### PR TITLE
Feature/api interfaces

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Add API endpoints to manage network interfaces

# Impacts
Unified API

# Delete branch after merge
YES

### CODE REVIEW

**Comment by julsemaan** [comment]
To be able to fully replicate the interfaces page of the current admin, API endpoints for networks will be needed (for the "ADD ROUTED NETWORK" button). Until then, everything should be available to replicate the page except for that feature. I'll very likely open another PR for the networks API

**Comment by extrafu** [comment]
💪

**Comment by satkunas** [comment]
`type` should be an array (and accept an array): "type": ["management","portal"]
```json
{
  "items": [
    {
      "enp0s3": { ... },
      "enp0s8": { ... },
      "enp0s9": {
        ...
        "type": "management,portal",
      },
      "is_running": false,
      "network_iseditable": false
    }
  ],
  "status": 200
}
```

Move the interface name from the object key into the value object as `id`:
```json
{
  "items": [
    { "id": "enp0s3", ... },
    { "id": "enp0s8", ... },
    { "id": "enp0s9", ... },
  ]
}
```

**Comment by satkunas** [comment]
Is `"type": "none"` a valid value, or should we use `"type": null` instead?
```json
{
  "item": {
    ...
    "type": "none"
  },
  "status": 200
}
```

**Comment by julsemaan** [comment]
@satkunas 

None is a value accepted by the current pfappserver model and a valid "enforcement" method so I believe it should stay since changing it could have some side effects.

I'll take care of translating to an array but I think type will have to stay a string and I'll push the additional stuff in additional_daemons which is used during the POST/PUT

**Comment by satkunas** [comment]
Errors have 1 too many nested levels of "message".

```json
{
  "errors": [],
  "message": {
    "message": "Interface lo doesn't exist"
  },
  "status": 404
}
```

**Comment by julsemaan** [comment]
@satkunas 

I've performed adjustments on the API endpoints, please check them again and let me know if I messed something else

**Comment by julsemaan** [comment]
@satkunas 

Can you check this again so we can get this ASAP and it doesn't rot here

**Comment by extrafu** [comment]
@satkunas Please confirm and merge so the GUI work around this can get going.

**Comment by satkunas** [comment]
@julsemaan looks good. Please rebase so I can merge.

**Pull request merged**
