### PR TITLE
Feature/remove Symantec Endpoint Protection Manager (SEPM)

### PR DESCRIPTION
**Pull request by JeGoi**
# Description
Remove Symantec Endpoint Protection Manager (SEPM) provisioner.

# Impacts
Provisioners
Web admin

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [x] Script that removes the SEPM provisioners from the conf/provisioning.conf
- [x] Script that removes the SEPM provisioners from the conf/profiles.conf

### CODE REVIEW

**Review by satkunas — APPROVED** [review]
UI changes look good.

**Review by nqb — CHANGES_REQUESTED** [review]
You don't need to remove content in .po files manually, it will be done automatically by a script

**Comment by nqb** [comment]
Also, I think we can also remove useless images (due to documentation removal)

**Comment by jrouzierinverse** [comment]
rebase please

**Comment by jrouzierinverse** [comment]
This is not compiling.
`/usr/local/pf/lib/pf/UnifiedApi/Controller/Config/Provisionings.pm`

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
Remove pfappserver::Form::Config::Provisioning::sepm from
`/usr/local/pf/lib/pf/UnifiedApi/Controller/Config/Provisionings.pm`

**Comment by JeGoi** [comment]
> You don't need to remove content in .po files manually, it will be done automatically by a script

Do you want me to restore them?

**Comment by JeGoi** [comment]
@jrouzierinverse Please, Files updated
Thanks

**Comment by extrafu** [comment]
@jrouzierinverse and @stgmsa all good? If so, just merge it

**Review by stgmsa — APPROVED** [review]

**Pull request merged**
