### PR TITLE
add profile name as args attribute

### LINKED ISSUE #5977: Audit log: profile has an empty value when doing Ethernet/Wireless-NoEAP
**Describe the bug**
When PacketFence received a RADIUS request with Ethernet/Wireless-NoEAP, even if request hits a specific connection profile, this information is not saved in DB. In place we have a `N/A`.

Behavior is the same if your device is registered or unregistered.

**To Reproduce**
1. Create a Mac Auth RADIUS request
2. Check "Profile" value on RADIUS Audit log menu
3. Check `packetfence.log` for this RADIUS request:

=> You can find a `instantiate profile NAME_OF_PROFILE` log

**Expected behavior**
Profile should be save in `radius_audit_log` table for such requests.

**Additional context**
I put FreeRADIUS in debug and I noticed that PacketFence doesn't return a `PacketFence-Profile` RADIUS attribute to FreeRADIUS. Consequently, FreeRADUS save a `N/A` in DB according to [queries.conf](https://github.com/inverse-inc/packetfence/blob/7d97560ee029c8264fba19a5f625ebb4c65ced77/raddb/mods-config/sql/main/mysql/queries.conf#L422)

```
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Processing response header
(81) Wed Nov 11 10:11:21 2020: Debug: rest:   Status : 100 (Continue)
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Continuing...
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Processing response header
(81) Wed Nov 11 10:11:21 2020: Debug: rest:   Status : 200 (OK)
(81) Wed Nov 11 10:11:21 2020: Debug: rest:   Type   : json (application/json)
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-IfIndex"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 8
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 8
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-IfIndex := "8"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Mac"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 00:03:00:11:11:01
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 00:03:00:11:11:01
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Mac := "00:03:00:11:11:01"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Switch-Id"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 44:38:39:00:00:12
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 44:38:39:00:00:12
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Switch-Id := "44:38:39:00:00:12"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-UserName"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 000300111101
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 000300111101
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-UserName := "000300111101"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "Tunnel-Private-Group-Id"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 100
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 100
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Tunnel-Private-Group-Id := "100"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Eap-Type"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 0
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 0
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Eap-Type := "0"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Request-Time"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 1605107481
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 1605107481
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Request-Time := 1605107481
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Role"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND headless_device
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> headless_device
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Role := "headless_device"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Authorization-Status"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND allow
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> allow
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Authorization-Status := "allow"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "Tunnel-Medium-Type"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 6
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 6
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Tunnel-Medium-Type := IEEE-802
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Status"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND reg
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> reg
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Status := "reg"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Switch-Mac"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 44:38:39:00:00:12
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 44:38:39:00:00:12
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Switch-Mac := "44:38:39:00:00:12"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "Tunnel-Type"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 13
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 13
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Tunnel-Type := VLAN
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-AutoReg"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND 0
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> 0
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-AutoReg := "0"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-IsPhone"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-IsPhone := ""
(81) Wed Nov 11 10:11:21 2020: Debug: rest: Parsing attribute "control:PacketFence-Connection-Type"
(81) Wed Nov 11 10:11:21 2020: Debug: rest: EXPAND Ethernet-NoEAP
(81) Wed Nov 11 10:11:21 2020: Debug: rest:    --> Ethernet-NoEAP
(81) Wed Nov 11 10:11:21 2020: Debug: rest: PacketFence-Connection-Type := "Ethernet-NoEAP"
```

### PR DESCRIPTION
**Pull request by nqb**
# Description
Profile is now a args and a node attribute. It means that when doing Ethernet-NoEAP or Wireless-NoEAP, connection profile matched is saved in radius_audit_log table.

# Impacts
RADIUS audit log

# Issue
fixes #5977

# Delete branch after merge
YES

# Checklist
- [x] Add unit tests

# NEWS file entries
## Bug Fixes
* Audit log: profile has an empty value when doing Ethernet/Wireless-NoEAP (#5977)

### CODE REVIEW

**Comment by nqb** [comment]
I tested with Ethernet-NoEAP and Ethernet-EAP and it works as expected.

I add integration tests to be sure profile is always available in RADIUS audit log.

**Comment by jrouzierinverse** [comment]
rebase

**Comment by nqb** [comment]
done

**Comment by jrouzierinverse** [comment]
rebase then I will merge!

**Comment by nqb** [comment]
done

**Pull request merged**
