### PR TITLE
Added a cleanup of the posted username on /login.

### PR DESCRIPTION
**Pull request by julsemaan**
Cleans up the username that's sent during the post to /login

Removes leading + trailing whitespaces.

Had reports of tablets auto-completing the username with a space at the end causing this issue

Should we merge this or ignore it since it's caused by a bug on the client side ?

### CODE REVIEW

**Comment by julsemaan** [comment]
Can someone comment + review + discuss. 

This is an intrusive PR and brings a maybe unexpected feature for users

**Comment by dwlfrth** [comment]
the _clean_username method doesn't belong in the Controller as per MVC way of thinking :)
Also, since we may want to use it elsewhere in the code, I'd put it in the util class (pf::util).

Oherwise, regex seems OK.
Would be great to test with a username containing spaces (ie: derek wuelfrath)

**Comment by julsemaan** [comment]
My opinion would be that it belongs there because it's correcting the user input that comes from the view.

The cleanup is not needed by the backend but is necessary because of the view.

**Comment by julsemaan** [comment]
This has been rebased. Can this be merged ?

**Pull request merged**
