### PR TITLE
feature/rename-database-backup-and-maintenance

### LINKED ISSUE #3061: Rename database-backup-and-maintenance.sh to backup-and-maintenance.sh
Ideally we should rename that script, as it not only takes care of the database backup, but also the /usr/local/pf/ one for config files, etc. So the script name is a bit misleading.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Rename database-backup-and-maintenance.sh to backup-and-maintenance.sh

Issue
=====
Fixes #3061

Delete branch after merge
=========================
NO

NEWS file entries
=========================

Enhancements
------------
* Rename addons/database-backup-and-maintenance.sh to addons backup-and-maintenance.sh

### CODE REVIEW

**Review by nqb — CHANGES_REQUESTED** [review]
I think we also need to change filename in UPGRADE.asciidoc.

**Comment by jrouzierinverse** [comment]
Done

**Comment by nqb** [comment]
We also need to upgrade this script: https://github.com/inverse-inc/packetfence-monitoring-scripts/blob/master/scripts/check-2388.sh#L8

I think a note in UPGRADE.asciidoc would be necessary for admins who use this script to backup PF from external tools.

**Comment by jrouzierinverse** [comment]
We do not need to update that script since it is only applies for packetfence version 7.0 and 7.1

**Comment by nqb** [comment]
Agree with you @jrouzierinverse

**Comment by julsemaan** [comment]
I'm moving this to 8.3 since the merge window for features is long gone

**Comment by fdurand** [comment]
Looks good to me.

**Pull request merged**
