### PR TITLE
Fix/radius default nas ip address

### LINKED ISSUE #5722: Accounting not working for switches that don't send NAS-IP-Address
I am getting this errors on accounting with Juniper switches, because they don't send NAS-IP-Address on accounting.
`Jul 25 16:38:04 pf packetfence_httpd.aaa: httpd.aaa(1999) ERROR: [mac:00:25:64:bb:b2:06] WARNING ! Unknown switch(es) 08:81:f4:ab:43:c0 (pf::SwitchFactory::instantiate)`

`Jul 25 16:38:04 pf packetfence_httpd.aaa: httpd.aaa(1999) WARN: [mac:00:25:64:bb:b2:06] Use of uninitialized value $switch_ip in concatenation (.) or string at /usr/local/pf/lib/pf/radius.pm line 387. (pf::radius::accounting)`

`Jul 25 16:38:04 pf packetfence_httpd.aaa: httpd.aaa(1999) WARN: [mac:00:25:64:bb:b2:06] Can't instantiate switch (). This request will be failed. Are you sure your switches.conf is correct? (pf::radius::accounting)`

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Add default NAS-IP-Address for standalone RADIUS

# Impacts
RADIUS inbound requests

# Issue
fixes #5722 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Define a default NAS-IP-Address when its missing from the RADIUS packet (was already there in cluster, extended it to standalone)

### CODE REVIEW

**Comment by julsemaan** [comment]
We should probably test this in a cluster to ensure we're not breaking anything

I tested standalone and it works fine

**Comment by julsemaan** [comment]
A package is available here for testing:
https://support.inverse.ca/~jsemaan/5723-rpms.zip

**Comment by lyubomirtraykov** [comment]
@fdurand  please commit to 10.0 and 10.1 maintenance

**Comment by fdurand** [comment]
It's done my lord

**Pull request merged**
