### PR TITLE
Security events GUI

### PR DESCRIPTION
**Pull request by julsemaan**
## This is not ready, its a work in progress and @satkunas will apply his magic to it

# Description
New admin security events GUI

# Impacts
Security events GUI

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by satkunas** [comment]
@julsemaan branch is re-based with latest devel.

**Comment by julsemaan** [comment]
@cgx, will you be using this PR for the GUI?

If not, lets close this

**Comment by cgx** [comment]
> @cgx, will you be using this PR for the GUI?

Yes.

**Comment by cgx** [comment]
@satkunas: Can we merge so @julsemaan can test?

**Pull request merged**
