### PR TITLE
eduroam local realm proxy

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Added the way to proxy eduroam local realm to another radius server (like nps)

# Impacts
- RADIUS eduroam workflow

# Delete branch after merge
(REQUIRED)
YES | NO

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Added a way to forward eduroam local realm to a define radius server instead of packetfence.

### CODE REVIEW

**Comment by fdurand** [comment]
Bump

**Comment by julsemaan** [comment]
I'm not sure we should have both the eduroam source and these configuration options because it will be confusing as to what should be configured where and what settings apply in both cases.

If we plan on having this as the way to integrate eduroam, we should deprecate the eduroam source and provide an upgrade script + instructions so that we can migrate to that

**Comment by fdurand** [comment]
The eduroam sources are still necessary if you want to deal with eduroam.
The goal of this PR is per example you don't want to join the PacketFence server to the domain but to authenticate incoming request (from eduroam server) to a 3rd party server (like the MS NPS server).

**Comment by julsemaan** [comment]
So just to make sure, if we leave all of this as default all the existing inbound/outbound eduroam we already have will work as-is?

**Comment by fdurand** [comment]
yes

**Pull request merged**
