### PR TITLE
Add postrotate for logrotate status

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description
Logrotate will "log" it's return code for maintenance scripts to check

# Impacts
Logrotate

# Delete branch after merge
YES

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by julsemaan** [comment]
Was this config tested on Debian ?

**Comment by dwlfrth** [comment]
No, don't have one but should be fairly quick and easy to test.

**Comment by julsemaan** [comment]
Can one of the Debian gods setup the new logrotate on his devbox and see if it rotates tomorrow.

**Comment by dwlfrth** [comment]
Tested on Debian and seems to be running just fine.

**Comment by julsemaan** [comment]
@dwlfrth is now part of the Debian elite.. Wow

All looks good.

Shall we cherry-pick this to maintenance as your new monitoring scripts should warn us about the presence of that new file and should be able to use it ?

**Comment by dwlfrth** [comment]
@julsemaan, yep.

**Comment by dwlfrth** [comment]
Wait before merge. Need to check something with Debian god.

**Comment by dwlfrth** [comment]
Please review

**Pull request merged**
