### PR TITLE
add CLI access support to HP Procurve

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Add CLI support to HP Procurve switches

# Impacts
HP Procurve switches

# Delete branch after merge
YES

# NEWS file entries
## New Features
- Added CLI login support for HP Procurve switches

### CODE REVIEW

**Comment by extrafu** [comment]
Should we provide some docs for this? ie., how to configure the switch to use PacketFence for CLI authentication.

**Comment by extrafu** [comment]
What's the status on this?

**Comment by julsemaan** [comment]
Will need a test procurve or setup with one to write the documentation

**Comment by extrafu** [comment]
Bump!

**Comment by yugoos** [comment]
I've got about 160 procurve 2610/2620 switches and cli access is working after alertering vsa to Service-type = Administrative-User [(freeradius procurve doc)](https://wiki.freeradius.org/vendor/HP#procurve-administrative-interface-authentication-special-features_privilege-mode_enable-privilege-mode)

However, some switches seem to send an ip address in either the mac or called-station-id field so packetfence thinks its a authorisation request (wired-mac) and fails with a module error complaing about a empty mac address.

Im not a programmer but am able to read code, yet i'm not sure how modules are called/linked to find a fix.
How can i help to fix this?
What logs do you need?

**Comment by julsemaan** [comment]
This is a pull request and isn't meant for bug tracking.

Your issue belongs on the PacketFence mailing list

**Pull request merged**
