### PR TITLE
add radius filter to use ttls-pap username from inner tunnel in reply

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Makes the User-Name sent in a TTLS-PAP reply use the identity of the inner tunnel

# Impacts
EAP-TTLS PAP

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* The User-Name value in an EAP-TTLS PAP reply will always be the identity of the inner tunnel

### CODE REVIEW

**Comment by julsemaan** [comment]
One downside I see using this approach (RADIUS filter) is that if the user defines another filter that matches after this one in EAP-TTLS PAP, it will never match. I see 2 solutions for this:

- Allow more than 1 filter to match in the RADIUS filters (could have a use outside of the scope of this PR too)
- Implement this in the code directly in radius.pm instead of through a filter

Happy to hear the opinion of the team around this

**Comment by fdurand** [comment]
i have a concern about that, if we do that it mean that it will remove the anonymous identity for the eap-ttls.
Btw with peap we use that in the peap section: "use_tunneled_reply = yes" just because we compute the answer in packetfence-tunnel/post-auth.
So i am not sure if it´s ok or no.

Also we can do it directly in unlang:

```
if ( outer.EAP-Type == TTLS) {
update {
 &reply:User-Name = %{User-Name}
}

**Comment by julsemaan** [comment]
> i have a concern about that, if we do that it mean that it will remove the anonymous identity for the eap-ttls. Btw with peap we use that in the peap section: "use_tunneled_reply = yes" just because we compute the answer in packetfence-tunnel/post-auth. So i am not sure if it´s ok or no.
> 
> Also we can do it directly in unlang:
> 
> ```
> if ( outer.EAP-Type == TTLS) {
> update {
>  &reply:User-Name = %{User-Name}
> }
> ```

I think the unlang way would be better. AFAIK, the attributes are properly tunneled but the outer tunnel handler adds the User-Name even though nowhere in the configuration it says to do so.

I think I'll try to implement your solution instead, would `post_auth` be the best section to put that in `packetfence-tunnel`?

**Comment by fdurand** [comment]
I think you can add it in packetfence-tunnel in the authorized section (there is already a test with TTLS)

**Comment by fdurand** [comment]
The logic as been ported in unlang instead of the radius filter.

**Pull request merged**
