### PR TITLE
feature/config-syslog_forwarder

### LINKED ISSUE #3569: Add ConfigStore::SyslogForwarding endpoints

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Fixes #3569

Description
===========

Add ConfigStore::SyslogForwarding endpoints

### CODE REVIEW

**Comment by satkunas** [comment]
I'm unable to tell how the `$base_url` from the test unit is used. I assume it's for the `PUT`, `PATCH` and `DELETE` methods. 
- Write tests for  the `PUT`, `PATCH` and `DELETE` methods
- Document all the endpoints in the openapi spec.

**Comment by extrafu** [comment]
Bump - what's the status on this one?

**Comment by jrouzierinverse** [comment]
The documentation will auto generated when fix/openapi-doc is merged.

**Comment by extrafu** [comment]
Bump.

**Comment by satkunas** [comment]
@jrouzierinverse please rebase

**Comment by jrouzierinverse** [comment]
This was rebased

**Comment by extrafu** [comment]
@satkunas Can we merge?

**Pull request merged**
