### PR TITLE
Update backup script to support remote databases

### PR DESCRIPTION
**Pull request by nqb**
# Description
- Backup remote MariaDB databases (standalone or Galera clusters)
- Refactor code

# Impacts
Backup script

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Backup remote MariaDB databases  (standalone or Galera clusters) from pf servers

### CODE REVIEW

**Comment by nqb** [comment]
@lzammit, did you to test it ?

**Comment by nqb** [comment]
@lzammit, could you review ?

**Comment by extrafu** [comment]
Remote backups should be disabled by default.

1- @nqb adjust the scripts to respect that
2- rebase

**Comment by nqb** [comment]
@extrafu:
- PR rebased
- Remote backups are only enabled if you set variable `MARIADB_REMOTE_CLUSTER` to `1` (`0` by default)

**Comment by extrafu** [comment]
Looks good to me, @fdurand can you also review please?

**Pull request merged**
