### PR TITLE
feature/wmi-post-filter

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Move WMI filtering to use pf::condition::* and allow functions to be exposed via filtering

Impacts
=======
WMI scanning

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
I'm not sure the description is really what you've wanted..

**Comment by extrafu** [comment]
@jrouzierinverse and @lzammit Please pull the working example from the customer and put it in the .example configuration file.

**Comment by julsemaan** [comment]
Tested with provided example and its always triggering even when there is an update that is less than 30 days old

**Comment by julsemaan** [comment]
The following example does work through:
```
[InstalledOn]
operator = advance
value = Date.Diff('DAYS', Date.Now(), Date.Parse("%m/%d/%Y", ${InstalledOn})) > 30

[1:InstalledOn]
match=all
action=trigger_violation
action_param = mac = $mac, tid = OUTOFZEDATEEEEE, type = INTERNAL
```

Thanks to @lzammit / MonsieurSandwich

**Comment by julsemaan** [comment]
The example needs to be updated to the working one provided above and we're good to merge

**Comment by jrouzierinverse** [comment]
done

**Pull request merged**
