### PR TITLE
feature/request-cache

### LINKED ISSUE #1775: request cache

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Provided the ability to cache the results a function
## Impacts

node_view SwitchFactory and ProfileFactory
## Issue

Fixes #1775
## NEWS file entries

Enhancements
++++++++++++

Bug Fixes
+++++++++
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Ready for review

**Comment by fdurand** [comment]
Maybe i am wrong but can we cache node_attributes too ?

**Comment by jrouzierinverse** [comment]
Yes we could.

**Comment by fdurand** [comment]
The code looks to be good, i have to test it first before merging

**Comment by jrouzierinverse** [comment]
As discussed we would need to remove caching the profile filters at the moment.

**Comment by fdurand** [comment]
Can't locate CHI/Memoize.pm in @INC (@INC contains: /usr/local/pf/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/local/pf/lib/pf/node.pm line 28.

**Comment by dwlfrth** [comment]
Perhaps you forgot to load CHI/Memoize ? Or perhaps you forgot to load autocorrect 💃

**Comment by dwlfrth** [comment]
Ahaha it's actually the real name ! Sorry 'bout that :P

**Comment by fdurand** [comment]
Tested and OK.
Except missing dep in spec and control file and you have to remove caching of the profile filters, this PR looks ok.

**Comment by jrouzierinverse** [comment]
done

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Pull request merged**
