### PR TITLE
OpenVAS/GVM: Add a field for port list ID to support GVM (formerly OpenVAS) 20

### LINKED ISSUE #5791: openvas20.0.8 require port list id while creating target
hey , openvas upgraded and omp unable to create task with error require port list . kindly upgarde this .

PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2577) INFO: [mac:[undef]] Creating a new scan target named 160008315756ae61600083157.5xxxx for host 10.x.x.x (pf::scan::openvas::createTarget)
 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2577) WARN: [mac:[undef]] There was an error creating scan target named 160008315756ae61600083157.5xxxx, here's the output: <create_target_response status_text="One of PORT_LIST and PORT_RANGE are required" status="400"></create_target_response> (pf::scan::openvas::createTarget)
PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2577) INFO: [mac:[undef]] Creating a new scan task named 160008315756ae61600083157.5xxxx (pf::scan::openvas::createTask)
PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2577) WARN: [mac:[undef]] Use of uninitialized value $target_id in concatenation (.) or string at /usr/local/pf/lib/pf/scan/openvas.pm line 324.
 (pf::scan::openvas::_get_task_string)
 PacketFence-ZEN packetfence_httpd.aaa: httpd.aaa(2577) WARN: [mac:[undef]] There was an error creating scan task named 160008315756ae61600083157.5xxxx, here's the output: <create_task_response status_text="Failed to find target ''" status="404"></create_task_response> (pf::scan::openvas::createTask)

### PR DESCRIPTION
**Pull request by aveao**
# Description
GVM (formerly OpenVAS) 20 adds a breaking change where it requires users to supply a PORT_LIST or PORT_RANGE UUID: https://docs.greenbone.net/API/GMP/gmp-20.08.html#changes

This PR adds an additional config field for that a la report format ID, alert ID, scan config ID:

This is currently a breaking patch where previous OpenVAS/GVM will break until they set a port list ID. Please let me know if any other behavior is expected and I will do my best to change the code to do that.

# Impacts
- OpenVAS (/GVM) compliance settings and scans

# Issue
fixes #5791

# Delete branch after merge
YES

# Checklist
- [yes] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

(Other fields lack unit tests and acceptance tests)

# NEWS file entries
## Bug Fixes
* OpenVAS settings now allow setting a port list ID, fixing support for GVM 20 (#5791)

# UPGRADE file entries
## New OpenVAS field for port lists

In order to use the OpenVAS compliance checks, navigate to _Configuration -> Port lists_ on GVM/OpenVAS's Web UI, select the port list you would like to use to scan the hosts, and add it to your OpenVAS scanner configuration.

### CODE REVIEW

**Comment by aveao** [comment]
This is my first ever PR to PF, so my overall knowledge on how to contribute properly is limited. I did my best to read the relevant docs on both this repo and on the developer guide, but please let know if there's anything I missed and I'll do my best to fix it.

**Comment by LizardNerd** [comment]
I'm trying to integrate GVM 20.08 with PacketFence but I can't see the "Port list ID" section. Is this bug actually fixed? I'm running packetfence 10.2.0+20201007132254+199263253+0009+v10.2.0+stretch1. Thank you in advance.

**Comment by aveao** [comment]
@LizardNerd this PR is not yet merged into upstream, as such the bug is not yet fixed on packetfence releases like the one you have installed.

**Comment by LizardNerd** [comment]
@aveao I fixed the problem thanks to your changes. Anyway, there is still an issue whit "report_id" column on PF's MySQL database when I successfully start a scan trought PF, I think that for this reason, I can't get a report back from GVM 20.08 to PF. I've been puzzling over this issue for a week now. 
Can I ask you for a hand? I enclose a zip with various logs and more. Really thank you if you can put an eye on this.

[info_debug.zip](https://github.com/inverse-inc/packetfence/files/6082559/info_debug.zip)

Some info:
PF management ip: 192.168.50.56
GVM 20.08: 192.168.50.228

P.s. At this point I'm doing the scan to 192.168.50.56 (PF) because I don't know how to scan IP on Registration, Isolation and Normal VLAN.

**Comment by syir-cjodex** [comment]
hello
Can someone help me with this.. 
I followed  the fix but I couldn't find the directory /docs/api to modify the files 
docs/api/spec/components/schemas/configscan.yaml
docs/api/spec/openapi.json
And as you can see I still don't have the option " port list ID" displayed
Is it because of these files ? 
pf

**Pull request closed without merging**
