### PR TITLE
feature/reset-search

### LINKED ISSUE #1581: Admin Searches: Should have option to reset the search
There should be an option to reset the search back to empty whether it is saved or not.

In: 
- RADIUS audit log
- Node search
- Users search

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Reset search forms

Issue
=====
fixes #1581

Delete branch after merge
=========================
NO

NEWS file entries
=================

Enhancements
------------
* Allow the ability reset the search forms

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
When testing this you would need to run ```grunt js```

**Review by julsemaan — COMMENTED** [review]
Just tested it and the button indeed resets the search but then it leaves the current view unchanged which means the view isn't consistent with the current search. I believe we should submit the new empty form so the view is consistent with the action that was taken

**Comment by jrouzierinverse** [comment]
OK

**Comment by jrouzierinverse** [comment]
Done

**Pull request merged**
