### PR TITLE
[Docs] Reorganize Documentation content

### PR DESCRIPTION
**Pull request by JeGoi**
# Description
This branch reorganize doc content in trees and leaf.
Each major file (cluster, install, network, upgrade) has now a dedicated directory with content.
Each major file is divided in sub-file according to the title level2
If a sub-file is/could be divided in something more readable, a new directory is created with the content in separated files.
Images are in same place as before. Only contents have changed.

Other content modifications:
- Clean all titles and subtitles with the = style
- Make almost all navigation in italic (it could be changed later)
- Try to make all buttons with ` (back quote - probably not exhaustive)
- Try to use  * bold when it is needed (and remove italic or simple/double quotation marks)

This branch has merged modifications and discussions from PR #5873 
(PR #5873 could be closed when this one is merged)

# Impacts
PRO:
- Reduce the size of each files => More readable by human
- Reorganize easily
- Create network-device will be more easily done etc.

CONS:
- a split is some time not that easy to compile if too much split => could be transform in another maze

# Delete branch after merge
YES

# Checklist
- [x] Other PR not yet merged

### CODE REVIEW

**Review by nqb — CHANGES_REQUESTED** [review]
### Remarks

#### Ansible changes

I didn't see your [changes related to Ansible from previous PR](https://github.com/inverse-inc/packetfence/pull/5873/files/fc2931de399201a85a007eef3ddcb4528bec3014#diff-ee51b23e62a6f2793867041f327b8b1784b8e5ae2285840aca3c037da106001a).

Perhaps, we can add them in #5940 

### Rebase

This PR needs to be rebased on `devel` branch.

### NEWS file

@cgx, do we want NEWS file published on http://packetfence.org ? 

If yes, @JeGoi you need to create a PR similar to https://git.inverse.ca/inverse/website-packetfence/pulls/2.

But see my comment below.

### `make html` target

In current state of this PR, `make html` target will only work if you modify a top level asciidoc file (like `PacketFence_Installation_Guide.asciidoc`) but not for `installation/installation.asciidoc`. 

### GitHub display

To have correct display of images and TOC on GitHub, we duplicate some content in several asciidoc files. We should avoid this.

My proposal is to publish a devel version of your documentation on http://packetfence.org. We can build this using your CI.

### AsciiDoc conventions

Using:
- `_` for menus
- backquotes for buttons

looks good to me. @cgx, is it ok for you ? I suppose that PDF display will be correct when #5968 is merged.

@JeGoi: 
1. In which case do you use bold ?
2. You need to update AsciiDoc conventions in Developers' guide. Perhaps with a specific section like for Titles.

**Comment by cgx** [comment]
> @cgx, do we want NEWS file published on http://packetfence.org ?

No. We already have a [news](https://packetfence.org/news.html) section. @JeGoi please rollback your changes.

> To have correct display of images and TOC on GitHub, we duplicate some content in several asciidoc files. We should avoid this.

I've fixed this in [PR#5968](https://github.com/inverse-inc/packetfence/pull/5968).

**Comment by JeGoi** [comment]
> ### `make html` target
> 
> In current state of this PR, `make html` target will only work if you modify a top level asciidoc file (like `PacketFence_Installation_Guide.asciidoc`) but not for `installation/installation.asciidoc`.

Radical Solution: Maybe clean the directory first. It will create the file each time.

**Comment by JeGoi** [comment]
> ### AsciiDoc conventions
> 
> @JeGoi:
> 
>     1. In which case do you use bold ?

Text that need attention from the reader. If you miss that part, well, it will break your PF.

>     2. You need to update AsciiDoc conventions in Developers' guide. Perhaps with a specific section like for Titles.

Ok good idea.

**Comment by JeGoi** [comment]
> > @cgx, do we want NEWS file published on http://packetfence.org ?
> 
> No. We already have a [news](https://packetfence.org/news.html) section. @JeGoi please rollback your changes.

Ok.
@cgx, So, could we remove references to this part in all major doc ([example](https://packetfence.org/doc/PacketFence_Installation_Guide.html#_other_sources_of_information))?
The link is here but it is not a real link. It looks like dead.
Another idea, we could add a link to the [news section](https://packetfence.org/news.html), no?
```
NEWS.asciidoc
    Covers noteworthy features, improvements and bug fixes by release.
```

**Comment by JeGoi** [comment]
> ### Rebase
> 
> This PR needs to be rebased on `devel` branch.

Ouch. Ok not sure how long it will take...

**Comment by JeGoi** [comment]
> ### `make html` target
> 
> In current state of this PR, `make html` target will only work if you modify a top level asciidoc file (like `PacketFence_Installation_Guide.asciidoc`) but not for `installation/installation.asciidoc`.

Radical Solution: Maybe clean the directory first. It will create the file each time.

Hum, it looks that there is now a `clean` from #5968

**Comment by nqb** [comment]
>  Another idea, we could add a link to the [news section](https://packetfence.org/news.html), no?

Looks like a good idea.

**Comment by nqb** [comment]
> Ouch. Ok not sure how long it will take...

I know but it's something we should do quickly. 

> Radical Solution: Maybe clean the directory first. It will create the file each time.

In fact `make -B html` works. Issue was present before this PR but now with each major file splitted, issue is more visible.

**Comment by JeGoi** [comment]
> > Ouch. Ok not sure how long it will take...
> 
> I know but it's something we should do quickly.
> 
Ok I will do it that today

**Comment by JeGoi** [comment]
Ok rebased is done.

**Comment by JeGoi** [comment]
> ### GitHub display
> 
> To have correct display of images and TOC on GitHub, we duplicate some content in several asciidoc files. We should avoid this.
> 
> My proposal is to publish a devel version of your documentation on http://packetfence.org. We can build this using your CI.

I haven't work on this part. I am pretty sure that tags are needed with Github. But @cgx is more advanced than me on that and you proposed another solution. So. I guess that we can do that part later, if we want to have that PR merged quickly.

**Comment by JeGoi** [comment]
> #### Ansible changes
> 
> I didn't see your [changes related to Ansible from previous PR](https://github.com/inverse-inc/packetfence/pull/5873/files/fc2931de399201a85a007eef3ddcb4528bec3014#diff-ee51b23e62a6f2793867041f327b8b1784b8e5ae2285840aca3c037da106001a).
> 
> Perhaps, we can add them in #5940

Also I did not work on that part because I was waiting your comment/advice. And perhaps I was wrong...

**Pull request merged**
