### PR TITLE
Added vsys support for paloalto firewall

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Added vsys support for Paloalto Firewall SSO

# Impacts
Need to revalidate the firewall sso config in order to set vsys default value

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* vsys (virtual firewall) support in PaloAlto firewall sso modulw

# UPGRADE file entries
Save the firewall sso config for PaloAlto to define a default value to vsys parameter

### CODE REVIEW

**Comment by julsemaan** [comment]
Not really clear what vsys does.

That should be clarified with a help close to the field and adjusting the paloalto guide if necessary

**Comment by olmanolsztyn** [comment]
Palo-Alto devices can use multiple vsys (virtual systems).
Before you could put firewall sso credentials only to vsys1 as default after succesful registering.
Now you can define another vsys number if u have users in another vsys on Palo Alto firewall.

**Comment by extrafu** [comment]
@julsemaan That's that one I meant for the new firewall SSO code. Should you "convert" it in Go and close that PR?

**Comment by julsemaan** [comment]
Yes I should

**Comment by julsemaan** [comment]
opened #2061 for the golang version of this

**Pull request closed without merging**
