### PR TITLE
bootstrap-vue v2.0.0

### PR DESCRIPTION
**Pull request by cgx**
# Description
Adapt code to [bootstrap-vue v2.0.0](https://bootstrap-vue.js.org/docs/misc/changelog) (and consequently [vue v2.6](https://medium.com/the-vue-point/vue-2-6-released-66aa6c8e785e)).

### CODE REVIEW

**Comment by julsemaan** [comment]
Putting this in 9.1 would be fairly unsafe IMO since we're almost done with testing and are in feature-freeze for almost 2 weeks

**Comment by nqb** [comment]
Agree with @julsemaan

**Comment by satkunas** [comment]
Missing `v-slot` in:

* https://github.com/inverse-inc/packetfence/blob/feature/bootstrap-vue-2.0.0/html/pfappserver/root/static.alt/src/components/pfConfigList.vue#L46
* https://github.com/inverse-inc/packetfence/blob/feature/bootstrap-vue-2.0.0/html/pfappserver/root/static.alt/src/components/pfFormChosen.vue#L4
* https://github.com/inverse-inc/packetfence/blob/feature/bootstrap-vue-2.0.0/html/pfappserver/root/static.alt/src/components/pfFormChosen.vue#L36

**Comment by cgx** [comment]
@satkunas All fixed. You can merge.

**Pull request merged**
