### PR TITLE
feature/disable-domain

### LINKED ISSUE #3971: Have the ability to disable a domain

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Add the ability to disable a domain

Impacts
=======
Domain handling

Issue
=====
Fixes #3971

Delete branch after merge
=========================
NO

UPGRADE
=========================

Run addons/upgrade/to-9.1-add-domain-conf.pl to add status=enabled to each section.

### CODE REVIEW

**Comment by fdurand** [comment]
It miss the way to restart winbindd when you disable/enable the domain.

**Comment by extrafu** [comment]
@fdurand Review and test and let's decide if we keep it for v9.1.

**Comment by fdurand** [comment]
Needs an upgrade script to set the value in existing domain.

**Comment by jrouzierinverse** [comment]
done

**Pull request merged**
