### PR TITLE
Connection pool for LDAP connections

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Connection pool for LDAP connections
## Impacts

LDAP Authentication sources
## NEWS file entries

New Features
++++++++++++
- Pool LDAP connections to avoid unnecessary reconnection
## Delete branch after merge

NO

### CODE REVIEW

**Comment by julsemaan** [comment]
Not able to run pftest against an LDAP source with this code.

It dies without any error in the output or in the log.

On an Active Directory source pointing to the Inverse AD

Output : 

```
┌─[✗]─[pf-julien]─[/usr/local/pf]-((detached from refs/pull/origin/1241))$ 
└──╼  bin/pftest authentication lzammit ''
Testing authentication for "lzammit"

Authenticating against local
  Authentication FAILED against local (Invalid login or password) 
  Did not match against local
  Did not match against local

Authenticating against file1
  Authentication FAILED against file1 (Invalid login or password) 
  Did not match against file1
  Did not match against file1

Authenticating against sms
  Authentication FAILED against sms () 
  Matched against sms for 'authentication' rules
    set_role : sms
    set_access_duration : 1D
  Did not match against sms

Authenticating against email
  Authentication FAILED against email () 
  Matched against email for 'authentication' rules
    set_role : email
    set_access_duration : 1D
  Did not match against email

Authenticating against sponsor
  Authentication FAILED against sponsor () 
  Matched against sponsor for 'authentication' rules
    set_role : guest
    set_access_duration : 1D
  Did not match against sponsor

Authenticating against null
  Authentication FAILED against null () 
  Matched against null for 'authentication' rules
    set_role : default
    set_access_duration : 12h
  Did not match against null

Authenticating against inverse
┌─[✗]─[pf-julien]─[/usr/local/pf]-((detached from refs/pull/origin/1241))$ 
└──╼  

```

**Comment by jrouzierinverse** [comment]
Send me the configuration

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by julsemaan** [comment]
sent via FAX machine

**Comment by jrouzierinverse** [comment]
Send it via telex

**Comment by julsemaan** [comment]
Not secure enough.

In my book, there is nothing safer than fax machines.

**Comment by rouzier** [comment]
Please re-review

**Comment by julsemaan** [comment]
Next time you need a re-review, please don't forget to send a fax to Zammitcorp.

Response time are much faster

**Pull request merged**
