### PR TITLE
Fix/Change the how the date range search works in node search

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Fix/Change the how the date range search works in node search.
The date range search will use the detect date instead of the locationlog
## Impacts

Admin GUI Node advanced search 
## NEWS file entries

Bug Fixes
+++++++++
Fix the date range search in node advanced search
## Delete branch after merge

NO

### CODE REVIEW

**Comment by louismunro** [comment]
Does not seem t work for a node seen today.

**Comment by jrouzierinverse** [comment]
Give it a try now

**Comment by julsemaan** [comment]
We should add a description of what this does on the left of the range. Right now we don't even know what it searches on. 

I suggest : 

Detected between :

**Comment by julsemaan** [comment]
Other than that it works fine. Including with nodes detected today

**Comment by jrouzierinverse** [comment]
Update please review

**Comment by louismunro** [comment]
Let me test quickly and report.

**Comment by louismunro** [comment]
Works for me. 
Will merge.

**Pull request merged**
