### PR TITLE
Update golang

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Update to golang 1.21.3

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Update to golang 1.21.3

### CODE REVIEW

**Comment by JeGoi** [comment]
Please rebase on devel.
NodeJS issue etc.
Thank you

**Comment by jrouzierinverse** [comment]
done

**Comment by satkunas** [comment]
@jrouzierinverse please also look at merging the dependabot PRs for golang: https://github.com/inverse-inc/packetfence/pulls?q=is%3Aopen+is%3Apr+author%3Aapp%2Fdependabot+go

**Comment by jrouzierinverse** [comment]
I closed those and manually updated those dependencies.

**Review by JeGoi — APPROVED** [review]
CI with tests is perfect.
Thanks ready to merge.

**Comment by satkunas** [comment]
@jrouzierinverse please fix the conflict and merge when ready

**Comment by jrouzierinverse** [comment]
rebased

**Pull request merged**
