### PR TITLE
feature/mysql-compatibility

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
MySQL Compatibility

# Impacts
pfcron

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* MySQL Compatibility

### CODE REVIEW

**Comment by julsemaan** [comment]
@satkunas, make sure you review this ASAP so we can get these in devel

Thanks!

**Review by satkunas — APPROVED** [review]
SQL looks good, but I haven't tested.

**Comment by extrafu** [comment]
@JeGoi and @satkunas what's the status on testing this in the CI environment?

**Comment by JeGoi** [comment]
Just Launch the unit test: https://gitlab.com/inverse-inc/packetfence/-/jobs/2757844555 it is a cron test. The job can fail due to the perl test but if the cron is good, it should be good.

**Comment by extrafu** [comment]
@JeGoi Status on this?

**Comment by JeGoi** [comment]
The unit golang test passed and it is good enough according to @jrouzierinverse 
Like expected perltest and pfcron are falling since based on devel branch.

**Comment by extrafu** [comment]
@satkunas So let's merge that PR right now please!

**Pull request merged**
