### PR TITLE
fix/3670

### LINKED ISSUE #3670: sponsor guest registration: untranslated email
To reproduce: Create a sponsor request by visiting captive portal with a web browser configured in French.

Actual result: Sponsor will receive an email with:
* subject in French (see #3669)
* content in English

Expected result: Sponsor should receive email with subject and content in French. 

Template contains I18n tags and chains are present in `conf/locale/fr/LC_MESSAGES/packetfence.po`

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
I18n email subject right before sending the email.

Impacts
=======
Sponsor email

Issue
=====
Fixes #3670

Delete branch after merge
=========================
NO

NEWS file entries
=================

Bug Fixes
------------
* Sponsor Email subject and body are i18n in the same language (#3670)

### CODE REVIEW

**Comment by julsemaan** [comment]
Please put the appropriate tags and milestone

Otherwise it'll just get forgotten if this needs to go in 8.2 or in the maintenance

**Comment by nqb** [comment]
@jrouzierinverse,

Should I wait future commits before testing ?

**Comment by jrouzierinverse** [comment]
Nope, Test away!
This just fixes the fact there are two different i18n for the email.

**Comment by nqb** [comment]
@jrouzierinverse, tested. Works as expected. Good job ;-)

**Comment by nqb** [comment]
I think we can cherry-pick in maintenance, I can do it if you want.

**Comment by jrouzierinverse** [comment]
Can you merge this then?

**Comment by nqb** [comment]
Yes of course.

**Comment by nqb** [comment]
Done in maintenance too.

**Pull request merged**
