### PR TITLE
feature/remove-multi-tenant

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Remove multi tenant

# Impacts
Multi Tenant support

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Remove multitenant support

### CODE REVIEW

**Comment by julsemaan** [comment]
@jrouzierinverse, please rebase another time, I'll take a look right after so that it doesn't conflict again

**Comment by jrouzierinverse** [comment]
Done

**Comment by julsemaan** [comment]
It doesn't look like the upgrade script handles the reconfiguration of the realms to strip their tenant ID and delete the realms of outdated tenants

**Comment by julsemaan** [comment]
I've launched a pipeline to build this branch and IMO before merging this, we should do a test on this branch with a fresh install and a basic use-case and also a test where we upgrade an existing environment in our lab to make sure upgrading through this won't cause major issues.

Once the build is passing, we can see who could do these tests

**Comment by jrouzierinverse** [comment]
The code is there to do it?
Did you test and it did not work or were you eyeballing it?

https://github.com/inverse-inc/packetfence/blob/c035333d80818c34d6320295d83aa27510e86b07/addons/upgrade/to-12.0-remove-tenant.pl#L51

> It doesn't look like the upgrade script handles the reconfiguration of the realms to strip their tenant ID and delete the realms of outdated tenants

**Comment by julsemaan** [comment]
> The code is there to do it? Did you test and it did not work or were you eyeballing it?
> 
> https://github.com/inverse-inc/packetfence/blob/c035333d80818c34d6320295d83aa27510e86b07/addons/upgrade/to-12.0-remove-tenant.pl#L51
> 
> > It doesn't look like the upgrade script handles the reconfiguration of the realms to strip their tenant ID and delete the realms of outdated tenants

Code reading only, the builds aren't ready for testing yet. I missed that line while reading

**Comment by julsemaan** [comment]
On a fresh install on Debian 11, pfconfig fails to start during the packaging install and the install fails because of that
Package from: https://gitlab.com/inverse-inc/packetfence/-/pipelines/537663834
Log of pfconfig: https://support.inverse.ca/~jsemaan/pfconfig-multi-tenant-removal.log

**Comment by jrouzierinverse** [comment]
Done and tested

**Comment by julsemaan** [comment]
Passed a build and french install, merging

**Pull request merged**
