### PR TITLE
Feature/remove default switch

### PR DESCRIPTION
**Pull request by fdurand**
Remove the switch 127.0.0.1 in the switches.conf and instantiate it on the code
## 

NEWS entry:
- Removed static configuration of 127.0.0.1 switch in switches.conf to avoid borked configuration by people who deleted this one switch needed for communication between PacketFence and pfsetvlan.

UPGRADE entry:
- We removed the static configuration of 127.0.0.1 switch in switches.conf as described in the NEWS document. You can safely remove this one switch from your current configuration. Failure to do so won't affect the proper functioning of the solution but we encourage you to proceed.

### CODE REVIEW

**Comment by dwlfrth** [comment]
Wondering if we can get rid of the 127.0.0.1 in bin/pfcmd line 995 since this switch is no longer part of the config? (That's a question)

**Comment by dwlfrth** [comment]
Added some NEWS/UPGRADE documents entries (in the pull-request comment). Review of these would be appreciated.

**Comment by dwlfrth** [comment]
- Shouldn't we add a check in the switches.conf section of checkup.pm to make sure 127.0.0.1 is off the config and if not, display a status message at start time?
- What is the behavior if 127.0.0.1 is still present in switches.conf?
- Maybe we should add either an "addon script" that will remove the 127.0.0.1 section and document it in UPGRADE, or manage the instantiation in a different way if the section is present.

**Comment by fgaudreault** [comment]
Merged in Devel.

**Pull request closed without merging**
