### PR TITLE
Feature/admin improvements

### PR DESCRIPTION
**Pull request by whitx**
# Description
This is a full revamping of the admin interface, removing, reorganize sections and a new CSS apply.

# Impacts
Admin interface

# Delete branch after merge
NO

# NEWS file entries
## Enhancements
* The admin interface has been redone, section reorganize and a new look has been applied

# UPGRADE file entries

A major rename of multiple sections and parametersof pf.conf was done. An upgrade script is provided to automate the renaming of all those entries. In order to migrate your pf.conf, execute:

```
# /usr/local/pf/addons/upgrade/to-7.0-pf-conf-changes.pl
```

### CODE REVIEW

**Comment by julsemaan** [comment]
We need an upgrade script to rename 
* Sections: trapping, vlan, registration, monitoring
* Parameters: services.pfdhcplistener_packet_size, registration.device_registration, registration.device_registration_role
* Call out deprecation of: services.suricata, services.suricata_binary, services.snort, services.snort_binary, general.dnsservers, trapping.detection, trapping.detection_engine, alerting.log, trapping.wireless_ips, trapping.wireless_ips_threshold, pfwatch, advanced.reevaluate_access_reasons, pfcmd colors

**Comment by julsemaan** [comment]
Found issues which we'll need to fix prior to merging:
* RADIUS audit log quick searches are broken, most of the dropdowns don't open anything (sources, realms, domains, ...)
* Same as above for DHCP option 82
* If you have 2 custom reports, you click on one of them, then on the other one and the second one never loads and you get a bunch of JS errors (I can provide those if needed). After that, you can't navigate any of the reports
* Searching nodes by 'Online status' generates the following error in the logs: `Mar 23 07:29:20 httpd.admin(5485) ERROR: Caught exception in pfappserver::Controller::Node->search "ARRAY(0x7ff2823bf070) is not a supported search operation at /usr/local/pf/html/pfappserver/lib/pfappserver/Base/Model/Search.pm line 50." (pfappserver::PacketFence::Controller::Root::end)` Other searches work fine. Will need to confirm if this is caused by this PR or if the bug is in devel
* We're still trying to load a bunch of resources that don't exist anymore: `
GET 
https://172.20.20.109:1443/static/app/bootstrap-datepicker.js [HTTP/1.1 404 Not Found 0ms]
GET 
https://172.20.20.109:1443/static/app/jquery-ui.js [HTTP/1.1 404 Not Found 0ms]
GET 
https://172.20.20.109:1443/static/app/chosen.jquery.min.js [HTTP/1.1 404 Not Found 0ms]
GET 
https://172.20.20.109:1443/static/app/bootstrap-datepicker.js [HTTP/1.1 404 Not Found 2ms]
GET 
https://172.20.20.109:1443/static/app/chosen.jquery.min.js [HTTP/1.1 404 Not Found 1ms]
GET 
https://172.20.20.109:1443/static/app/jquery-ui.js [HTTP/1.1 404 Not Found 0ms]
`
* Little hand section (Advanced Portal Configuration) shouldn't be named like this because it contains access duration and filter engines which aren't only portal related. Could be named Advanced access configuration

**Comment by julsemaan** [comment]
Just reviewed and it seems good up to this point

Should be able to merge once we fix the issues noted this morning

**Comment by julsemaan** [comment]
We'll need to change the doc links to point to /static/doc/... when rebasing onto devel so it grabs the local copy which is now part of the official packaging

**Comment by julsemaan** [comment]
Could require a bit more testing but most likely [FIXED]

I'm having issues with pre-built searches, it seems to be adding inputs twice or making the form believe they are there twice since the requests contain the same parameters twice

Ex:
Search by 'Online Nodes' in the Nodes tab and this is the parameters that are sent on this branch
image

If we compare them with the ones in devel
image

The duplicate parameters create an error in the httpd.admin process for that search:
```
Mar 27 09:38:45 httpd.admin(9429) ERROR: Caught exception in pfappserver::Controller::Node->search "ARRAY(0x7fb68c9ad5c8) is not a supported search operation at /usr/local/pf/html/pfappserver/lib/pfappserver/Base/Model/Search.pm line 50." 
(pfappserver::PacketFence::Controller::Root::end)
```

**Comment by julsemaan** [comment]
[FIXED]
Another bug with pre-built searches, the ones in auditing don't populate the operator field:
image

In the case above I selected a pre-built search for the inverse source

**Comment by julsemaan** [comment]
And another one

If I repeatedly click on pre-built searches in auditing, it makes the report display smaller and smaller since it seems to be rendering a container inside the already existing container on every search

image

**Comment by dwlfrth** [comment]
Anything "big" that could prevent the merge to devel ?
Display bugs and other "minor" things could be fixed while in devel, and we could start testing using the new UI.

**Comment by cgx** [comment]
Let me fix a few more things before merging.

**Comment by julsemaan** [comment]
Continued review up to b3d631d and there is nothing that is merge-blocking

Waiting for confirmation of @cgx that there is nothing more to be added and we'll merge

**Review by julsemaan — CHANGES_REQUESTED** [review]
Waiting for other changes from @cgx before merging

**Comment by whitx** [comment]
Next changes/fixes should be push into devel.

**Comment by fdurand** [comment]
please fix the packaging with debian , i am fed up to fix it all the time

**Comment by louismunro** [comment]
Yes. I thought we were agreed that it's "china shop rules" : you break it you own it.

**Pull request merged**
