### PR TITLE
Database encryption

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Added support for database encryption

# Impacts
database

# NEW Package(s) required
Mariadb >= 10.2
Mariadb-backup >= 10.2

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Support for database encryption (aws and file key)

### CODE REVIEW

**Comment by extrafu** [comment]
👍

**Comment by julsemaan** [comment]
Not sure this should be 8.1 considering the feature freeze will begin Monday

What do @extrafu and @fdurand think?

**Comment by extrafu** [comment]
I think we should consider it since it won't "break" anything unless enabled.

**Comment by julsemaan** [comment]
In that case we need to get it in today so its part of our testing phase in case this causes unexpected side effects even when disabled

**Comment by satkunas** [comment]
`MariaDB-aws-key-management` needed in .spec

**Review by julsemaan — COMMENTED** [review]
code looks fine to me, if we merge this for 8.1, we'll need to test properly the new backups using the MariaDB backup tool

**Comment by julsemaan** [comment]
Let me know when the packages are in devel and we'll merge

**Pull request merged**
