### PR TITLE
feature/netflow-listen-config

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Allow netflow address to be configured

Impacts
=======
pfacct

NEWS file entries
=======================
Enhancements
-------------
* Allow netflow address to be configured

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Review by nqb — CHANGES_REQUESTED** [review]
On Debian 9, `sysctl` is not in `/usr/sbin/sysctl` but in `/sbin/sysctl`

`confignetflow` failed with following output:

`open3: exec of /usr/sbin/sysctl net.netflow.destination=0.0.0.0:2056 failed: No such file or directory at /usr/local/pf/lib/pf/cmd/pf/confignetflow.pm line 27.
`

**Review by nqb — CHANGES_REQUESTED** [review]
`netflow_address` seems to be ignored by `pfacct`.

After I configure `netflow_address` in `pf.conf`, I see following message during startup of `pfacct`:

```
mars 15 15:29:26 pfdeb9dev pfacct[9278]: t=2021-03-15T15:29:26+0000 lvl=info msg="Starting listening to netflow at '127.0.0.1:2056'" pid=9278
```

PacketFence config:
```console
# pfcmd pfconfig get "config::Pf()" | grep -i netflow
                                      'pfacct_netflow' => '2056',
                                         'netflow_on_all_networks' => 'disabled',
                                         'netflow_address' => '0.0.0.0',
```

OS config:
```console
# sysctl -a|grep netflow
[..]
net.netflow.destination = 0.0.0.0:2056
```

**Comment by jrouzierinverse** [comment]
Can you try the following.
```
cd /usr/local/pf/go
make pfacct
mv pfacct ../sbin/
systemctl restart packetfence-pfacct 
```

> `netflow_address` seems to be ignored by `pfacct`.
> 
> After I configure `netflow_address` in `pf.conf`, I see following message during startup of `pfacct`:
> 
> ```
> mars 15 15:29:26 pfdeb9dev pfacct[9278]: t=2021-03-15T15:29:26+0000 lvl=info msg="Starting listening to netflow at '127.0.0.1:2056'" pid=9278
> ```
> 
> PacketFence config:
> 
> ```
> # pfcmd pfconfig get "config::Pf()" | grep -i netflow
>                                       'pfacct_netflow' => '2056',
>                                          'netflow_on_all_networks' => 'disabled',
>                                          'netflow_address' => '0.0.0.0',
> ```
> 
> OS config:
> 
> ```
> # sysctl -a|grep netflow
> [..]
> net.netflow.destination = 0.0.0.0:2056
> ```

**Comment by nqb** [comment]
Thank, it works after I moved binary to correct location.

However, I'm not able to get data into `bandwidth_accounting` table after I did this:
- enable "Netflow on all networks" setting
- configure `netflow_address` as `0.0.0.0`
- allow `udp/2056` to management IP in `iptables.conf:`
```
-A input-management-if -p udp -m udp --dport 2056 -j ACCEPT
```
- restart `packetfence-iptables` and `packetfence-pfacct`
- send NetFlow traffic to management IP address using `scapy` like this:
```
pip3 install --pre scapy[basic]
sudo scapy # mandatory to run with sudo
netflow = NetflowHeader()/NetflowHeaderV5(count=1)/NetflowRecordV5(src="10.10.10.10",dst="8.8.8.8")
pkt3 = Ether()/IP(src="192.168.1.1",dst="172.17.17.10")/UDP(dport=2056)/netflow
pkt3.show2()
sendp(pkt3, iface="virbr2")
```

I expect to see an entry into `bandwidth_accounting` table.

**Comment by jrouzierinverse** [comment]
in pf.conf try setting 
advanced.netflow_on_all_networks = enabled
Then see

**Comment by nqb** [comment]
@jrouzierinverse, I already did it. See my comment above:

> enable "Netflow on all networks" setting

**Comment by jrouzierinverse** [comment]
If there is no ip4log entry then the bandwidth_accounting won't be updated.

**Comment by extrafu** [comment]
@jrouzierinverse Please standardized using /sbin/sysctl

**Comment by jrouzierinverse** [comment]
done

**Comment by nqb** [comment]
I was able to make it working. However, I have to add by hand this `iptables` rule:

`-A input-management-if -p udp -m udp --dport 2056 -j ACCEPT`

to allow NetFlow traffic to reach management interface.

I wonder if we should not add it by default like we have for [fingerbank-collector](https://github.com/inverse-inc/packetfence/blob/505f6e2fda99de085852979c69db8d5710ac7669/conf/iptables.conf.example#L64).

It means that by default, NetFlow traffic is allowed but it will only works if somebody changed `netflow_address` in `pf.conf`.

I will add some sentences in documentation on this part.

**Pull request merged**
