### PR TITLE
Modify index for bandwidth account to improve speed

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Update bandwidth accounting indexing to improve speed of processing cleanup/rotation

# Impacts
pfcron job bandwidth_maintenance and pfacct

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Improved speed of cleanup/rotation of bandwidth accounting record on large tables.

### CODE REVIEW

**Comment by julsemaan** [comment]
Let's hold off for a confirmation that this fixes the issue at the impacted customer and we'll merge after

**Comment by extrafu** [comment]
@jrouzierinverse Look into this one and close if not relevant.

**Comment by extrafu** [comment]
@jrouzierinverse Based on my comment last week, we keep that one as it is still relevant?

**Comment by extrafu** [comment]
Bump, until noon or will move out of 11.2

**Comment by jrouzierinverse** [comment]
I pushed this to #6850

**Pull request closed without merging**
