### PR TITLE
Feature/net snmp perl

### PR DESCRIPTION
**Pull request by mullagain**
Added pf::snmp module to use SNMP.pm from net-snmp instead of Net::SNMP. SNMP.pm has huge performance gains over Net::SNMP. I have created an initial connectRead to replace the method in Switch.pm and get/get_tables methods to make read requests look the same as Net::SNMP.

This is also a Moose based class.

Future support will include set requests, traps, etc.

For review, discussion and merge.

### CODE REVIEW

**Comment by louismunro** [comment]
Thank you for your contribution.
Give us a few days to look at it. It Friday afternoon here and there is a holiday next week.

**Comment by mullagain** [comment]
no worries, just trying to contribute.

**Comment by mullagain** [comment]
I am re-implementing the connectWrite method in this module, but I notice that connectWrite is a wrapper to connectWriteTo. Is the session id still needed or is this something I can remove? I havent been able to find anything using it.

**Comment by mullagain** [comment]
any update?

**Comment by mullagain** [comment]
Any word on this?

**Comment by jrouzierinverse** [comment]
Thank your for contribution 

I will have to discuss with the guys the best way to test this code.

In the mean time could you redo your pull request in this branch https://github.com/inverse-inc/packetfence/tree/feature/net-snmp-perl

**Comment by mullagain** [comment]
Sure thing!

**Comment by jrouzierinverse** [comment]
This was done a different branch

**Pull request closed without merging**
