### PR TITLE
Remove kubernetes and move to github.com/go-kit/log

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description

Remove coredns kubernetes plugin.
Move to use github.com/go-kit/log

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
I recalled to have seen some Golang tests failing randomly on CoreDNS Kubernetes (on maintenance/11.X branch)
My 2 cents:
1. are we sure tests are removed too ?
1. can this PR be backported to maintenance/11.X ?

**Comment by julsemaan** [comment]
Pushing to 12.2 since it's still missing a rebase and the feature freeze is active

**Comment by julsemaan** [comment]
Needs to be rebased

**Comment by jrouzierinverse** [comment]
Done

**Pull request merged**
