### PR TITLE
use nb_NO locale in place of no for Norwegian language

### PR DESCRIPTION
**Pull request by nqb**
# Description
use `nb_NO` locale in place of `no` for Norwegian language because:
- `no` is not a locale
- `no_*` locales doesn't have utf8 related files
- almost all Norwegian locales are alias to `nb_NO` locale

# Impacts
Available locales

# Delete branch after merge
YES

# NEWS file entries
- [X] add news entry

### CODE REVIEW

**Comment by nqb** [comment]
bump

**Review by jrouzierinverse — COMMENTED** [review]
conf/locale/nb_NO/LC_MESSAGES/packetfence.po

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
The rename is bad 
Should be 
conf/locale/no_NO/LC_MESSAGES/packetfence.po
Not
conf/locale/nb_NO/LC_MESSAGES/packetfence.po

Sorry never mind quick on draw

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
nb_NO is not included in the conf/documentation.conf advanced.language

Add /usr/local/pf/conf/locale/nb_NO/LC_MESSAGES/packetfence.po to debian/packetfence.conffiles

**Pull request merged**
