### PR TITLE
fix/5634

### LINKED ISSUE #5634: web admin: Advanced filter (advanced mode) on a connection profile doesn't work as expected
**Describe the bug**
On a connection profile, when you define an Advanced filter using Advanced mode (for advanced users in an advance configuration), your filter is not saved in `profiles.conf`.

**To Reproduce**
1. Create a connection profile called `test2`
2. Switch to Advanced mode to define an Advanced filter
3. Copy following content in field: `last_connection_type == "Wireless-802.11-EAP"`
4. Save

=> Check `profiles.conf`,  `advanced_filter` value is empty.

**Expected behavior**
`advanced_filter` should be `last_connection_type == "Wireless-802.11-EAP"`

**Additional context**
I compared JSON payload sent by frontend when you create connection profile with advanced filter in :
- [basic mode](https://gist.github.com/nqb/d577190a8c3712e9ef056609526ad10f)
- [advanced mode](https://gist.github.com/nqb/acf7eeda56d5bc12104812063f08c56c)

It looks like in advanced mode, conditions are not inserted in the `values` list.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Add the proper top level op to the parse_condition response.

NEWS file entries
=======================

Bug Fixes
-------------
*  Add the proper top level op to the parse_condition response.

Issue
=====
* Fixes #5634

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
can this cause problems with existing filters ?

**Comment by jrouzierinverse** [comment]
No

**Comment by jrouzierinverse** [comment]
bump

**Comment by fdurand** [comment]
The issue has been closed by another commit, do we still kept it open ?

**Comment by extrafu** [comment]
@jrouzierinverse Still relevant?

**Comment by jrouzierinverse** [comment]
This has been fixed by other means.
This can be closed.

**Pull request closed without merging**
