### PR TITLE
add the ability to enable/disable an NBA policy

### LINKED ISSUE #5403: Have the ability to enable/disable a network behavior policy
**Is your feature request related to a problem? Please describe.**
Since we ship all of the default ones enabled by default, it may cause excessive emails from the default security events that go with them.

**Describe the solution you'd like**
We should have a flag to enable/disable them and ship the examples disabled in the future

**Describe alternatives you've considered**
Watching pictures of @lzammit to relax, didn't have much impact on what is above

**Additional context**
One of the pictures I've looked at:
image

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Adds the ability to enable/disable a NBA policy

# Impacts
NBA policies

# NEW Package(s) required
fingerbank-collector-1.3.4

# Issue
fixes #5403

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Added ability to enable/disable a network anomaly detection policy (#5403)

### CODE REVIEW

**Comment by julsemaan** [comment]
We can potentially put this in the maintenance but it will be ignored unless fingerbank-collector-1.3.4 is used (not yet built)

**Comment by extrafu** [comment]
@jrouzierinverse Review and merge if all is fine. Don't forget to update the NEWS file.

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
* In the conf/network_behavior_policies.conf.example can you please add the status parameters to all the sections.
* A script or instructions to add the status parameter to the sections.
* Are there any admin GUI changes needed?
* Are the changes needed in fingerbank done to support the disabled parameter?

**Comment by julsemaan** [comment]
> * In the conf/network_behavior_policies.conf.example can you please add the status parameters to all the sections.

  Done
> * A script or instructions to add the status parameter to the sections.

  No need to do it, the default value handles this transparently in the collector as the default is to set this to enabled which is backward compatible. The admin also handles this transparently.
> * Are there any admin GUI changes needed?

  They are in this PR
> * Are the changes needed in fingerbank done to support the disabled parameter?

  Yes (see new package required)

**Pull request merged**
