### PR TITLE
No autocorrect / uppercasing on login field

### PR DESCRIPTION
**Pull request by dwlfrth**
## Description

We should tell the device (iPad per example) not to autocorrect / uppercasing login field
## Impacts

None... Except if not supported by some browsers
## NEWS file entries

New Features
++++++++++++

Enhancements
++++++++++++
- Device will avoid autocorrect / uppercasing the login field in the captive portal

Bug Fixes
+++++++++
## Delete branch after merge

YES

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by julsemaan** [comment]
Tested with Chrome on Android + IE8.

Android device doesn't autocap + autocorrect and IE8 doesn't break (surprise surprise)

If devel is ready to accept merging then we can go ahead and merge this one

**Comment by cgx** [comment]
Technically, this is not supported in XHTML Transitional. I suggest we move to HTML5.

**Comment by cgx** [comment]
I insist: please change the doctype.

**Comment by dwlfrth** [comment]
What should be the new doctype ?
Will change it in templates/header.html

**Comment by cgx** [comment]
`<!DOCTYPE html>`

**Comment by dwlfrth** [comment]
So we should remove
<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
and replace it by
<!DOCTYPE html>

?

**Comment by cgx** [comment]
Yes!

**Comment by dwlfrth** [comment]
https://github.com/inverse-inc/packetfence/commit/8f645c428ab7b4a1110aa228c2227397852a4488

**Pull request merged**
