### PR TITLE
Feature/ifdesc locationlog

### PR DESCRIPTION
**Pull request by julsemaan**
## TODO: must put the content of db/ifdesc-locationlog.sql in the upgrade script prior to merging

# Description
Adds the interface description in the locationlog and display it where relevant

# Impacts
locationlog so RADIUS, pfsetvlan, portal

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Added interface description to location entries

### CODE REVIEW

**Comment by dwlfrth** [comment]
@jrouzierinverse Please review

**Comment by jrouzierinverse** [comment]
Move the sql to
db/upgrade-X.X.X-X.Y.Z.sql
db/pf-schema-X.Y.Z.sql

**Comment by jrouzierinverse** [comment]
Looks good to me except for the sql

**Comment by julsemaan** [comment]
done

**Comment by lzammit** [comment]
workinje

**Pull request merged**
