### PR TITLE
Bash Script to get latest cd/ci files for public directory

### PR DESCRIPTION
**Pull request by JeGoi**
# Description
Bash script to get latest cd/ci files for public directory
It parse the latest 5 pages from gitlab ci, get the latest public archives file and install it in packetfence/public directory.

# Impacts
Can be used with venom automation

# Dependencies
wget and curl

# Delete branch after merge
YES please

### CODE REVIEW

**Comment by nqb** [comment]
Hello @JeGoi,

1. Could you create a new PR on a branch directly in inverse-inc/packetfence repo in place of your fork ?
2. In this new PR, could you put your script in `ci/lib/test/` directory ?
It makes more sense to put it here because it's much related to provision of VMs using Vagrant

**Comment by nqb** [comment]
The script doesn't work on my side. It looks like `$j` is never incremented.

@JeGoi, according to [GitLab's docs](https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#downloading-the-latest-artifacts), we can get more easily latest artifacts for a branch. On my side, I'm able to get latest artifact available for devel branch using following command:

```
curl -L https://gitlab.com/inverse-inc/packetfence/-/jobs/artifacts/devel/download?job=pages --output /tmp/public.zip
```

I really prefer this approach.

I'm sure that parsing resulting HTML from gitlab.com will not survive to GitLab upgrades.

**Comment by JeGoi** [comment]
Hum, if the j is not incremented, it is because the first job id (published and available) has been found in the page. So no need to search in the rest of the page. It will increment if a job (first or not) is publish and canceled. It will search for the first and latest available.

For the latest artifact, the link will be a problem if the latest artifacts available is not the publish one. You will have the wrong one.
Example, if the pipeline failed at the "sign" step, the latest available artifact will be the "build package" artifacts, which is not the one we are looking for, correct?
I have seen that problem only once when a pipeline has been cancelled.

**Comment by JeGoi** [comment]
Ok no problem, I will move it and publish it in a branch of packfence repository.
Thanks for your time

**Comment by nqb** [comment]
> For the latest artifact, the link will be a problem if the latest artifacts available is not the publish one.

I'm surprised by this behavior, I expected to have the latest artifact available for the job pages. If the latest pipeline has failed, GitLab.com should not provide files to download.

**Comment by JeGoi** [comment]
It was on the third page, at the time, I've script it.
And, it looks that only the first 4 pages have artifacts (Gitlab will not keep it for ever...).

**Comment by nqb** [comment]
Test to cancel "pages" job on: https://gitlab.com/inverse-inc/packetfence/-/pipelines/205188863

**Comment by JeGoi** [comment]
@nqb Ok it is working perfectly with the link you have provided.
I will close the pull request.

**Pull request closed without merging**
