### PR TITLE
Test script for testing the packetfence schema

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Test script for testing the packetfence schema
## Impacts

Testing infrastructure
## NEWS file entries

Enhancements
++++++++++++
- Added additional tests for db schemas
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Review

**Comment by jrouzierinverse** [comment]
Review

**Comment by fdurand** [comment]
The only question i have is what happen if there are no pf-schema-X.Y.Z.sql and upgrade-X.X.X-X.Y.Z.sql like when we release ?

**Comment by jrouzierinverse** [comment]
At the moment it will fail I will fix that tomorrow

**Comment by jrouzierinverse** [comment]
Done

**Comment by jrouzierinverse** [comment]
Please review

**Pull request merged**
