### PR TITLE
fix/sms-pincode-reuse

### LINKED ISSUE #3436: Ran out of pin code
In the code even if the pin code has been used we never make it available again for another registration.
We need to find a way to "expire" the pin code.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Allow activation pin codes to be reused

Impacts
=======
SMS/Email activations.

Issue
=====
Fixes #3436

Delete branch after merge
=========================
NO

NEWS file entries
=================

Bug Fixes
------------

* Allow activation pin codes to be reused (#3436)

### CODE REVIEW

**Comment by extrafu** [comment]
@jrouzierinverse Please revisit this after the discussion we had. The SMS doesn't need to be unique per MAC address.

**Comment by extrafu** [comment]
@jrouzierinverse Bump - what's the status on this?

**Comment by jrouzierinverse** [comment]
Fixed

**Comment by fdurand** [comment]
Just did some tests and i was able to reuse a pin code.

**Pull request merged**
