### PR TITLE
Syslog config for pfsso and etcd

### LINKED ISSUE #3512: pfsso and etcd : logging to /var/log in place of /usr/local/pf/logs
Same issue as #3423 but for `pfsso` and `etcd`.

No matching in `lib/pf/constants/syslog.pm`

### PR DESCRIPTION
**Pull request by nqb**
# Description
Send `pfsso` and `etcd` logs in `/usr/local/pf/logs` in place of `/var/log`

# Impacts
Syslog configuration

# Issue
fixes #3512 

# Delete branch after merge
YES

### CODE REVIEW

**Review by julsemaan — APPROVED** [review]

**Comment by nqb** [comment]
@julsemaan : do you think we can cherry-pick in maintenance/8.1 ?

**Comment by julsemaan** [comment]
@nqb 

Sure. Lets get another pair of eyes to confirm those changes, then lets merge and cherry-pick

**Comment by nqb** [comment]
Ok. I think we could also cherry-pick #3433

**Comment by nqb** [comment]
@jrouzierinverse, @fdurand : could you review quickly ? I would like to cherry-pick to fix a current setup.

**Review by fdurand — APPROVED** [review]

**Pull request merged**
