### PR TITLE
fix/config-switch-roles

### LINKED ISSUE #6321: switches: slow display in frontend
**Describe the bug**
On a 10.3 with 92 switch groups and ~400 switches, if I try to browse switches or switchs groups, I have to wait ~10 seconds between each page.

Setup has 37 roles.

**To Reproduce**
1. Install a fresh 10.3
2. Install a switches.conf with a lot of entries
3. Try to display switch or switch groups

=> You will have to wait between each page

**Expected behavior**
Faster display.

**Additional context**
In the web browser, I see duplicate requests to API to get switch or switch groups information (see screenshot below):
switches

I don't know if it's expected.

JSON payload returned by API only contains 25 first switches and not all the switches.

When I used `pidstat 1`, I see that `pfperl-api` processes used 100% of all CPUs available on the machine to answer requests.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Improve the speed of the switch configuration.

NEWS file entries
=======================
Enhancements
-------------
* Improve the speed of retrieving switches (#6321)

Issue
=====
fixes #6321

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Review by nqb — CHANGES_REQUESTED** [review]
Rendering of switches and switch groups is really improved.

However, I noticed following issues during my "functional" tests:

### Create/Update/Delete

When you create, update or delete a switch, it seems that it takes more time than previously.

### Switch groups members

Randomly, members of switch groups doesn't appear in "Members" tab of switch groups.
If I look at web browser console, API sends a correct response but it could take more than 10 seconds depending of number of members.

If I close switch group displayed and open it again: members appear directly.

It looks like `/api/v1/config/switch_group/SWITCH_GROUP_NAME/members` API call returned all informations related to members. I don't think it's necessary because we only display: ID, description and type on Members tab. On top of that, when you click on a member, frontend resends an API call for this specific member to get datas.

**Comment by nqb** [comment]
@jrouzierinverse, could you take a look at my comment and let me know what you want to do ?

Thanks

**Comment by nqb** [comment]
I will retest this PR ASAP.

**Comment by julsemaan** [comment]
The code looks good but we need @nqb's blessing on whether or not this works

**Comment by nqb** [comment]
Hello,

Both issues mentioned seem fixed. Regarding CRUD issue, @jrouzierinverse told me because of the changes to how the role mapping is handled now it is now faster on listing but it is slower for the individual.

However, I still have an issue. I'm not able to have Vlan Mapping when I browse a switch on GUI. It works when I browse a switch group but not for an individual switch.

I look at API calls and I see `VlanMapping` in JSON response when calling `/api/v1/config/switch/X.X.X.X`

**Comment by jrouzierinverse** [comment]
> Hello,
> 
> Both issues mentioned seem fixed. Regarding CRUD issue, @jrouzierinverse told me because of the changes to how the role mapping is handled now it is now faster on listing but it is slower for the individual.
> 
> However, I still have an issue. I'm not able to have Vlan Mapping when I browse a switch on GUI. It works when I browse a switch group but not for an individual switch.
> 
> I look at API calls and I see `VlanMapping` in JSON response when calling `/api/v1/config/switch/X.X.X.X`

The VlanMapping issue also happens in devel @satkunas is looking at it now.

**Comment by nqb** [comment]
Ok so I'm merging.

**Pull request merged**
