### PR TITLE
Feature/security events upgrade

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Upgrade script for security event renaming in #3969 

# Impacts
Upgrade of violations

# Code / PR Dependencies
PR #3969

### CODE REVIEW

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
Rename all directories in the html/captive-portal/profile-templates/<profile>/violations to html/captive-portal/profile-templates/<profile>/security_events
Rename the file logs/violation.log to logs/security_event.log
Rename search and replace api calls in conf/pfdetect.conf

**Comment by julsemaan** [comment]
Adjustments performed

**Comment by extrafu** [comment]
@jrouzierinverse Let's merge if it's ok.

**Comment by jrouzierinverse** [comment]
rebase

**Comment by julsemaan** [comment]
rebase, ready for review+merge

**Comment by extrafu** [comment]
rebase

**Comment by julsemaan** [comment]
Its already rebased, lets merge this baby

**Pull request merged**
