### PR TITLE
Renamed FR template files so they can be used by the code

### PR DESCRIPTION
**Pull request by dwlfrth**
## Description

FR violation template files were not usable by the code since it was trying to load fr_FR instead of FR
## Impacts

None... it was not working ...
## Delete branch after merge

YES

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me please

**Comment by julsemaan** [comment]
If you use fr_CA then I guess these templates don't work, right ?

**Comment by cgx** [comment]
The problem is in `pf::Portal::Session->getLanguages` where we should include the 2-character languages from the profile's locales. I'll fix it.

**Comment by julsemaan** [comment]
Good idea because I don't think that it should have been fr_FR anyway. 
French people would have felt too important with that.

**Comment by dwlfrth** [comment]
:+1: What @cgx said
:+1: :+1: What @julsemaan said

**Pull request merged**
