### PR TITLE
fix/7848

### LINKED ISSUE #7848: suspected memory leak in pfconnector service packetfence 12.2
Hello,

I have a cluster of 3 server with packetfence 12.2.

We noticed the pfconnector service keep increasing ram usage over time costantly on all 3 servers. I have standard load balancing of services in the cluster, so web interface on the first one, radius etc on the others. If I restart all pf services the ram usage is reset almost to zero for the service pfconnector, and then it starts again to increase.

I've been searching online for this pfconnector service and ram usage, but found nothing. Is anyone familiar with this behavior?

Here's the top of the 3 servers:
SERVER1:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
4002511 root      20   0 6101832   3.8g   7700 S   3.0  24.1 1994:47 /usr/local/pf/sbin/pfconnector server --host 100.64.0.1,127.0.0.1 --port 22226 --reverse

uptime 11:56:49 up 78 days, 21:00
(pf restarted 24 days ago)

SERVER 2:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2928 root      20   0   15.6g  11.3g   7080 S   2.9  72.4 11412:50 /usr/local/pf/sbin/pfconnector server --host 100.64.0.1,127.0.0.1 --port 22226 --reverse

uptime 11:03:38 up 78 days

SERVER 3:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2727 root      20   0   15.4g  10.7g   5680 S   0.7  68.7 11476:19 /usr/local/pf/sbin/pfconnector server --host 100.64.0.1,127.0.0.1 --port 22226 --reverse

uptime   10:09:26 up 78 days

Regards,
Massimiliano

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Reuse the websocket buffer to reduce memory usage.

# Issue
fixes #7848

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Reuse the websocket buffer to reduce memory usage.

### CODE REVIEW

**Comment by extrafu** [comment]
@jrouzierinverse Should this be contributed to Chisel itself or the code is vertical to us?

**Comment by jrouzierinverse** [comment]
This could be added upstream.

**Comment by extrafu** [comment]
@jrouzierinverse I suggest you create a PR upstream so we don't have to maintain this fix ourselves

**Comment by jrouzierinverse** [comment]
done

**Pull request merged**
