### PR TITLE
Feature/golang 1.17

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description

Upgrade to golang 1.17

# NEWS file entries

## Enhancements
* Upgrade to golang 1.17.1

### CODE REVIEW

**Comment by nqb** [comment]
I was able to build correctly packages for EL8 and Debian 11 using Golang 1.17

**Comment by jrouzierinverse** [comment]
Should we merge this now or wait?

**Comment by nqb** [comment]
Could you rebase on devel in order to have latest fixes added by #6566 ? Them I will run full tests on it.

**Comment by jrouzierinverse** [comment]
done

**Comment by nqb** [comment]
Pipeline is running: https://gitlab.com/inverse-inc/packetfence/-/pipelines/366603741

**Comment by nqb** [comment]
I would like #6581 to be fixed and #6574 to be merged (when ready) before testing again.

**Comment by julsemaan** [comment]
I'm pushing this to 11.2 given the short window we have for releasing 11.1

Optimally, my opinion would be to merge this in devel right when 11.1 is released which will give us plenty of time to deal with the side effects if there are any

**Comment by jrouzierinverse** [comment]
Bump!

**Comment by nqb** [comment]
@jrouzierinverse, could you rebase on `devel `and I will re-run tests.

**Comment by nqb** [comment]
https://gitlab.com/inverse-inc/packetfence/-/pipelines/400256028

**Comment by nqb** [comment]
Golang unit tests failed:

```
--- FAIL: TestMetricsAvailableAfterReload (0.31s)
    reload_test.go:239: Could not scrap one of expected stats : Get "http://127.0.0.1:53186/metrics": dial tcp 127.0.0.1:53186: connect: connection refused
    reload_test.go:253: Could not scrap one of expected stats : Get "http://127.0.0.1:53186/metrics": dial tcp 127.0.0.1:53186: connect: connection refused
FAIL
```
but I think this is the usual tests that failed.

Unless you have a fix for that, we can merge.

**Pull request merged**
