### PR TITLE
fix/5729

### LINKED ISSUE #5729: Should be possible to set multiples ca cert in radius ssl
**Describe the bug**

When i have to add multiples ca certificates in the Certificate Authority section and when i save only one of them is saved.

Freeradius support multiples CA in the same file, so PacketFence should support that.

**To Reproduce**
1. Go to 'https://mgmt_ip:1443/admin/alt#/configuration/certificate/radius'
2. Click on 'Edit'
3. Fill Certificate Authority with:

```
-----BEGIN CERTIFICATE-----
MIIEBjCCAu6gAwIBAgIQTQQhGG1woYtCsMzfN9pRyDANBgkqhkiG9w0BAQUFADBe
MQswCQYDVQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1
dGhvcml0eTElMCMGA1UEAxMcQWxjYXRlbCBFbnRlcnByaXNlIFNvbHV0aW9uczAg
Fw0wNTA5MjgxMDAzNDJaGA8yMDU1MDkyODEwMTEwOFowXjELMAkGA1UEBhMCRlIx
EDAOBgNVBAoTB0FsY2F0ZWwxFjAUBgNVBAsTDVBLSSBBdXRob3JpdHkxJTAjBgNV
BAMTHEFsY2F0ZWwgRW50ZXJwcmlzZSBTb2x1dGlvbnMwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCoW+RtCCV4bVFyajRkHX6mci2W/vkFqYy0OZOFKO86
IbSro6iXXiY8CnBGC6YUPg5OsBqwQcKFrpX7gxd36yDGjn7oeIWHe6SYj+LJN4dZ
wrout2x6P3ggpYCIxSJn61OqZVblt8UFcd23iL4IToHgxzPURh+KSHwM4vmfL89P
o7GGqCwpdzP/SAMo7MbFsLS1YO1OEJp9x/LRJY76A0Kga7ZQAoyM492ylmx2AbOE
nIypL/o8RYH8BHFgCfeCwdwsDgpH3FAq4icLfi4ww+ErnBHElkpHQIZp72sBDisw
g3MCvyVrgfh7mxhzJcYNKsUS3x5mg9GinvOluyo8TpCNAgMBAAGjgb0wgbowDgYD
VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLcfTkW1AN3z
x5qXYgQI0ZpMukoNMBAGCSsGAQQBgjcVAQQDAgEAMGYGA1UdIARfMF0wWwYJKwwC
h25JAAABME4wTAYIKwYBBQUHAgIwQB4+AFAAQwAgAEEAbABjAGEAdABlAGwAIABF
AG4AdABlAHIAcAByAGkAcwBlACAAUwBvAGwAdQB0AGkAbwBuAHMwDQYJKoZIhvcN
AQEFBQADggEBAA3G62EdwvjmM+s/1wKgWA18v70MJ5b0JMJgpOBNITG1ocXzdDkb
HCLPO/tJIbdeneaPVbFHunOjREVjEaHaKzPyO/jFlYsp+Y0YYpgmAtbcf9CRuZ1x
uPym3mj0ReLP8QBzwHKB2KmNZz/7fdDnuy3YFFl6QIkc79+2GbNXLnidGnm0dtfz
jGLmajyfkz43ENlY+kY9Uv14z2l4vIltSjRqdtBUyw7zbJYeEu9KTaL/YEXG9j3x
FDjgI7nuv/vWKhKY/lMkb7A5RjMmLYULdqp6sw/NeIcC1qA9Fmk8VFgNENTmeGR7
n7nc1SCVb6Q6IAQgW6UsRn/3E7CUFII4/FQ=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIClDCCAf2gAwIBAgIKERuoVQAAAAAAGzANBgkqhkiG9w0BAQUFADBSMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTEZMBcGA1UEAxMQQWxjYXRlbCBJUCBUb3VjaDAeFw0wNTA5MjkxMjA5MzNaFw0y
NTA5MjgwODIyMDRaMEgxCzAJBgNVBAYTAkZSMRAwDgYDVQQKEwdBbGNhdGVsMRYw
FAYDVQQLEw1QS0kgQXV0aG9yaXR5MQ8wDQYDVQQDEwZBSVBUIDEwgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBAMZ5vAH4xHgluR/Y3b0Ypw/RzVEqiQ1Aa2KLRkuQ
gfsphy2TgrViOzYClARWyKbrbOETh9Z+0wSfGNuepnP9JQmFzVB3bAmbuk3Xh9fs
tQCxw9UGsZ7/cd7xLvePLC/eKMwwiUU3XRBeCeGQInXro8bdKsUFYiqjrOHnEKSt
YXCLAgMBAAGjezB5MB0GA1UdDgQWBBR4ekAGoXlWhbwFm9Wa07AWTxbL4jAfBgNV
HSMEGDAWgBRWkggS7kPUr7UgEcCSqOBiwR5/fDAZBgkrBgEEAYI3FAIEDB4KAFMA
dQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjANBgkqhkiG9w0B
AQUFAAOBgQAXNh2LpE0aqH4pm++MVtHTN5awGv+uWNF7CyBNL19btKedFLo0gKxw
XjsDiLYW1edXggGbYrRyvvRvNZ4kF0f6TwvxFeuhrTSCO9T6YOkOZLlKsG64ATme
m3fkldxYd/pxytTcrJBOzo8Mpxo/gvKlTWuSdcAU9cUY4wJZTugcGg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIClDCCAf2gAwIBAgIKER8bgwAAAAAAHDANBgkqhkiG9w0BAQUFADBSMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTEZMBcGA1UEAxMQQWxjYXRlbCBJUCBUb3VjaDAeFw0wNTA5MjkxMjEzMTlaFw0y
NTA5MjgwODIyMDRaMEgxCzAJBgNVBAYTAkZSMRAwDgYDVQQKEwdBbGNhdGVsMRYw
FAYDVQQLEw1QS0kgQXV0aG9yaXR5MQ8wDQYDVQQDEwZBSVBUIDIwgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBAMBkY3eYycaTCceKKVgSG21OPW0FN8CCSEfXv+2X
UY6u08K8ToBNIKimuwDsKUxyzRF0GyujpUX8Q+Y8gpX/OFrzblKvf8TGsePfcUFA
8va4SsXoiHNWU9hDVldDblw+AhpdQwcrzCIZqOC0Avb3Z8T4CmWngLQvd16AvzTS
whFlAgMBAAGjezB5MB0GA1UdDgQWBBSIPswtkCnJ/hT80zCmVQZYaD+oQTAfBgNV
HSMEGDAWgBRWkggS7kPUr7UgEcCSqOBiwR5/fDAZBgkrBgEEAYI3FAIEDB4KAFMA
dQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjANBgkqhkiG9w0B
AQUFAAOBgQCOQSFt3R9Osgw6q30wxEStlKDrYuGGINmQ16AaOIKbRHsGxm8lnUG1
l95EDlnuNbkdu4IJnFsrFy/CSh0W65ODoWtFUyN9jLWrUHWtEehhI5PRgRXcu4rK
3Awysm9RiDQnoDKQcBdhxAO1YsJSh1kvtVUhXweJXMpoZgI7Ieo6Mg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIClDCCAf2gAwIBAgIKER8bogAAAAAAHTANBgkqhkiG9w0BAQUFADBSMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTEZMBcGA1UEAxMQQWxjYXRlbCBJUCBUb3VjaDAeFw0wNTA5MjkxMjEzMTlaFw0y
NTA5MjgwODIyMDRaMEgxCzAJBgNVBAYTAkZSMRAwDgYDVQQKEwdBbGNhdGVsMRYw
FAYDVQQLEw1QS0kgQXV0aG9yaXR5MQ8wDQYDVQQDEwZBSVBUIDMwgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBAPdDpy2qPzkDeE6s9Sgab+9s/4KX11wr7i87OV16
W0kAHDmwtqsXqnZvCsJEa3CaFFEiQhA2J2IzAm7XoiA/g89HvzI30J0l9pfLpzh+
QUhmqdArD+oPLuZRaTZr6WHOB+mW4zC6J6c0yL1T1cEgtcpfJumb2RMb5UTP3wa3
WpuHAgMBAAGjezB5MB0GA1UdDgQWBBSS1yZ9/T8AuU2zGYkKjQNg7azdCjAfBgNV
HSMEGDAWgBRWkggS7kPUr7UgEcCSqOBiwR5/fDAZBgkrBgEEAYI3FAIEDB4KAFMA
dQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjANBgkqhkiG9w0B
AQUFAAOBgQB2h3dbQSgFjqbOL2GFlsOw2Qx+bItAvDYz1YRLwn9aCGGZ1kmkiro/
1IGeITQW/qExz/GP6id7QRqd2T3X95CnOazn3hz9+jHHEgTUgW0qvNRJBE9GkCzZ
PZZ1O4V+OrljFMBp0X+7OUK8q6jQEVm+Tf4g8F9djbKYVMMsdUJLtA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIClDCCAf2gAwIBAgIKER8bsQAAAAAAHjANBgkqhkiG9w0BAQUFADBSMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTEZMBcGA1UEAxMQQWxjYXRlbCBJUCBUb3VjaDAeFw0wNTA5MjkxMjEzMTlaFw0y
NTA5MjgwODIyMDRaMEgxCzAJBgNVBAYTAkZSMRAwDgYDVQQKEwdBbGNhdGVsMRYw
FAYDVQQLEw1QS0kgQXV0aG9yaXR5MQ8wDQYDVQQDEwZBSVBUIDQwgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBAL9Sow+GjUG4FIpwK+8P14vzxrc5CqDtVa/9rk+s
DwHVJ2jqqA9xOGulnj3JzJO9206eNjF1tumbbisvAhhq+/CfpRG8SZYz4Xsndgp8
KVnYEq3grFF2bRRFb6eWHQoeYunuTbZEazInzKsk4ZgK/lb1mSdxF3h602cPrhM3
0HSVAgMBAAGjezB5MB0GA1UdDgQWBBTySoW6ZJhoRSG9OEu7mIg1UGVhcTAfBgNV
HSMEGDAWgBRWkggS7kPUr7UgEcCSqOBiwR5/fDAZBgkrBgEEAYI3FAIEDB4KAFMA
dQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjANBgkqhkiG9w0B
AQUFAAOBgQBmzPYtvXIuPpo47JgxAH9b9ygIC2EXjHas8mcyMg9ssFhZwQYw3/mD
PJwGjBzw+aDbsmgw9ofLU3kY9wDF0HhpZjdWKE0A7wHG6akipmLryk1DncpRiEhl
M4ZI0R/bujArS0ikUSR/66QVFkUdTdfd70E7vwgNBzSWoiRYkyJAng==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDtTCCAp2gAwIBAgIKE5R/5gAAAAAABDANBgkqhkiG9w0BAQUFADBeMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTElMCMGA1UEAxMcQWxjYXRlbCBFbnRlcnByaXNlIFNvbHV0aW9uczAeFw0xMDAx
MjgxMTIwMzRaFw00MDAxMjgxMTMwMzRaMFUxCzAJBgNVBAYTAkZSMRcwFQYDVQQK
Ew5BbGNhdGVsLUx1Y2VudDEWMBQGA1UECxMNUEtJIEF1dGhvcml0eTEVMBMGA1UE
AxMMV2lyZWQgUGhvbmVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
5avHo+3mFoZg8dC1OhAVv+JbUfLbggIgJJoxKfD4Fvkl/cu4s2Q5OYQ0EAt75Mr9
M5Z/Zg7n3JOAXbAb2R4stgx24tFQEL6ZxA2gF1A7spgVTz4DwbCiGA40y2Pcb6Gs
ZSzuan5CZTSp22ML4u1nXvH+Nw19dHqtN7ogheV9bCo2ul0n8oJMJTLMmGCKBTsY
xLdgWWWZtST15M6Lr59sxiqUDa011YrRMDdstnJ3lb2KHTZeEvXD5wVPtOF3IQ6W
m0VtypNuG/s5Mgv5jgqh75VW1G+cWoDOBq+bL198RTYvT0jjqtkHCU24CoWy6prZ
u+WoK7Xh1UvonnkwpnELKwIDAQABo34wfDALBgNVHQ8EBAMCAcYwHQYDVR0OBBYE
FNIFozjmVmeshTykIVxkz9JJ28wCMB8GA1UdIwQYMBaAFLcfTkW1AN3zx5qXYgQI
0ZpMukoNMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwDQYJKoZIhvcNAQEFBQADggEBABDcSB0muQs0mglMkL4EKG6OdjeFsmXG
WDzvkn3fleAJmqXku+OMlBoBYwxWZ+9gsiyp96XntODrCyfkfvbaZaMNQBWBvSyu
T6+XAAJlRMZiIEsb6OMjpQZcIotrkAqc7xBUV4GDJ6SvNgnW3YY1jQV4Xs8FQDKE
db+uQUUL9GwIgrS0gkcHd/g6ofs+eWHAss9FYh7+lUtSJatN+OiurfjhqOaaZ/64
XT8khpTwXBlGVEtAfjbnd+xFx9CjaOzexPVKFMz7iLXVkrYVjHQsdOnSacx7rdkv
Q60IIaAuN/bs6vwfWeuzo6ATcIFdiCcphZvI3eXP95W4PLLawKXgls0=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDjzCCAnegAwIBAgIKYaLyagAAAAAABDANBgkqhkiG9w0BAQUFADBeMQswCQYD
VQQGEwJGUjEQMA4GA1UEChMHQWxjYXRlbDEWMBQGA1UECxMNUEtJIEF1dGhvcml0
eTElMCMGA1UEAxMcQWxjYXRlbCBFbnRlcnByaXNlIFNvbHV0aW9uczAeFw0wNTA5
MjgxMDAyNDdaFw0yNTA5MjgwODIyMDRaMFIxCzAJBgNVBAYTAkZSMRAwDgYDVQQK
EwdBbGNhdGVsMRYwFAYDVQQLEw1QS0kgQXV0aG9yaXR5MRkwFwYDVQQDExBBbGNh
dGVsIElQIFRvdWNoMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCQ0c9SKpu3
IL1MiCvL2C0fPUMrY6xXy6gBnFhm7GJpZirZJtIAxdylkZfCzyu7UFUcq71Yo1/+
9BAwX/KsPtH7iJpv/4dKe93Yt7e5vs1E2lMcokHyEhnE3rb/I1WCH/rwFMkCydN1
n+RaTrzu4gJaJwLmnfruud3cqkvpBhJqiQIDAQABo4HeMIHbMA8GA1UdEwEB/wQF
MAMBAf8wHQYDVR0OBBYEFFaSCBLuQ9SvtSARwJKo4GLBHn98MAsGA1UdDwQEAwIB
hjAQBgkrBgEEAYI3FQEEAwIBADBOBgNVHSAERzBFMEMGCSsMAoduSQABATA2MDQG
CCsGAQUFBwICMCgeJgBQAEMAIABBAGwAYwBhAHQAZQBsACAASQBQACAAVABvAHUA
YwBoMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMB8GA1UdIwQYMBaAFLcfTkW1
AN3zx5qXYgQI0ZpMukoNMA0GCSqGSIb3DQEBBQUAA4IBAQCKcjNba0Q5n/6bWm/M
B8Qv4LbFFuEMffkiSA5nIYDLLDQbaFPYCZIs5ldWCFR2QtTWAAb2saL8NVUxAC0+
TZx+B8KrgbKNd3CmwoANJ8Y3UqHdXTJBJr0D9j4A55Tugv52mF+pyXAflHrwVNE3
7XcmdXbdT+3JQN7rBAdDCkpPauKjYMN1C8iaG4m8GZ9xlfdopOefBrNMjo41kcPK
uRAMEygoJFDJtwykoi1GvhWgfZde3mrwVWIQ+6JjF0lXFjKZ6mhdEC2nuNn3klKA
9TiAvBWksD9bkNSpe0PcLvtEGwW6w1ifrxKk1rV6O3foYxzizXNMVVHDO65HLF17
kUkP
-----END CERTIFICATE-----
```

4. Save

5. Only one certificate is saved

**Screenshots**

image

**Expected behavior**

Freeradius support to have multiple certificate in the same file in order todo eap-tls with multiples CA.
We should be able to save all of them and see in the admin gui all the certificates.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Unable to set multiples ca cert in radius ssl.

NEWS file entries
=======================
Bug Fixes
-------------
* Allow to set multiples ca certificates.

Issue
=====
fixes #5729

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by lyubomirtraykov** [comment]
The Web GUI is not displaying CA correctly:
Screen Shot 2020-08-18 at 8 24 10

**Comment by jrouzierinverse** [comment]
You must compile the javascript fixes to test this properly
```bash
make -C /usr/local/pf/html/pfappserver/root/static.alt/ dev
````

**Comment by nqb** [comment]
Hi @jrouzierinverse, 

Is this PR ready ?

**Comment by jrouzierinverse** [comment]
yes

**Review by nqb — CHANGES_REQUESTED** [review]
It work on my side if I used certificates provided by @fdurand on #5729: all certificates are correctly displayed in web admin after I added all of them in Certificate Authority field.

However, we introduced a new frontend logic in place of reusing what we have for intermediate CA certificates: we can already add several certificates using "Add certficate" button.

@cgx, do you thinks it's possible to reuse same logic ?

Also, it will make more sense to rename "Certificate Authority" field by "Certification Authority certificate(s)" field.

**Comment by fdurand** [comment]
For now i think it's enough since it fix the issue.
There is some work to do in this section to integrate the packetfence pki ca certificate, so we will be able to change this section after.

**Pull request merged**
