### PR TITLE
feature/remove-tc-service

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Remove the Traffic Shaping

# Impacts
Traffic Shaping

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Remove Traffic Shaping

### CODE REVIEW

**Review by satkunas — APPROVED** [review]
More UI changes pushed

**Comment by fdurand** [comment]
There is other code to remove https://github.com/inverse-inc/packetfence/pull/2803/files
ipset.pm per example contain code related to the traffic shapping.

**Comment by fdurand** [comment]
Still remain code in ipset.pm

**Comment by jrouzierinverse** [comment]
Done

**Pull request merged**
