### PR TITLE
Maintain Captive Portal Interface Seperation

### PR DESCRIPTION
**Pull request by tallwireless**
# Description
One of the problems with the captive portal is that on a html redirect to the captive portal the hostname of the management interface is used. This is fine if the user subnet has access to the management interface, but poses a problem when it does not. An use case for this is our guest network resides in a L3VPN, and doesn't have access to the management interface, but shares the same DNS server with the rest of campus preventing the use of different DNS entries.

This enhancement adds a hostname variable to the interface sections of the pf.conf file. When a request comes in to httpd.portal the pf::web::dispatcher does a lookup of the incoming server IP address, and uses the hostname variable for the $captive_portal_domain if it exists. This in turn returns the correct hostname for isolated networks.

# Impacts
This code makes changes to the pf::web::dispatcher::html_redirect subroutine adding a lookup to code to redirect the incoming request to the appropriate interface.

# Code / PR Dependencies
See diff.

# NEW Package(s) required
None.

# Issue
None.

# Delete branch after merge
YES

# NEWS file entries
(REQUIRED, but may be optional...)
* Ability to redirect captive portals to incoming interface

### CODE REVIEW

**Comment by dwlfrth** [comment]
That PR seems bogus

**Comment by louismunro** [comment]
Perhaps not bogus, but certainly misguided as far as merging and rebasing.
As it is, it's not acceptable.

**Comment by dwlfrth** [comment]
What I meant ;)

**Comment by julsemaan** [comment]
And I hate to break your dream, but the dispatcher was rewritten in go so this change is not relevant for devel

Also, the hostname would make more sense in the networks configuration more than the interface configuration

Nonetheless, this need to be ported to the Golang code so it can reach devel (7+)

**Comment by julsemaan** [comment]
@louismunro, @dwlfrth 

This seems to have been based off maintenance/6.5 instead of devel which explains the weird merge attempt

**Comment by tallwireless** [comment]
I'm currently in the process of deploying 6.5.1 in production, and ran into this problem. I wasn't sure if there was going to be another maintenance release of 6.5 before 7 was deployed.

I'll take a pull of the devel branch, and look into merging it into the dispatcher written in go.

As for the placement of the hostname, tying it with the interface seemed appropriate. Unless there have been changes to the networks.conf file and what is contained there, networks.conf was for the list of routed subnets, not the interfaces.

**Comment by dwlfrth** [comment]
What are we doing with this ?
@tallwireless, do you want to submit a reworked PR ?

**Comment by dwlfrth** [comment]
@tallwireless, can you let us know what you think about the comments. If we don't get any reply, we gonna go ahead and close

**Comment by julsemaan** [comment]
no love given to the PR based on our comments, will close this, @tallwireless feel free to reopen if you want to adjust it

**Pull request closed without merging**
