### PR TITLE
Make Sourcefire great again.

### LINKED ISSUE #2018: Sourcefire module is no longer compatible with pf::api
The current code for the pf::api expects events to be a hash, containing an event element that points to a hashref of type and id.

The old Sourcefire module just sends a list with the time, sid, and ip.

### PR DESCRIPTION
**Pull request by louismunro**
# Description
Fixes the Sourcefire client to be compatible with the current pf::api.

# Impacts
The current pf::api expects a hash of events.
This fixes the Sourcefire module to comply with the API.

# Issue
fixes #2018

# Delete branch after merge
YES 

# NEWS file entries

## Bug Fixes
* Restores pf::api compatibility to Sourcefire module (#2048)

### CODE REVIEW

**Comment by julsemaan** [comment]
Looks good

As discussed, just not sure if the SOAP call will serialise the attributes correctly but that should be it

**Review by julsemaan — COMMENTED** [review]
Looks good

As discussed, just not sure if the SOAP call will serialise the attributes correctly but that should be it

**Comment by jrouzierinverse** [comment]
Quick test shows that the soap api deserialize everything correctly

**Comment by louismunro** [comment]
Cool.
I knew XML would not let a feature go unimplemented...

**Pull request merged**
