### PR TITLE
fix for #1493 pfcmd vlan deauth exit code fix

### PR DESCRIPTION
**Pull request by obilodeau**
A modified version of a patch provided by Moshe_Levi in http://packetfence.org/bugs/view.php?id=1493

Ready for testing in integration and review.

Aiming for devel since this isn't a big deal and somewhat intrusive.

### CODE REVIEW

**Comment by obilodeau** [comment]
Don't forget to move the NEWS entry from stable to devel if merged in devel!

**Comment by obilodeau** [comment]
passing integration

**Comment by dwlfrth** [comment]
seems fair enough... quite simple

**Comment by fgaudreault** [comment]
I guess we can merge in devel...

**Pull request merged**
