### PR TITLE
Removes the deprecated NTLM background job fields and components

### LINKED ISSUE #6552: Deprecate backend code related to NTLM cache background job
With merge of #6340, we decided to deprecate NTLM cache background job.

Backend code related to that feature need to be removed.

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Removes the deprecated NTLM background job fields and components

# Impacts
NTLM cache

# Issue
fixes #6552 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by julsemaan** [comment]
I tested the NTLM cache on this branch and it works correctly like in 11.0 (cache on connection only)

**Comment by nqb** [comment]
@julsemaan, you said on https://github.com/inverse-inc/packetfence/issues/6552#issuecomment-906481607 that some fields need to be removed from `./_components/index.js`, is it still necessary ?

**Comment by julsemaan** [comment]
Looks like @satkunas did already remove them when I checked

**Comment by nqb** [comment]
Tested, work as expected.

**Pull request merged**
