### PR TITLE
feature/template_switch_getVoipVsa

### LINKED ISSUE #5059: Switch template module is missing getVoipVsa
**Is your feature request related to a problem? Please describe.**
We need to be able to set the RADIUS attributes used when authorizing a VoIP device using a templated switch. Right now, this is missing.

**Describe the solution you'd like**
Have getVoipVsa implemented with a confidurable scope in the template

**Describe alternatives you've considered**
Going on OTBM but its offline now

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Add supports for getVoipVsa for pf::Switch::Template

Issue
=====
fixes #5059

Delete branch after merge
=========================
NO

NEWS file entries
=======================
Enhancements
-------------
* Allow to configure VOIP Radius atrributes

Checklist
=========
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
Documentation and example template needs to be updated

**Comment by jrouzierinverse** [comment]
Done

**Comment by julsemaan** [comment]
Missing news entry for post-merge

**Comment by jrouzierinverse** [comment]
done

**Pull request merged**
