### PR TITLE
Various fixes for PKI

### LINKED ISSUE #6370: pfpki: p12 mail from is ignored
**Describe the bug**
If you create a template with a custom "p12 mail from", this field is ignored and mails are sent with a `From` field based on `alerting.fromaddr`

**Expected behavior**
Mail received has `From` header equals to "p12 mail from" value of certificate template.

### LINKED ISSUE #6671: pfpki: clarify behavior when certificates are provided using SCEP
**Describe the bug**
In order to get a certificate using SCEP through `pfpki`, a node need to generate a CSR which contain informations to generate its own certificate. For example:

https://github.com/inverse-inc/packetfence/blob/7e16d54c250373b9ec65248066a996976fd97d7a/t/venom/nodes/wired_dot1x_eap_tls/run_sscep_on_node01.yml#L23-L41

At the moment (v11.0.0) , I noticed that only CN is taken into account. All others DN parameters are ignored.

I would like to document what is the expected behavior.
See also https://github.com/inverse-inc/packetfence/issues/6248

### LINKED ISSUE #6713: pfpki: editing PKI templates is possible but not taken into account
**Describe the bug**
On PF v11.1.1, if you edit a PKI template to change settings, frontend lets you perform your operation. After you click on "Save", some fields become empty and values are not updated in DB.

**To Reproduce**
1. Create a CA and a PKI template with a Country and a Locality values
2. Change "Country" setting in your PKI template
3. Save

=> Country and Locality fields became empty

**Expected behavior**
I'm not sure what should be the expected behavior. I remembered it was not possible to edit PKI templates in the past.

### LINKED ISSUE #6749: web admin: wrong display of fields for PKI templates
**Describe the bug**
When you create a PKI template with Organisation, Organisation unit, State and Country, fields are saved in DB.
If you go back to your PKI template to enable SCEP setting and save. Then Organisation, Organisation unit, State and Country informations disappear when you switch to "General" tab.

If you close and get back to your template, you got same behavior. You need to refresh your web browser to get informations.

When I enabled SCEP setting on my PKI template, PATCH request sent by frontend doesn't contain Organisation, Organisation unit, State and Country fields.

However, the next API call to `api/v1/pki/profiles` contains this informations.

Has been noticed on PF 11.0.0, I was able to replicate on PF 11.1.0

**To Reproduce**
1. Create a CA
2. Create a PKI template with Organisation, Organisation unit, State and Country fields
3. Edit yout PKI template to enable SCEP setting
3. Save
4. Open your PKI template and check values of Organisation, Organisation unit, State and Country fields

=> They are blank.

**Expected behavior**
Frontend should display values of PKI templates in DB

**Additional context**
Organisation, Organisation unit, State and Country have never been updated in DB, only SCEP setting is updated.

Certainly related to #6713

### LINKED ISSUE #6751: pfpki: PKI templates can be modified by a SCEP request
**Describe the bug**
If you create a PKI template with values for following fields : organisation, organisational_unit, country, state, locality, ocsp_url. Values of these fields (in PKI template) are removed when you request a certificate through SCEP using this PKI template.

User certificates doesn't contain these values too.

Has been noticed on 11.0.0, can be replicate on `devel`.

**To Reproduce**
1. Create a CA
2. Create a PKI template with values for organisation, organisational_unit, country, state, locality, ocsp_url (with SCEP enabled)
3. Request a certificate through SCEP 
4. Look value of fields for PKI template

=> They have been removed

5. Look value of fields for user certificate

=> Values are not here

**Expected behavior**
- PKI template should not be updated by a SCEP request
- User certificate should contain values of PKI template

**Additional context**
There is no specific error in logs.

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Return all attributes of the profile on PATCH
Fixes PKI templates can be modified by a SCEP request
Fixes PKI send email function to take the From parameter is it exists in the profile
Allow to edit PKI templates

# Impacts
PKI

# Issue
fixes #6713
fixes #6749
fixes #6751
fixes #6370
fixes #6671 

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* Fixes issue on PKI template save (#6749)
* Fixes issue on PKI templates can be modified by a SCEP request (#6751)
* Fixes issue with PKI From value when sending certificate by email (#6370)

### CODE REVIEW

**Review by nqb — COMMENTED** [review]
Code looks good to me. I will test now.

**Review by nqb — CHANGES_REQUESTED** [review]
I have seen following unexpected behaviors during my tests:

1. It's not possible to download or sent by mail a certificate generated through SCEP from web admin (using Download or Email buttons).

In web browser console, you got a 404 error with following message:  `tls: failed to find any PEM data in key input"`.

No issues with non-SCEP certificates.

2. `updated_at` field of PKI template is still updated when a new SCEP certificate is generated. I don't think it's necessary

3. If email is defined in PKI template, a certificate generated through SCEP (without email defined) will not get that attribute. I don't know it's expected.

**Comment by nqb** [comment]
Before merging this PR, I would like to adjust `dot1x_eap_tls_scenario` to reflect changes.

**Review by nqb — CHANGES_REQUESTED** [review]
Because this PR will change the way SCEP certificates are generated (PKI templates attributes override SCEP request attributes), we need to add an upgrade note to warn users.

**Comment by fdurand** [comment]
> I have seen following unexpected behaviors during my tests:
> 
> 1. It's not possible to download or sent by mail a certificate generated through SCEP from web admin (using Download or Email buttons).
> 
> In web browser console, you got a 404 error with following message: `tls: failed to find any PEM data in key input"`.
> 
> No issues with non-SCEP certificates.
> 
> 2. `updated_at` field of PKI template is still updated when a new SCEP certificate is generated. I don't think it's necessary
> 3. If email is defined in PKI template, a certificate generated through SCEP (without email defined) will not get that attribute. I don't know it's expected.

1. Yes it´s not possible to download it since there is no private key. We have to adjust that in the frontend.
2. i will have to check, it´s gorm who is managing the updated_at field.
3. Email is not part of the subject but it make sense to include it if there is no one defined in the scep request.

**Comment by fdurand** [comment]
To fix the Download for SCEP issued certificate i have to change the db schema.

**Comment by nqb** [comment]
> To fix the Download for SCEP issued certificate i have to change the db schema.

I don't think it's a problem because I don't think we can backport this PR on maintenance due to change related to SCEP attributes override or we need to have separate PR for things that could go in maintenance.

**Comment by nqb** [comment]
@fdurand, let me know if you plan to add new changes.

**Comment by fdurand** [comment]
I don´t think i have new change to add.

**Comment by nqb** [comment]
@fdurand: you said

> i will have to check, it´s gorm who is managing the updated_at field.

I don't think it's mandatory to fix. I'm fine to merge as is.

**Comment by fdurand** [comment]
ok let´s merge

**Pull request merged**
