### PR TITLE
feature/custom-root-pfappserver

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
-----------
Allow the Admin templates to be customizable

Impacts
-----------
The Admin GUI

NEWS file entries
-------

Enhancements
++++++++++++
* Allow the admin templates to be customizable

Delete branch after merge
-------------------------
NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Review me

**Comment by julsemaan** [comment]
Just add a quick note in the developers guide on the existence of this and its good to merge

**Comment by jrouzierinverse** [comment]
Updated

**Comment by jrouzierinverse** [comment]
Bump

**Comment by jrouzierinverse** [comment]
Bump

**Pull request merged**
