### PR TITLE
Feature/logoff page

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Provide a page for users to logoff of the current device (unregister it)

# Impacts
Captive portal

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Added captive portal page to unregister the device on which the user is currently connected (Network Logoff in connection profile)

### CODE REVIEW

**Comment by extrafu** [comment]
@jrouzierinverse Please review and comment before tomorrow.

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this?

**Review by jrouzierinverse — COMMENTED** [review]
After rebasing this seems to get stuck on one of the smoke tests t/serialized_unittests/merged_list.t

**Comment by jrouzierinverse** [comment]
Never mind it was pfconfig was stuck because of a corrupted berkelydb backend.

**Pull request merged**
