### PR TITLE
fix/double_nodes

### LINKED ISSUE #1848: Admin: Double nodes still showing up when there is a duplicate locationlog
There is two issues with this, first, the duplicate inline L3 locationlog (see #1847) and second we are still showing duplicate records when there are duplicate locationlogs (this issue is for the latest).

I believe we should address this duplicate locationlog issue directly in the admin so that we stop having this recurring problem to show double nodes when there are duplicate locationlogs.

image

image

P.S. : This is on 6.3

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Fixes the double nodes in the admin view

Impacts
=======
Admin node searching

Issue
=====
fixes #1848

Delete branch after merge
=========================
NO

NEWS file entries
=================

Bug Fixes
------------
* Fixes duplicate nodes displaying when there are multiple locationlog entries (#1848)

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
I would like someone to review/ test this on a decently sized set of nodes with for speed.

**Comment by dwlfrth** [comment]
SQL query error when doing a search

**Comment by dwlfrth** [comment]
Basically tested and does what it is supposed to.

**Comment by dwlfrth** [comment]
Tested with a DB with the following (relevant) specs:
node: 40771
locationlog: 48735

**Pull request merged**
