### PR TITLE
Added a floored value for iplog lease time

### LINKED ISSUE #1965: iplog: Floored lease time for "tolerance"
When opening an iplog entry (either creating a new one or updating an existing one), PacketFence is using the actual lease time of a given DHCP lease (if provided) or set a NULL (which defaults to 0000-00-00 00:00:00) as the 'end_time' for the record.

It looks like more and more device "may not care" about the provided lease time or it may be some other reason, but the thing is, we are seeing more and more issues where "The device cannot be found in PacketFence database" when trying to reach the captive-portal, which is the result of the portal not being able to get an "open" iplog entry to do the IP <-> MAC lookup.

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description
Add a default minimal value for iplog entries lease time (end_time)

# Impacts
* iplog
* portal
* dhcp

# Issue
fixes #1965 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* iplog: Floored lease time for "tolerance" (#1965)

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by extrafu** [comment]
Rebaisse

**Comment by dwlfrth** [comment]
Review and merge

**Comment by julsemaan** [comment]
Its all fine with me.

Do we cherry-pick in maintenance ?

If so, I'll let you squash merge it

**Comment by dwlfrth** [comment]
Merged into 
* maintenance/6.5
* maintenance/6.4

**Pull request merged**
