### PR TITLE
feature/node-on-off-online

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Have online offline not tied to the bandwidth accounting.

# Impacts
pfacct and displaying nodes in the admin

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Improve node online/offline detection

### CODE REVIEW

**Comment by julsemaan** [comment]
Just making sure since this is handled in pfacct.

Does having process_bandwidth_accounting disabled still gets the node_session updated?

**Comment by jrouzierinverse** [comment]
It is always processed.

**Comment by julsemaan** [comment]
It doesn't look like there are changes in the admin. Are any required or it will work auto-magically?

**Comment by jrouzierinverse** [comment]
It happens automagically. Look at the next page to see it, as it is the 26th config item.

**Comment by julsemaan** [comment]
> It happens automagically. Look at the next page to see it, as it is the 26th config item.

In this case, could we make the limit be like 50 items so what we don't have a single item being left out there. Or make the limit 10 so that it's obvious there are other pages

**Comment by jrouzierinverse** [comment]
@satkunas How can we change the default items limit requested from config/maintenance_tasks?

**Comment by satkunas** [comment]
```diff
diff --git a/html/pfappserver/root/src/views/Configuration/maintenanceTasks/_composables/useCollection.js b/html/pfappserver/root/src/views/Configuration/maintenanceTasks/_composables/useCollection.js
index 6e4054e398..4f69a6d075 100644
--- a/html/pfappserver/root/src/views/Configuration/maintenanceTasks/_composables/useCollection.js
+++ b/html/pfappserver/root/src/views/Configuration/maintenanceTasks/_composables/useCollection.js
@@ -17,6 +17,7 @@ import makeSearch from '@/store/factory/search'
 import api from '../_api'
 export const useSearch = makeSearch('maintenanceTasks', {
   api,
+  limit: 1000,
   sortBy: null, // use natural order (sortable)
   columns: [ // output uses natural order (w/ sortable drag-drop), ensure NO columns are 'sortable: true'
     {
```

**Pull request merged**
