### PR TITLE
switch filters enhancement

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Added to go in the 2nd level of a switch configuration (like change the vlan mapping)

# Impacts
Switch filters

# Delete branch after merge
YES | NO

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Modify the 2nd level of a switch configuration with the switch filters

### CODE REVIEW

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
This does not create the expected output.

```bash
perl <<'PERL'
my $switch = {};
my $switch_params = {
    'switch' => 'Cisco::WLC_5500',
    '_rule'  => 'msmodule4wired:wireless_locationlog|wireless_radius',
    'param3' => 'vlans => gaming => 40;registration => 10',
    'scope'  => 'instantiate_module'
};
foreach my $key (keys %{$switch_params}) {
    if (ref($switch_params->{$key}) eq 'ARRAY') {
        foreach my $param (@{$switch_params->{$key}}) {
            if ($param  =~ /([a-zA-Z_-]*)\s*=>\s*(.*)/) {
                $switch->{$key}->{$1} = $2;
            }
        }
    } elsif ($switch_params->{$key} =~ /([a-zA-Z_-]*)\s*=>\s*(.*)/) {
        $switch->{$key}->{$1} = $2;
    } else {
        $switch->{$key} = $switch_params->{$key};
    }
}

use Data::Dumper;print Dumper($switch);
PERL
$VAR1 = {
          'switch' => 'Cisco::WLC_5500',
          '_rule' => 'msmodule4wired:wireless_locationlog|wireless_radius',
          'param3' => {
                        'vlans' => 'gaming => 40;registration => 10'
                      },
          'scope' => 'instantiate_module'
        };
```

Also it might be better to put this in pf::config::builder::scoped_filter_engines->preprocessRule
As this will allow the filters to take advantage of nested parameters.

**Comment by fdurand** [comment]
If you use what pffilter return then it works.

```
perl <<'PERL'
my $switch = {};
my $switch_params = {
          '_vlans' => [
                      'gaming => 40',
                      'registration => 10'
                    ]
        };
foreach my $key (keys %{$switch_params}) {
    if (ref($switch_params->{$key}) eq 'ARRAY') {
        foreach my $param (@{$switch_params->{$key}}) {
            if ($param  =~ /([a-zA-Z_-]*)\s*=>\s*(.*)/) {
                $switch->{$key}->{$1} = $2;
            }
        }
    } elsif ($switch_params->{$key} =~ /([a-zA-Z_-]*)\s*=>\s*(.*)/) {
        $switch->{$key}->{$1} = $2;
    } else {
        $switch->{$key} = $switch_params->{$key};
    }
}

use Data::Dumper;print Dumper($switch);
PERL
$VAR1 = {
          '_vlans' => {
                        'gaming' => '40',
                        'registration' => '10'
                      }
        };
```

**Comment by fdurand** [comment]
Bump

**Comment by extrafu** [comment]
@jrouzierinverse Review and merge ASAP.

**Pull request merged**
