### PR TITLE
feature/upgrade-coredns

### LINKED ISSUE #7076: Upgrade coredns
**Upgrade coredns**

Upgrade coredns to 1.9.3 to fix

https://github.com/inverse-inc/packetfence/security/dependabot/34

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Upgrade coredns to use coredns 1.94.
Make coredns an external library to make upgrading easier in the future.

# Impacts
pfdns

# NEW Package(s) required
Upgrade to golang 1.19

# Issue
fixes #7076

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Upgrade coredns libraries

### CODE REVIEW

**Comment by fdurand** [comment]
Can you rebase ?

**Comment by jrouzierinverse** [comment]
Done

**Comment by fdurand** [comment]
Rebase on more time please

**Comment by jrouzierinverse** [comment]
Done

**Review by fdurand — APPROVED** [review]

**Pull request merged**
