### PR TITLE
Reorder iptables

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Reorder iptables.conf file to put INPUT rules in INPUT section (same for FORWARD)

# Impacts
Iptables rules

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Reorder iptables rules

### CODE REVIEW

**Comment by fdurand** [comment]
BUMP

**Review by nqb — APPROVED** [review]
LGTM

**Comment by atran-inverse** [comment]
@nqb and I have tested it with Inline and Registration.
Iptables order are correct.

**Review by atran-inverse — APPROVED** [review]
LGTM

**Comment by fdurand** [comment]
If it's ok then you can merge the PR

**Pull request merged**
