### PR TITLE
feature/bulk_config_actions

### LINKED ISSUE #4091: GET /api/v1/switches/bulk_{action}
We need some bulk action for switches, the most important would be to change the switch group. See #1095.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Add bulk_update and bulk_delete

Issue
=====
fixes #4091

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
This is ready for review.

**Comment by satkunas** [comment]
```ERROR pfperl-api(22365): Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 1224.```

Using:

```
/usr/local/pf/sbin/pfperl-api get -M POST -c '{"items":[{"id": "TEST1", "id": "TEST2", "id": "TEST3"}],"stopOnFirstError":true,"ignoreInsertIfNotExists":true,"ignoreUpdateIfExists":true}' /api/v1/config/realms/bulk_import
```

**Comment by satkunas** [comment]
@jrouzierinverse we won't be consuming the majority of these bulk endpoints from the web admin. At least not right away. Since we offer them, and don't consume them ourselves, we need some unittests for the `bulk_import` and `bulk_delete` methods.

**Comment by nqb** [comment]
Would be nice to have in 10.1.

**Comment by cgx** [comment]
@satkunas Can we consume the bulk actions to fix #4091? You could push your code to this PR.

**Comment by satkunas** [comment]
> @satkunas Can we consume the bulk actions to fix #4091? You could push your code to this PR.

@cgx I've got a separate PR open at https://github.com/inverse-inc/packetfence/pull/5034

Can we merge this so I can complete the work there?

**Pull request merged**
