### PR TITLE
Removed the "upstream" Combination listing

### PR DESCRIPTION
**Pull request by dwlfrth**
## Description

As the title says... remove the "upstream" Combination listing since not required.
Also, standardize the way tables looks and fix some displaying issue.
Adding "Search" and "Pagination" to "Local" "Devices" listing
## Impacts

Shouldn't be any
## Delete branch after merge

YES
## NEWS file entries

New Features
++++++++++++

Enhancements
++++++++++++
- Removed the unnecessary "Upstream" listing from the "Combination" menu item of Fingerbank section.
- Ability to search in Fingerbank "Local" "Devices" listing

Bug Fixes
+++++++++
- Fixes tables displaying bugs in Fingerbank menu items.

### CODE REVIEW

**Comment by julsemaan** [comment]
Saying No combination defined even though there are combinations defined. See screenshot : 
combinations

**Comment by dwlfrth** [comment]
Ahah fixing it... Actually, the whole html template is messed up... explaining half-lifes and so on...

**Comment by julsemaan** [comment]
It now works.

When devel is opened for merges, this is ready

**Comment by dwlfrth** [comment]
Please re-review

**Comment by julsemaan** [comment]
i don't know if it's related to this code but when going in Local devices and then back to upstream, the upstream button does not turn blue to indicate that upstream is selected. 

A refresh of the page fixes the issue, so I'm readding the zammitbug label

**Comment by julsemaan** [comment]
Other than the issue described above, this seems fine

**Comment by dwlfrth** [comment]
Running 'devel' I do see the same behavior. So, not related to this code.
Will have a look anyway...

**Comment by dwlfrth** [comment]
The 'active' tab issue seems to be related to the 'child view'. @jrouzierinverse would probably be better placed since he's the one who put it in place...
Please advise.

**Comment by dwlfrth** [comment]
No more need for @jrouzierinverse to take a look at it. Will merge

**Pull request merged**
