### PR TITLE
Dedicated API / apache webservice for AAA

### PR DESCRIPTION
**Pull request by julsemaan**
Adds a dedicated apache service for RADIUS authorization and accouting.

For review + merge

### CODE REVIEW

**Comment by fdurand** [comment]
Don´t forget iptables

**Comment by julsemaan** [comment]
It shouldn't be necessary since it's meant to be used only locally by the running radius server.

Should it be made public ?

**Comment by fdurand** [comment]
So why do you listen on the mamangement interface and not just 127.0.0.1 ?

**Comment by julsemaan** [comment]
Pretty good point ! I'll remove the listening interface on the management IP and leave only 127.0.0.1

**Comment by fdurand** [comment]
I prefer to be able to have a remote radius server.

**Comment by julsemaan** [comment]
Done, I added it to iptables so the service stays public

**Comment by julsemaan** [comment]
Merge me ?

**Comment by jrouzierinverse** [comment]
The following files were missed.

lib/pf/radius/rpc.pm
raddb/packetfence.pm
raddb/packetfence-soh.pm

**Comment by julsemaan** [comment]
Everything should have been fixed. _Ready_ to merge

**Comment by jrouzierinverse** [comment]
This looks good from a code point of view

**Comment by julsemaan** [comment]
Everything should be fixed.

Ready to merge if no more comments/reviews

**Pull request merged**
