### PR TITLE
Add failed connection fault tolerance to avoid false positive

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description
Add some fault tolerance on every connection tests in Monit to avoid false positive

# Impacts
Monit check "accuracy"

# Delete branch after merge
YES

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by dwlfrth** [comment]
Bump

**Comment by dwlfrth** [comment]
Will probably need to rebuild maintenance script package with this one (@julsemaan)

**Comment by julsemaan** [comment]
That looks good

**Comment by julsemaan** [comment]
Updated monit.tgz on monitoring script mirror

**Pull request merged**
