### PR TITLE
Show better error messages when auth doesn't give proper role or unregdate

### LINKED ISSUE #380: Max number of devices reached.
Correct that message please.

### PR DESCRIPTION
**Pull request by whitx**
## Description

Show accurate error message while trying to auth on a source that doesn't have role or unregdate matching your login username(instead of max devices reached).
fixes #380
## Impacts

Authentication with a source that does not have role or unregdate setup. 
## NEWS file entries

Bug Fixes
+++++++++

Fix error messages.
## Delete branch after merge

NO

### CODE REVIEW

**Comment by cgx** [comment]
Does the error really mean anything to the user? Since the remediation involves an administrator, shouldn't we return an error such as:

> Your username has currently no access to the network. Please contact your network administrator.

And we should provide the phone number and/or email address of the helpdesk/administrator.

**Comment by whitx** [comment]
Then shouldn't it be

> the error message + "Please contact your network administrator" 

With mail/number, this way the admin know straight why he doesn't have access(w/o looking through logs).

**Comment by cgx** [comment]
That's fine!

**Comment by louismunro** [comment]
I believe this does not solve the problem.
See maxRegNodesReached in html/captive-portal/lib/captiveportal/PacketFence/Controller/CaptivePortal.pm

**Comment by louismunro** [comment]
I could be wrong. Have you tested this?

**Comment by whitx** [comment]
I tested, while logging through the source, The right message popup, anyhow there is way more to do if we want to improve the message, since we will need this for every other messages.

**Comment by whitx** [comment]
Worked with AD, it doesnt with Email, trying other sources now

**Comment by louismunro** [comment]
Ok, then let's do it please.

**Comment by louismunro** [comment]
Would also require translation and i18n.

**Comment by julsemaan** [comment]
I wouldn't say to contact the administrator personally. 

The thing is you could match no auth rule in a source but bind to it. ex : my AD username + password is ok but I'm not part of the group that can have access.

Then get role will return nothing, but not because of a misconfiguration, but because I'm not aloud to connect to the network.

Asking to contact the administrator would suggest that the user deserves network access but that a problem has happened.

**Comment by julsemaan** [comment]
Same thing with max devices actually. If I reached the maximum number of devices then I shouldn't contact my admin. I should unregister devices.

**Comment by julsemaan** [comment]
Also from what I remember showError I18N's the errors directly so it just needs to be added to transifex

**Comment by cgx** [comment]
So back to my initial comment: let's make the error message meaningful to the user and give her a remedial procedure if any. Examples of sentences that could be appended or prefixed to the error message:
- You don't have access to the network.
- Please unregister a device before registering a new one.
- You've been lost in an `else clause` of PacketFence.

**Comment by julsemaan** [comment]
I really like the last one.

Jokes apart I'll rework those tomorrow

**Comment by extrafu** [comment]
We could also let users know to call the 24/7 hotline and use Giorgio's number in there.

**Comment by julsemaan** [comment]
I've made the error message better. Didn't go into the whole contact administrator thing since this is clearly out of the scope of 4.7.

The max node reached has to be reworked to bring the user to a page to unregister devices anyway.

**Comment by julsemaan** [comment]
wait before merging, still needs guests to be fixed

**Comment by louismunro** [comment]
Looks good to me.
"Le mieux est l'ennemi du bien."
Merge away!

**Comment by whitx** [comment]
Still not owrking on email/sms reg

**Comment by julsemaan** [comment]
Fixed and tested. Waiting for @whitx to test also and we'll merge.

**Pull request merged**
