### PR TITLE
Use source from profile if none is set in Module.

### LINKED ISSUE #8392: Portal Module for SMS or SPonsor doesn't use the source from the connection profile if none is defined in the portal module.
**Describe the bug**
Title say it

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Use source from profile if none is set.

# Issue
fixes #8392

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Use source from profile if none is set in portal module.

### CODE REVIEW

**Comment by fdurand** [comment]
When i try the sponsor (without source defined in the portal module):
```
2024-12-16T15:46:14.998328-05:00 packetfence-dev httpd.portal-docker-wrapper[423228]: httpd.portal(13) ERROR: [mac:00:11:22:33:44:55] Attribute (source) does not pass the type constraint because: Validation failed for 'pf::Authentication::Source::SponsorEmailSource' with value undef at accessor captiveportal::PacketFence::DynamicRouting::Module::Authentication::Sponsor::source (defined at /usr/local/pf/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm line 32) line 18
```

with email:
```
2024-12-16T15:47:03.566829-05:00 packetfence-dev httpd.portal-docker-wrapper[423228]: httpd.portal(14) ERROR: [mac:00:11:22:33:44:55] Caught exception in captiveportal::Controller::Root->dynamic_application "Can't generate template signin.html: undef error - Can't call method "isa" on an undefined value at /usr/local/pf/lib/captiveportal/PacketFence/Form/Authentication.pm line 79.
```

**Review by fdurand — CHANGES_REQUESTED** [review]
It produce error on the captive portal

**Comment by jrouzierinverse** [comment]
Can you please try again?

**Comment by fdurand** [comment]
Sponsor looks to work now but Email no:

```
Caught exception in captiveportal::Controller::Root->dynamic_application "Can't generate template signin.html: undef error - Can't call method "isa" on an undefined value at /usr/local/pf/lib/captiveportal/PacketFence/Form/Authentication.pm line 79. Error : undef error - Can't call method "isa" on an undefined value at /usr/local/pf/lib/captiveportal/PacketFence/Form/Authentication.pm line 79."
```

**Comment by fdurand** [comment]
It works for Email/SMS and Sponsor. I tested other type of source and there is the same kind of issue.
I will open a new PR for the rest of the sources and merge that one.

**Review by fdurand — APPROVED** [review]

**Pull request merged**
