### PR TITLE
remove "password server" from samba chroot config

### PR DESCRIPTION
**Pull request by kkplein**
Removed the "password server" from the generated chroot config
as recommended by the samba core team members Andrew Bartlett
and Rowland Penny here:
https://lists.samba.org/archive/samba/2017-June/208999.html

The "password server" option exists, to be able to *restrict* samba from using all available servers, but rather make it stick to one or more specific DCs.

# Description
After some discussion on the samba mailinglist on the packetfence generated smb.conf in the chroot, it was concluded that removing the "password server = " option from smb.conf is the better way of doing things. With the line removed, it will default to "password server = *" and that will use the samba builtin-mechanisms to locate all available DCs.
Specially in the case of using 802.1x auth, the DC selection/location should be as robust and fool-proof as possible.

# Impacts
I am not aware of any other impact, rather than improving the DC location/selection behaviour.

# Delete branch after merge
YES

# NEWS file entries
none

## Enhancements
* use the regular samba mechanisms to locate and select DCs

# UPGRADE file entries
none

### CODE REVIEW

**Comment by julsemaan** [comment]
To our knowledge, this doesn't prevent samba from talking to other servers but I don't see anything wrong with removing it so that it uses the samba default

**Review by julsemaan — APPROVED** [review]

**Comment by julsemaan** [comment]
If somebody objects on this being merged, please speak up or I'll merge this before the 7.3 merge window closes

**Comment by julsemaan** [comment]
**** 7.2 I mean

**Comment by dwlfrth** [comment]
I'd say, make it a configuration parameter of the domain configuration defaulted to *.
That would be more "customizable", a bit like the OU thing...

**Comment by kkplein** [comment]
haha, but i have no idea how to change this (*extremely*) simple pull request into what you are proposing...

**Comment by dwlfrth** [comment]
Ahah ! I'll take care of it

**Comment by kkplein** [comment]
:-) Much appreciated!

**Comment by dwlfrth** [comment]
Closing this PR since it will be addressed by #2410

**Comment by julsemaan** [comment]
@dwlfrth addressed this in a configurable way

@kkplein thanks for your input and for the research around the samba config

**Comment by kkplein** [comment]
Haha my pleasure. Nice to be able to contribute something.

**Pull request closed without merging**
