### PR TITLE
add GNU/Linux servers to virtual environment

### PR DESCRIPTION
**Pull request by nqb**
# Description
Add GNU/Linux servers to virtual environment to test integrations.

# Impacts
CI tests

# Delete branch after merge
YES

# Checklist
- [x] Document the feature

### CODE REVIEW

**Comment by nqb** [comment]
rsyslog provisioning using Ansible on `linux01` with latest DebOps collection doesn't work due a bug fixed by https://github.com/debops/debops/commit/52302ac155b24c54fe03c783a47c06cc88ccd936.

Issue will be fixed with a new release of DebOps collection (currently v2.1.2).

A possible workaround is to override variable in inventory.

**Comment by nqb** [comment]
@JeGoi,

I apply your recipe to put Linux servers in a dedicated Vagrantfile. Tested to start VM and Ansible provisioning: it works.

**Comment by JeGoi** [comment]
Do we need to had some info in requirement file, don't we?
https://github.com/inverse-inc/packetfence/blob/devel/addons/vagrant/requirements.yml

**Comment by nqb** [comment]
No, DebOps collection is already included in `requirements.yml`.

**Review by JeGoi — CHANGES_REQUESTED** [review]
Ok, it looks perfect.
And, as we spoke, it will need rebase after the merge of https://github.com/inverse-inc/packetfence/pull/6081
So the change request is only on that point. Thanks

**Comment by JeGoi** [comment]
Rebase and merged

**Pull request merged**
