### PR TITLE
feature/watchguard-firewall-sso

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
-----------
New Firewall SSO for WatchGuard

Impacts
-----------
Firewall SSO

NEWS file entries
-------

New Features
++++++++++++
* New Firewall SSO for WatchGuard

Delete branch after merge
-------------------------
NO

### CODE REVIEW

**Comment by extrafu** [comment]
@julsemaan Review + test with your best buddy.

**Comment by extrafu** [comment]
Bump

**Comment by julsemaan** [comment]
Contact done, waiting for reply

**Comment by julsemaan** [comment]
@jrouzierinverse 

can you provide me the watchguard document you followed to determine the attributes to send out

Thanks

**Comment by jrouzierinverse** [comment]
http://www.watchguard.com/help/docs/fireware/11/en-US/Content/en-US/authentication/rsso_enable.html

**Comment by julsemaan** [comment]
Seems to have been working

Will require some doc before we merge though

**Comment by julsemaan** [comment]
The watchguard only supports 1 RADIUS SSO server so active/active needs to send the packets from the VIP

Please apply the following patch to your branch:
```
diff --git a/lib/pf/firewallsso.pm b/lib/pf/firewallsso.pm
index 6bec42c..404e27f 100644
--- a/lib/pf/firewallsso.pm
+++ b/lib/pf/firewallsso.pm
@@ -28,6 +28,7 @@ use pf::constants qw(
 use pf::log;
 use List::MoreUtils qw(any);
 use NetAddr::IP;
+use pf::cluster;
 
 =head1 SUBROUTINES
 
@@ -91,6 +92,24 @@ sub do_sso {
 
 }
 
+=item sso_source_ip
+
+Computes which IP should be used as source IP address for the SSO
+
+Takes into account the active/active clustering
+
+=cut
+
+sub sso_source_ip {
+    my ($self) = @_;
+    if($cluster_enabled){
+        pf::cluster::management_cluster_ip();
+    }
+    else {
+        return $management_network->tag('vip') || $management_network->tag('ip');
+    }
+}
+
 
 =back
 
diff --git a/lib/pf/firewallsso/WatchGuard.pm b/lib/pf/firewallsso/WatchGuard.pm
index 1056513..9d484d0 100644
--- a/lib/pf/firewallsso/WatchGuard.pm
+++ b/lib/pf/firewallsso/WatchGuard.pm
@@ -55,6 +55,7 @@ sub action {
             nas_ip   => $firewall_conf,
             nas_port => $config->{'port'},
             secret   => $config->{'password'},
+            LocalAddr => $self->sso_source_ip(),
         };
 
         my $attributes = {
@@ -82,6 +83,7 @@ sub action {
             nas_ip   => $firewall_conf,
             nas_port => $config->{'port'},
             secret   => $config->{'password'},
+            LocalAddr => $self->sso_source_ip(),
         };
 
         my $attributes = {
```

Or if I can get push rights on it. Whatever is easier for you

**Comment by jrouzierinverse** [comment]
You have the push rights

**Comment by extrafu** [comment]
Bump

**Comment by julsemaan** [comment]
Need the doc done and we'll be merging

**Comment by extrafu** [comment]
Who takes care of the doc part? As mentioned during our meeting on Monday, we just want to link to the official documentation somewhere in our documentation.

**Comment by julsemaan** [comment]
I'll leave that fun part to the author :P

**Comment by extrafu** [comment]
Since each firewall SSO module has its own guide and we don't have time write one specifically for Watchguard, let's merge it for now and plan for a guide.

**Pull request merged**
