### PR TITLE
fix/pfacct-balance-6358

### LINKED ISSUE #6358: Time balance subtracted when unreg
title says it all

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Only reduce time balance when registered.

Impacts
=======
Radius Accounting time balance calculation

NEWS file entries
=======================

Bug Fixes
-------------
* Reducing time balance only when registered.

Issue
=====
fixes #6358

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
Lets get @lzammit to test this fix and get this into 11.1 and potentially backport this to the maintenance (we can discuss this after we know the fix works)

**Comment by julsemaan** [comment]
@lzammit, were you able to test this fix and validate it works as expected?

**Comment by extrafu** [comment]
@jrouzierinverse / @lzammit discuss this

**Comment by julsemaan** [comment]
This is the last day for our feature freeze, can we expect this to be sorted out today?
Otherwise we push this to 11.2

**Comment by jrouzierinverse** [comment]
Waiting on feedback from @lzammit

**Comment by fdurand** [comment]
Did a test yesterday and just checked this morning the result.
Looks to be ok on my side.
I am ok to merge !

**Pull request merged**
