### PR TITLE
Remove old static macs in radius/port-sec hybrid environement

### PR DESCRIPTION
**Pull request by julsemaan**
Adapted the behavior that's in pfsetvlan when a mac moves from a static port sec port to another port.

Prevents macs from being kept in the static table of the old switch.

For review and merge

### CODE REVIEW

**Comment by julsemaan** [comment]
Merge me ?

**Comment by dwlfrth** [comment]
Shouldn't we have some "reviewed and ready to merge" comment before merging... Otherwise, it is pretty simple to just click the merge button and we kind of loosing the peer-review concept...

**Comment by julsemaan** [comment]
Well I review before merging. I know James reviewed before merging this but we could wait for 2 reviewers to check and then call a merge

**Comment by dwlfrth** [comment]
No doubt about it, but the person who submit the pull-request cannot really be a reviewer ;) and there's no traces that James actually reviewed it..
Only
Merge me, merged

**Comment by jrouzierinverse** [comment]
I think one person is enough.
However we should (automatically) run a smoke test just make sure the basics have been covered.

**Comment by dwlfrth** [comment]
As James said, one person is enough. Only thing, that person should, at least, comment on the pull-request saying that it's been reviewed. (There's an option to do it on merge, all hail github!)

**Comment by jrouzierinverse** [comment]
I reviewed this code and liked it!

**Pull request merged**
