### PR TITLE
getting rid of pf::useragent

### LINKED ISSUE #2447: Remove pf::useragent
From what I can tell its useless now that we have Fingerbank

Will need to remove the tables that go with it and all that other boring stuff

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Remove pf::useragent which is deprecated

# Impacts
Everywhere pf::useragent could have been used (httpd.admin, httpd.portal, node lookup)

# Issue
fixes #2447 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Forgot to remove the reference to useragent.t in t/TestUtils.pm

**Comment by jrouzierinverse** [comment]
Forgot to remove /usr/local/pf/addons/upgrade/to-2.2.0-update-all-useragents.pl

**Comment by jrouzierinverse** [comment]
Forgot to remove references to the node_useragent database in
lib/pf/pfcmd/report.pm

Did not remove these files.
* lib/pf/dal/_node_useragent.pm
* lib/pf/dal/node_useragent.pm

**Comment by jrouzierinverse** [comment]
Should we include dropping that database in the upgrade script.

**Comment by julsemaan** [comment]
@jrouzierinverse 

Not sure I'll drop the database in the upgrade script :) but I'll drop the useragent table though

I'll leave dropping databases to @lzammit

**Comment by julsemaan** [comment]
Adjustments performed

**Comment by jrouzierinverse** [comment]
A few more references to useragent stuff we both missed.

* t/dao/report.t (or should we just remove this test since it is never used)

* the admin role USERAGENTS_READ - would need to add instructions or script to remove from conf/adminroles.conf (script would be nicer for the user since it would be only a single step)

* pf/addons/dev-helpers/useragent-build-regexp.pl

**Comment by jrouzierinverse** [comment]
Rebase

**Comment by julsemaan** [comment]
Now depends on #2509 for the run_as_pf command in the upgrade script so it should be merged before merging this

Other than this, its ready for another review

**Pull request merged**
