### PR TITLE
Display connection profile matched by a CLI login

### PR DESCRIPTION
**Pull request by nqb**
# Description
When you use CLI login, a connection profile is instantiated using a fake MAC which doesn't exist in PacketFence DB.
Current logic doesn't write a line in logs with connection profile matched in that's case which make troubleshooting difficult.

This PR change this behavior to display a line in a log with connection profile matched when we received a RADIUS request for CLI login.

# Impacts
Connection profile instantiation.

# Delete branch after merge
YES

# Checklist
- [X] Add unit tests

## Enhancements
* Log connection profile matched when using CLI login

### CODE REVIEW

**Comment by nqb** [comment]
I also want to mention that we don't use same logic as for `authorize` regarding audit log. So I was not able to save in DB the profile matched, like I did on #5977

**Comment by nqb** [comment]
Pipeline failed, I need to review my code.

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
I got ```"$FAKE_MAC" is not exported by the pf::constants module``` when I tried to test this.
Add the ```$FAKE_MAC``` in the ```@EXPORT``` array in ```pf::constants```

**Comment by nqb** [comment]
Done.

**Comment by jrouzierinverse** [comment]
Can you retry to see if the pipeline is working now?

**Comment by nqb** [comment]
Yes sure.

**Comment by nqb** [comment]
It works this time.

**Pull request merged**
