### PR TITLE
Removal of web admin (second part)

### LINKED ISSUE #6150: Builds failed after removal of old web admin
After merge of #6118, CentOS and Debian builds failed
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1067056862
- https://gitlab.com/inverse-inc/packetfence/-/jobs/1067056866

### PR DESCRIPTION
**Pull request by nqb**
# Description
- Remove items related to old web admin, next part of #6118
- Move contents of `static.alt` directory to `html/pfappserver/root` (`static.alt` and  `static` directories doesn't exist anymore)
- Adjust paths and filenames

# Impacts
- Builds
- Installations
- Maintenance
- Upgrade

# Issue
fixes #6150 

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Old web admin has been removed

### CODE REVIEW

**Comment by nqb** [comment]
It should be ok now. Trying to build here: https://gitlab.com/inverse-inc/packetfence/-/pipelines/264565543

**Comment by nqb** [comment]
Build failed, I got an error certainly related to https://github.com/inverse-inc/packetfence/commit/2bc107e6f867d120ee2956125253396451d6fdfb.

@cgx, could you take a look ?

**Comment by cgx** [comment]
Here's what I propose.

1. We move everything under `html/pfappserver/root/static.alt` up one parent to `html/pfappserver/root`.
2. We add the missing 502/503 JSON files to `html/pfappserver/root/errors`.
3. We use `/admin` as the new default Web admin URL.

**Comment by cgx** [comment]
@nqb Please remove references to `pfappserver` in [httpd.proxy.tt](https://github.com/inverse-inc/packetfence/blob/81f355b70c04e6360c692d0997b2bd568f48bda5/conf/httpd.conf.d/httpd.proxy.tt.example#L124-L125).

**Comment by nqb** [comment]
@cgx, I updated Description of this PR to reflect latest changes. 

Could you update `conf/I18N/api/{en,fr}.po` files with new paths ?

I ran two pipelines:
- branch of this PR: https://gitlab.com/inverse-inc/packetfence/-/pipelines/268103025
- maintenance/99.9 branch here (rebased on current branch): https://gitlab.com/inverse-inc/packetfence/-/pipelines/268115401

Tests:
- Build: OK
- Build maintenance artifacts: OK
- Installation on 
  * CentOS: OK
  * Debian: failed, pfperl-api issue
- Patching Debian/CentOS on 99.9: OK

**Comment by nqb** [comment]
On Debian, API is not working. Journalctl on `pfperl-api` reported following error:

```
Mar 10 09:53:13 pfdeb9dev packetfence[17939]: pfperl-api(17911) ERROR: Can't locate pfappserver/Model/Enforcement.pm in @INC (you may need to install the pfappserver::Model::Enforcement module) (@INC contains: /usr/local/pf/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config/Interfaces.pm line 18.
```

Caused by ef0fbbdd5daea7c7f41638a1f7f66360d12af332. On CentOS, symlink is still present.

@jrouzierinverse, do you want to adjust `pfperl-api` configuration or revert your commit ?

**Comment by nqb** [comment]
Some unit tests are failing:

https://gitlab.com/inverse-inc/packetfence/-/jobs/1085972145

@jrouzierinverse will look into this

**Comment by nqb** [comment]
@cgx,

Should be good from my side now. I will let you merge when PO files have been updated (like mentioned previously).

**Pull request merged**
