### PR TITLE
Removed commented code because no one maintains it and can lead to depre...

### PR DESCRIPTION
**Pull request by dwlfrth**
...cated code issue.

### CODE REVIEW

**Comment by dwlfrth** [comment]
Ready to be merged...

**Comment by julsemaan** [comment]
I would still leave the example methods in custom.pm with a simple example and a call to super at the end. That would remove the need to maintain the methods while showing how to use them.

**Comment by dwlfrth** [comment]
@julsemaan: Good idea, done.

**Comment by dwlfrth** [comment]
Can we merge ?

**Pull request merged**
