### PR TITLE
Always log the ip and mac for the captive portal

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Always log the ip and mac in the captive portal for everry log entry
## Impacts

Captive portal logging
## NEWS file entries

Enhancements
++++++++++++
- The client's mac and ip address is always logged for every log entry
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
This will add the mac and ip to every line in httpd.portal log entries

You can see the difference here between these two lines.

Jul 12 22:48:44 httpd.portal(3928) ERROR: Can't bind : IO::Socket::INET: connect: Connection refused

Jul 12 22:48:44 httpd.portal(3928) ERROR: [mac:0a:00:27:00:00:00 ip:192.168.56.1] Can't bind : IO::Socket::INET: connect: Connection refused

**Comment by jrouzierinverse** [comment]
Please Review

**Comment by jrouzierinverse** [comment]
We may want to consider this for 5.3.1 but most definitely 5.4.0

This improves logging for the captive portal by allowing use to following a particular mac or ip.

You want to see the activity for a node in the captive portal then just do the following.

```
tail log/packetfence.log | grep mac:01:02:03:04:05:06
```

As this will be done for every log entry there is no longer the need to always add the node or ip in the log entry itself.

**Comment by lzammit** [comment]
Looks good to me, need to be tested.

**Comment by jrouzierinverse** [comment]
Then test it

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by julsemaan** [comment]
image

**Pull request merged**
