### PR TITLE
Sponsor choose access duration

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Allow the sponsor to choose the access duration
Define which authentication source used to verify that the sponsor is allowed to sponsor.

# Impacts
Sponsor flow

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Allow the sponsor to choose the access duration
* Define which authentication source used to verify that the sponsor is allowed to sponsor.

### CODE REVIEW

**Comment by extrafu** [comment]
@jrouzierinverse To review and @lzammit to test.

**Comment by jrouzierinverse** [comment]
rebase

**Comment by fdurand** [comment]
Rebased.

**Comment by jrouzierinverse** [comment]
Looks good @lzammit please test

**Comment by extrafu** [comment]
@jrouzierinverse Correct me if I'm wrong here but the new GUI needs to be modified for this too. It'll have to be adjusted by @satkunas prior merging or immediately after.

**Comment by jrouzierinverse** [comment]
Yes as it adds a new field in Sponsor sources

**Review by jrouzierinverse — APPROVED** [review]
Approved!

**Comment by julsemaan** [comment]
image

**Comment by fdurand** [comment]
If approved , can we merge ?

**Comment by jrouzierinverse** [comment]
Did Zammit test it?

**Comment by fdurand** [comment]
Not part of his test to do.

**Comment by nqb** [comment]
I update NEWS section of the description to add "Define which authentication source used to verify that the sponsor is allowed to sponsor", see #3631. Thanks @jrouzierinverse

**Comment by fdurand** [comment]
@satkunas the new admin GUI needs to be adjusted for this PR

**Comment by fdurand** [comment]
@satkunas can you help for the new admin ?

**Comment by fdurand** [comment]
Retested from the new admin gui and register on the portal.
The code works on my side.
Ready to merge.

**Comment by extrafu** [comment]
Should we move that to v9.1? It's currently targeted for 9.2.

**Pull request merged**
