### PR TITLE
Composition Configurator

### PR DESCRIPTION
**Pull request by satkunas**
# Description
Refactor the UI Congfigurator to utilize the Vue 3 composition API.

# Impacts
Improves (does not alter or re-order) form workflow through configurator. 
Increases visibility of server-side errors.
Utilizes pfqueue polling to address timeouts on long requests.

# Delete branch after merge
YES 

# Checklist
(REQUIRED) - [yes, no or n/a]
- [n/a] Document the feature
- [n/a] Add unit tests
- [ ] Add acceptance tests (TestLink)

## Enhancements
* Improves (does not alter or re-order) form workflow through configurator. 
* Increases visibility of server-side errors.
* Utilizes pfqueue polling to address timeouts on long requests.
* Add Fingerbank proxy to configurator.

## Bug Fixes
* API - Database Create timeout (#5550)
* Installation - Step 3 MySQL Create Database (#3707)
* configurator: provide a way to configure Fingerbank proxy (#3980)

### CODE REVIEW

**Comment by satkunas** [comment]
Waiting on (#6128) before finalizing.

**Comment by nqb** [comment]
I will need to adjust integration tests related to configurator in order to use new pfqueue API calls. This should be simple because I already did it Venom when [joining domain](https://github.com/inverse-inc/packetfence/blob/1d7d7fbc768f952a7e04aec96c23ff64f8017636/t/venom/pfservers/dot1x_eap_peap/05_join_domain.yml#L60-L74).

@jrouzierinverse or @satkunas, which API calls are concerned ?

**Comment by satkunas** [comment]
@nqb the endpoint isn't new, and is now used with 4 endpoints:

You can grep for them using `pfqueue/pollTaskStatus`:
```
#ag pfqueue/pollTaskStatus -B 1

src/views/Configuration/bases/_store.js
891-    }).then(({ task_id }) => {
892:      return store.dispatch('pfqueue/pollTaskStatus', task_id).then(response => {

src/views/Configuration/domains/_store.js
118-    return api.joinDomain(data).then(response => {
119:      return store.dispatch('pfqueue/pollTaskStatus', response.task_id).then(response => {
--
130-    return api.rejoinDomain(data).then(response => {
131:      return store.dispatch('pfqueue/pollTaskStatus', response.task_id).then(response => {
--
142-    return api.unjoinDomain(data).then(response => {
143:      return store.dispatch('pfqueue/pollTaskStatus', response.task_id).then(response => {
```

* [baseurl]/config/base/database/create
* [baseurl]/config/domain/:id/join
* [baseurl]/config/domain/:id/rejoin
* [baseurl]/config/domain/:id/unjoin

The base url for these 4 endpoints can be either /api/v1/configuration/... or /api/v1/configurator/...

Once the above issue is addressed this list will include the service endpoint.

**Review by julsemaan — CHANGES_REQUESTED** [review]
As discussed with @satkunas, since the API calls now require pfqueue, both redis_queue and pfqueue need to be started on install for both CentOS and Debian. 

Otherwise the DB fails to get setup.

Also, we need to ensure that pfqueue and redis_queue get started on reboot during a new install, perhaps by adding them to the packetfence-base target since they are now necessary even when PF is fresh installed

**Comment by satkunas** [comment]
Moved to #6167

**Pull request closed without merging**
