### PR TITLE
Pruned useless code from radius.pm.

### PR DESCRIPTION
**Pull request by louismunro**
# Description

Spring cleanup.
Deleting useless code we never used for years.
# Impacts

Should be none.
This is code that always returns true and has not been used for years.
# Delete branch after merge

YES 
# NEWS file entries
## Enhancements
- Spring cleaning (not worth mentioning in NEWS file).

### CODE REVIEW

**Comment by louismunro** [comment]
Give me a good reason why I should not do this...

**Comment by extrafu** [comment]
Because Zaymmitte said so?

**Comment by jrouzierinverse** [comment]
Just to play devil's advocate one reason to keep it is to make easier to write custom behavior in pf::radius::custom.

**Comment by louismunro** [comment]
I thought about that, but since we haven't do that in years, how likely are we to start doing it now?

**Comment by fdurand** [comment]
Hi devil's advocate, we can do it now in the radius filter.

**Comment by jrouzierinverse** [comment]
You are correct but not as is.
We would have to add the a new scope to do so.

**Comment by fdurand** [comment]
[wiremacauth]
filter = connection_type
operator = is
value = WIRED_MAC_AUTH

[wireeap]
filter = connection_type
operator = is
value = Ethernet-EAP

[wirelessmacauth]
filter = connection_type
operator = is
value = Wireless-802.11-NoEAP

[wirelesseap]
filter = connection_type
operator = is
value = Wireless-802.11-EAP

[1:!wiremacauth|!wireeap|!wirelessmacauth|!wirelesseap]
merge_answer = no
scope = returnRadiusAccessAccept
status = RLM_MODULE_NOOP
answer1 = Reply-Message => Not acting on this request

**Comment by jrouzierinverse** [comment]
That would work.
However I meant adding a scope right after _handleStaticPortSecurityMovement to the extra work.
Maybe $switch->skipRadiusAccessAccept();

**Comment by louismunro** [comment]
Let's do this right.
Moving to v6.

**Comment by julsemaan** [comment]
Not sure where the debate is on this, I would personally go with the removal of these as they are not used at all, and as @fdurand said, this can be accomplished via a RADIUS filter, should need be.

If we are majorly happy with this, I'd say to merge that

**Pull request merged**
