### PR TITLE
Enhancements to AD integration scripts

### PR DESCRIPTION
**Pull request by cmammoli**
# Description
1) Enforce use of TLS in the powershell scripts which is required with the last versions of PF
2) Cycle through all the possible Active Directory usernames formats in PacketFence:
username
UPN (username@fqdndomain)
Netbios (DOMAIN\username)
SPN (host/computername)

# Impacts
AD integration scripts

# Delete branch after merge
YES 

## Enhancements
* Enforce use of TLS in the powershell scripts which is required with the last versions of PF
* Cycle through all the possible Active Directory usernames formats in PacketFence

### CODE REVIEW

**Comment by julsemaan** [comment]
It does look good, I'd agree to merge that one unless someone else from @inverse-inc/packetfence objects to that one

**Comment by julsemaan** [comment]
@cmammoli please accept the CLA and we will happily merge this PR

**Comment by cmammoli** [comment]
I tought I already accepted it:

CLAassistant commented 3 days ago

CLA assistant check
All committers have signed the CLA.

**Comment by julsemaan** [comment]
@cmammoli we refreshed it and its fine now, thanks

**Comment by julsemaan** [comment]
@cmammoli 

As a side note, next time always do your PRs against devel since that is our master branch.

We'll then pick your changes into the maintenance branches if appropriate.

Thanks again for your contribution

**Comment by cmammoli** [comment]
@julsemaan ok, sorry

**Pull request merged**
