### PR TITLE
feature/unassign_nodes_api

### LINKED ISSUE #3560: New endpoint POST user/:id/unassign_nodes

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Expose the ability to unassign a user nodes through the api

Fixes #3560

### CODE REVIEW

**Comment by satkunas** [comment]
Error with:

```/usr/local/pf/sbin/pfperl-api get -M POST -c '{}' /api/v1/user/talonso/unassign_nodes | jq```

```
Oct  2 15:33:29 packetfence packetfence: ERROR pfperl-api(5741): Can't locate object method "id" via package "pf::UnifiedApi::Controller::Users" at /usr/share/perl5/vendor_perl/Mojolicious.pm line 138.
 (Mojolicious::Plugin::DefaultHelpers::_development)

Oct  2 15:33:29 packetfence packetfence: WARN pfperl-api(5741): format() is not properly implemented in MojoX::Log::Log4perl. Please use appenders. at /usr/share/perl5/vendor_perl/MojoX/Log/Log4perl.pm line 25.
 (MojoX::Log::Log4perl::format)
```

**Comment by satkunas** [comment]
Please document the enpoint(s) in the openapi spec.

**Comment by extrafu** [comment]
Bump - what's the status on this one?

**Comment by extrafu** [comment]
Bump.

**Comment by satkunas** [comment]
No response and seeing errors via CLI:
```
/usr/local/pf/sbin/pfperl-api get -M POST -c '' /api/v1/user/dsatkunas/unassign_nodes | jq
```
Use of bare << to mean <<"" is deprecated at /usr/local/pf/lib/pf/UnifiedApi/Controller/Users.pm line 42.
Use of bare << to mean <<"" is deprecated at /usr/local/pf/lib/pf/UnifiedApi/Controller/Users.pm line 48.
Possible unintended interpolation of @inverse in string at /usr/local/pf/lib/pf/UnifiedApi/Controller/Users.pm line 51.
...
parse error: Invalid numeric literal at line 1, column 10

**Comment by jrouzierinverse** [comment]
It looks like you some how a merge happened and some conflict markers got in that setup.

**Comment by jrouzierinverse** [comment]
It works in my environment.

```bash
/usr/local/pf/sbin/pfperl-api get -M POST -c '' /api/v1/user/dsatkunas/unassign_nodes | json_xs
```

```json
{
   "errors" : [],
   "status" : 404,
   "message" : "Unable to get resource with this identifier"
}
```

**Pull request merged**
