### PR TITLE
Cleanup web libs to remove CGI leftovers

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description

Remove leftovers from the CGI captive-portal
# Impacts

Shouldn't have any since it was mostly dead code. Would be good to test the whole captive-portal flow anyway to make sure nothing is now broken
- billing
- guest
- device-registration
- email-activation (full)
# Delete branch after merge

YES
# NEWS file entries
## Enhancements
- Cleanup in web libs (pf::web, pf::web::*) to remode dead code from CGI captive-portal

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by fdurand** [comment]
There is probably stuff to remove in captive-portal-common.conf

**Comment by dwlfrth** [comment]
Review me

**Comment by jrouzierinverse** [comment]
I prefer to wait for 5.2 I do not think 1 week is enough time for testing.

**Comment by dwlfrth** [comment]
That's dead code not even used by anything.
Reviewing it doesn't necessarily implies merging it.
After review, we could readjust.

**Comment by jrouzierinverse** [comment]
The milestone being set to PacketFence-5.1 does implies merging for the release of 5.1.0 next week.

**Comment by dwlfrth** [comment]
Review me

**Comment by extrafu** [comment]
@jrouzierinverse Review one last time and merge.

**Comment by jrouzierinverse** [comment]
Looks good to me and it passes the smoke test I was able to go through the basic captive portal authentication workflow.

**Pull request merged**
