### PR TITLE
Issue 5804 - Tar command has options in wrong order

### PR DESCRIPTION
**Pull request by bbs2web**
The tar backup command has the options in the wrong order, so the exclude options are subsequently ignored. I additionally recommend that old backups still be removed when some files change whilst being read.

### CODE REVIEW

**Comment by nqb** [comment]
I will see how we can have this change compatible between Debian 9 and CentOS 7 because they don't use same `tar` version and issue #5804 only affects Debian 9.

**Comment by bbs2web** [comment]
I believe the change may not affect CentOS 7 as this only receives back ported security patches. I did however confirm that the following structure also still works on tar 1.26 as part of CentOS 7.8:
  tar -czf test.gz --exclude a/b/* a;

**Comment by bbs2web** [comment]
I realise my feedback on this was ambiguous. Tar ignoring the 'exclude' options, when they come after the source directory, does not appear to affect CentOS but is referenced in posts from almost 12 years ago. I presume RedHat patch tar, due to it catching so many people out.

ie:  Moving the source folder selection to the end of the command, after the 'exclude' options, worked when I tested this on CentOS 7 and Debian 9.


Create some files:
```
[root@packetfence ~]# for a in a b c d; do mkdir -p $a/$a; touch $a/file $a/$a/file; done;
[root@packetfence ~]# find a b c d -type f;
a/a/file
a/file
b/b/file
b/file
c/c/file
c/file
d/d/file
d/file
```

Then backup with selected sources after 'exclude' options (ie 'exclude' being positional) on CentOS 7 and Debian 9:
```
[root@centos7 ~]# tar -czvf test.tgz --exclude='a/a/*' --exclude='b/b/*' a/* b/* c/* d/*;
a/a/
a/file
b/b/
b/file
c/c/
c/c/file
c/file
d/d/
d/d/file
d/file

=================================================================================

[root@debian9 ~]# tar -czvf test.tgz --exclude='a/a/*' --exclude='b/b/*' a/* b/* c/* d/*;
a/a/
a/file
b/b/
b/file
c/c/
c/c/file
c/file
d/d/
d/d/file
d/file
```

If we however move the source directories before the 'exclude' options, as they currently are in the backup script, it does not skip those files on Debian 9:
```
[root@centos7 ~]# tar -czvf test.tgz a/* b/* c/* d/* --exclude='a/a/*' --exclude='b/b/*';
a/a/
a/file
b/b/
b/file
c/c/
c/c/file
c/file
d/d/
d/d/file
d/file

=================================================================================

[root@debian9 ~]# tar -czvf test.tgz a/* b/* c/* d/* --exclude='a/a/*' --exclude='b/b/*';
a/a/
a/a/file
a/file
b/b/
b/b/file
b/file
c/c/
c/c/file
c/file
d/d/
d/d/file
d/file
```

Sample post from almost 12 years ago:
https://stackoverflow.com/questions/984204/shell-command-to-tar-directory-excluding-certain-files-folders

GNU tar 1.32 documentation specifically lists position sensitive options, which includes 'exclude':
https://www.gnu.org/software/tar/manual/html_node/Position_002dSensitive-Options.html

**Comment by bbs2web** [comment]
Herewith a test on RHEL3 - working as expected:
```
[root@rhel3 root]# for a in a b c d; do mkdir -p $a/$a; touch $a/file $a/$a/file; done;
[root@rhel3 root]# find a b c d -type f;
a/a/file
a/file
b/b/file
b/file
c/c/file
c/file
d/d/file
d/file
[root@rhel3 root]# tar -czvf test.tgz --exclude='a/a/*' --exclude='b/b/*' a/* b/* c/* d/*;
a/a/
a/file
b/b/
b/file
c/c/
c/c/file
c/file
d/d/
d/d/file
d/file
```

**Comment by julsemaan** [comment]
IMO, this should get in, @nqb, is this good for us to merge ?

**Comment by nqb** [comment]
I would like to test on my side.

**Comment by nqb** [comment]
Hello @bbs2web,

Regarding `--exclude` option, it works as it should on CentOS 7 and Debian 9 as you reported.

Regarding change related to cleanup of old archives, I prefered to keep existing backups on disk if `tar` exits with a code different than 0. That's way you're sure to have at least valid backups if tar exits with a code different than 0.
On top of that, if we change it's behavior, it also mean we will not detect same issue you reported. 

Also PR need to be rebased due to a new exclusion added by @lzammit in a98c329487ba0d0e1d64c2b3deb7634c5a698ac0

**Comment by julsemaan** [comment]
@fdurand will take a look and merge today, otherwise it will be for the next release

**Comment by fdurand** [comment]
I am agree with @nqb , we should revert the test on the exist code since the --exclude has been fixed.
@bbs2web can you revert that ? and we will be good to merge.

**Comment by bbs2web** [comment]
Apologies that this took so long...

**Comment by fdurand** [comment]
Thanks for you contribution.

**Pull request merged**
