### PR TITLE
feature/return_count_from_api_search

### LINKED ISSUE #3572: Allow the count to be returned from the search query

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Fixes #3572

Description
===========

Allow the count to be returned from the search query

### CODE REVIEW

**Comment by satkunas** [comment]
@jrouzierinverse please update the openapi specs, documenting this variable. Afterwards we'll be ready to merge.

**Comment by jrouzierinverse** [comment]
I documented the variable in 
- docs/api/spec/components/schemas/base.yaml
- docs/api/spec/components/schemas/search.yaml

They will be merged into the bigger openapi spec after docs/api/spec/generate-openapi-spec.pl is ran.

**Comment by extrafu** [comment]
Bump - what's the status on this one?

**Comment by extrafu** [comment]
Bump.

**Pull request merged**
