### PR TITLE
Email templates improvements

### PR DESCRIPTION
**Pull request by cgx**
# Description
Better responsive email templates using the [mjml framework](https://mjml.io/).

# Impacts
Email templates will be readable on all devices. Yeah!

# NEWS file entries

```
## Enhancements

* improved email templates
```

## Bug Fixes

* PF7.2 Guest Sponsor email CSS: Email is aligned to the right in Outlook (#3097)

### CODE REVIEW

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
The packaging is not complete.

**Comment by cgx** [comment]
I improved the Makefile and added package.json. Should be good to merge.

**Review by julsemaan — COMMENTED** [review]
I'll throw the question we recently asked ourselves about generated templates/stylesheets/javascripties thingies

Should be have the generated HTML email templates not tracked in our git repo and build them in our packaging so that way we're not tracking generated files?

Possible answers I can think of:
- [ ] Yes
- [ ] No
- [ ] Semaan should mind his own business
- [ ] We should turn this into an @lzammit joke

**Comment by cgx** [comment]
Most of these templates were not modified for the last two years. Generating the HTML files every time we package PacketFence didn't sound necessary to me.

**Comment by julsemaan** [comment]
@cgx 

That sounds legit to me, its true that these aren't touched much, so on my side its good to merge

**Comment by extrafu** [comment]
@jrouzierinverse Please merge and update the NEWS file.

**Pull request merged**
