### PR TITLE
Feature/cache for get if index by nas port

### PR DESCRIPTION
**Pull request by fdurand**
## Description

Added a cache for getIfIndexByNasPortId to avoid snmpread on each radius request.
## Impacts

radius
## NEWS file entries

Enhancements
+++++++++++
- Cache the return of getIfIndexByNasPortId for one day to avoid snmpread on each radius request
## Delete branch after merge

YES

### CODE REVIEW

**Comment by julsemaan** [comment]
One word, 

NICE!

**Comment by julsemaan** [comment]
Nothing to say on my side this looks pretty neat.

Did you test one of the switches to make sure it works ?

If yes, I would say to merge it for PF 5.6

Its been too long we don't have this

**Comment by louismunro** [comment]
Two words: "very" .  "nice".

**Comment by fdurand** [comment]
Tested with the 2960C,, on the first radius request the switch object contain the snmp answer, on the second one the snmp answer is empty but i can calculate the ifindex from snmp result in the cache.

**Comment by jrouzierinverse** [comment]
It would be easier to just wrap get the response in pf::Switch instead of creating a pf::Net::SNMP module.

**Pull request merged**
