### PR TITLE
pfcmd pf service status return the status of all managed services

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Return the status of all managed services when we do a "pfcmd service pf status/start/restart"

# Impacts
pf service

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Return the status of each managed services when you ask for the status of the pf service

### CODE REVIEW

**Comment by julsemaan** [comment]
Getting this warning while restarting pf:
```
service|command
PolicyKit daemon disconnected from the bus.
We are no longer a registered authentication agent.
```

**Comment by julsemaan** [comment]
Not sure if it would be possible, but it would be cleaner to have the indentation be consistent in the status output:
```
Service Status
packetfence-api-frontend.service        started
packetfence-config.service      started
packetfence-etcd.service        started
packetfence-fingerbank-collector.service        started
packetfence-haproxy-db.service  stopped
packetfence-haproxy-portal.service      started
packetfence-httpd.aaa.service   started
packetfence-httpd.admin.service started
packetfence-httpd.dispatcher.service    started
packetfence-httpd.parking.service       started
packetfence-httpd.portal.service        started
packetfence-httpd.webservices.service   started
packetfence-iptables.service    started
packetfence-mariadb.service     started
packetfence-netdata.service     started
packetfence-pfdhcp.service      started
packetfence-pfdhcplistener.service      started
packetfence-pfdns.service       started
packetfence-pffilter.service    started
packetfence-pfipset.service     started
packetfence-pfmon.service       started
packetfence-pfperl-api.service  started
packetfence-pfqueue.service     started
packetfence-pfsso.service       started
packetfence-pfstats.service     started
packetfence-radiusd-acct.service        started
packetfence-radiusd-auth.service        started
packetfence-radiusd-cli.service started
packetfence-radiusd-eduroam.service     started
packetfence-radsniff.service    started
packetfence-redis-cache.service started
packetfence-redis_queue.service started
packetfence-tc.service  started
packetfence-winbindd.service    started
```

**Review by julsemaan — COMMENTED** [review]
Code looks good, just a few comments on usability

**Comment by fdurand** [comment]
Is it ok like that ? :
status

**Comment by julsemaan** [comment]
magnifique!

**Comment by julsemaan** [comment]
Omitting news file entry since it was already the case in 8.0

**Pull request merged**
