### PR TITLE
Remove the need to create a pf::SwitchFactory object to create pf::Switch objects

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Since the pf::SwitchFactory->instantiate method does not use any state. It
was just extra overhead to have to create a pf::SwitchFactory object to
instantiate switch objects.
Calling pf::SwitchFactory->instantiate removes the overhead of creating a pf::SwitchFactory object
## Impacts

Any module that uses the pf::SwitchFactory
## NEWS file entries

Enhancements
++++++++++++
- Optimize the create of switch object
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Please review

**Comment by julsemaan** [comment]
Looks good to me. 
Has this been tested ?

**Comment by jrouzierinverse** [comment]
It passed the smoke.t

**Comment by jrouzierinverse** [comment]
Well before it was broken

**Comment by julsemaan** [comment]
I'm more talking about basic testing like instanciating a switch, making sure all services start,...

**Comment by jrouzierinverse** [comment]
Yes those test have been done.

**Comment by jrouzierinverse** [comment]
t/SwitchFactory.t
t/SNMP.t
t/floatingdevice.t
t/network-devices/cisco.t
t/network-devices/threecom.t
t/services.t
t/vlan.t

**Pull request merged**
