### PR TITLE
Fix/netflow adjustements

### LINKED ISSUE #5715: web admin: Netflow on all networks option is missing in Advanced section
**Describe the bug**
If you want to enable "Netflow on all networks" using GUI, you can't because setting is not available in GUI.

**To Reproduce**
1. Go in advanced menu

**Expected behavior**
Netflow on all networks setting in GUI

### PR DESCRIPTION
**Pull request by nqb**
# Description
- `netflow_on_all_network` -> `netflow_on_all_networks`
- improve NetFlow documentation

# Impacts
Defaults PacketFence configuration.

# Issue
fixes #5715 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [x] Document the feature

# NEWS file entries
## Bug Fixes
* `netflow_on_all_networks` can be configured on GUI and take into account

### CODE REVIEW

**Comment by nqb** [comment]
I will add a documentation part to this PR related to bandwidth accounting on inline setup.

**Comment by jrouzierinverse** [comment]
A rename of a parameter should not be done in a +1 patch.
If someone is modified the parameter they will lose that value after using pf-maint.pl.
You would also need to modify go/pfconfigdriver/structs.go in order to take pfacct to read it.

**Comment by nqb** [comment]
>  If someone is modified the parameter they will lose that value after using pf-maint.pl.

I agree with you @jrouzierinverse, updated milestone.

>  You would also need to modify go/pfconfigdriver/structs.go in order to take pfacct to read it.

I updated files under `conf/` directory because `go/pfconfigdriver/structs.go` is good from my point of view.

**Comment by nqb** [comment]
New feature added in 29a7f5e965c6cecc3d3d24f667c2bb48bde889bc: Add the ability to listen to netflow on a different ip address

**Comment by nqb** [comment]
Documentation added, ready for a review @jrouzierinverse.

**Comment by nqb** [comment]
@jrouzierinverse, I missed to add details on `netflow_on_all_networks` setting in documentation. 

I'm not sure to understand the exact purpose of this setting, could you give me some hints ?

**Comment by nqb** [comment]
@jrouzierinverse, could you review and answer my last question ? 

Thanks !

**Comment by extrafu** [comment]
@jrouzierinverse What's the status on this? If all fine, please merge.

**Comment by nqb** [comment]
Latest item added, ready to merge.

**Pull request merged**
