### PR TITLE
exit post installation if manage-images.sh failed

### LINKED ISSUE #7148: Install/update should fail if manage-images.sh fails at any step
**Describe the bug**
I had an upgrade fail in a weird way where manage-images.sh wouldn't be able to pull some of the images (issue with ghcr.io I think) but it did prune images at the end.

We need to make it so that if **any** step of the manage-images.sh fails, it makes the packaging install/upgrade fail immediately. Otherwise you get weird unrelated issues like pfconfig connection failures because that service fails to start.

### PR DESCRIPTION
**Pull request by nqb**
# Description
Exit post installation if manage-images.sh failed

# Impacts
RPM installation

# Issue
fixes #7148 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by julsemaan** [comment]
Anything you need to do before we merge? I reviewed the change and it looks good

**Comment by nqb** [comment]
I'm testing package and I will let you know my results.

**Comment by nqb** [comment]
Works as expected 👌 
After a failure, you got message displayed and no containers are running.

I will just add a comment in `rpm/packetfence.spec` to explain why we added ìf` like this and we can merge.

**Comment by nqb** [comment]
Ready

**Pull request merged**
