### PR TITLE
feature/config-provisioning

### LINKED ISSUE #3554: Add endpoints for Provisioning

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Fixes #3554

Description
===========
Add endpoints for Provisioning

### CODE REVIEW

**Comment by satkunas** [comment]
I'm unable to tell how the `$base_url` from the test unit is used. I assume it's for the `PUT`, `PATCH` and `DELETE` methods. 
- Write tests for  the `PUT`, `PATCH` and `DELETE` methods
- Document all the endpoints in the openapi spec.

**Comment by extrafu** [comment]
Bump - what's the status on this one?

**Comment by jrouzierinverse** [comment]
Additional tests have been added the documentation was updated.

**Comment by extrafu** [comment]
@satkunas Review and merge ASAP please.

**Comment by jrouzierinverse** [comment]
The documentation will auto generated when fix/openapi-doc is merged.

**Comment by extrafu** [comment]
Bump.

**Pull request merged**
