### PR TITLE
Make OS selection explicit in the provisioners

### PR DESCRIPTION
**Pull request by julsemaan**
## Description

Fixes the OS detection in the provisioners
## Impacts

Fixes the OS detection in the provisioners
## NEWS file entries

New Features
++++++++++++

Enhancements
++++++++++++

Bug Fixes
+++++++++
- Make provisioner OS selection always explicit to prevent bad overiding of the default OS for mobileconfig and Android
## Delete branch after merge

YES

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Can you setup an environment that allow us to test this?
It do not see how this fixes the root cause

**Comment by julsemaan** [comment]
Antoine has an environment with provisioners setup.
Other than that you'll have to create your test environment

**Comment by julsemaan** [comment]
To explain what this fixes :
Use this provisioning configuration (in devel)

```
[android]
type=mobileconfig
template=provisioner/android.html
ssid=SANDWICH-AU-PAIN
hidden_ssid=FacketSecure
category=default
description=Android devices

[ios]
type=mobileconfig
#oses=
template=provisioner/mobileconfig.html
category=gaming
ssid=FacketSecure
description=Apple iOS devices
```

Then run : 

```
perl -Ilib -e 'use pf::factory::provisioner; use Data::Dumper; print Dumper(pf::factory::provisioner->new("android")->{oses})'
```

And it'll give you 'Apple ipod, iphone,....' while it should give you Android.

This seems to be caused because it was designed using the default value as a way to set what the module uses as a list of OS.

This breaks because android inherits from mobileconfig and mobileconfig declares it's list of OS in the default section so the default section of android is ignored. This way of assigning the OS seemed like a bad idea to me because if you put an empty list of OS in the configuration then running : 

```
perl -Ilib -e 'use pf::factory::provisioner; use Data::Dumper; print Dumper(pf::factory::provisioner->new("android")->{oses})'
```

will give you a list with an empty value.

Instead of fighing with all this code so close to the release I thought that making it explicit wouldn't hurt. This way if the user wants to add more OS than we initially wanted to he can, and it makes it clearer to debug instead of digging though multiple levels of inheritance that all define a default value.

**Comment by jrouzierinverse** [comment]
This is no longer needed

**Pull request closed without merging**
