### PR TITLE
force halt VM if clean-test is stopped by timeout

### LINKED ISSUE #7621: tests: if clean-test-environment.sh times out, VM could stay up
**Describe the problem**
If Ansible playbooks called by `clean-test-environment.sh` time out, `timeout` command will terminate execution of `clean-test-environment`.

Results: VM are not stopped on the runner because this is done later in the process.

**Mandatory informations**

 * Branch: all
 * Scenario: all
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/4070014193
 
**Symptoms**
How the problem can be identified if it appears again ?

During execution of `clean-test-environment.sh`:

```
make[1]: *** [Makefile:63: clean_pf] Terminated
make: *** [Makefile:119: mac_auth_el8] Terminated
```

### PR DESCRIPTION
**Pull request by nqb**
# Description
fixes #7621

# Impacts
CI tests

# Issue
fixes #7621

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
I increased pipeline timeout in GitLab UI from 3h to 3h15 because we can potentially exceed 180 minutes.

**Comment by nqb** [comment]
Test on a pipeline: https://gitlab.com/inverse-inc/packetfence/-/pipelines/883389932

**Review by JeGoi — APPROVED** [review]
Tout Capté! Tout D'Accord!

**Comment by nqb** [comment]
I made some adjustments to catch all potential errors.
New pipeline: https://gitlab.com/inverse-inc/packetfence/-/pipelines/884399170

**Pull request merged**
