### PR TITLE
fix/7538

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Remove the use of pthread_atfork.

# Issue
Related to #7538

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Bug Fixes
* Remove the use of pthread_atfork (#42)

### CODE REVIEW

**Comment by nqb** [comment]
@jrouzierinverse, could you:

1. Explain in details what issue you are trying to solve (with POSIX::AtFork)
1. Give us more details about your choice here (move from POSIX::AtFork to our own implementation pf::AtFork which seems pretty simple)

The POSIX::AtFork seems to use [XSLoader](https://metacpan.org/module/XSLoader/source), I wonder what is the difference between two implementations. 

Last thing, I think this change is too big to be backported to maintenance.

**Comment by nqb** [comment]
@jrouzierinverse, could you look at my comments ?

**Comment by jrouzierinverse** [comment]
The reason is that [pthread_atfork](https://pubs.opengroup.org/onlinepubs/009604499/functions/pthread_atfork.html) seems to have an issue with deadlocking processes in some scenarios.
So to reduce this chance, I emulated this functionality with this fix.

**Review by nqb — APPROVED** [review]

**Comment by nqb** [comment]
Changes look good. I'm just not sure which impact it has if it goes in maintenance.
I will let @jrouzierinverse take a decision on this.

**Pull request merged**
