### PR TITLE
Change ReturnRole attribute for ArubaOS_CX

### PR DESCRIPTION
**Pull request by abprasa**
# Description
Updating the ReturnRole attribute in ArubaOS_CX switch Modules for dynamic role assignment.

# Impacts
This change will allow dynamic role assignment for Aruba to work as it previously not working with "HP-User-role"
Also removed the old CX.pm as it was duplicate

# NEW Package(s) required
No additional packages are needed. 

# Feature
Changing this will fix dynamic role assignment issue for ArubaOS_CX

# Delete branch after merge
YES 

# Checklist
- [x] Testing the new role with Aruba_CX

### CODE REVIEW

**Comment by satkunas** [comment]
@abprasa Upgrade script needed

**Comment by abprasa** [comment]
> @abprasa Upgrade script needed
@satkunas and @fdurand Done.

**Comment by rvt88** [comment]
Is it possible to apply this change in pf 13.2? I've tried to update the files and restart packetfence without succes. The update script tells me there's nothing to be done

**Comment by abprasa** [comment]
> Is it possible to apply this change in pf 13.2? I've tried to update the files and restart packetfence without succes. The update script tells me there's nothing to be done

@rensvantil 
Yes, I will discussion this internally and we will try see if its possible to easily backport the fix.,
Also, After applying the following changes to the file: /usr/local/pf/lib/pf/Switch/Aruba/ArubaOS_CX_10_x.pm
```
=item returnRoleAttribute
What RADIUS Attribute (usually VSA) should the role returned into.
=cut

sub returnRoleAttribute {
    my ($self) = @_;
    
    return 'Aruba-User-Role';
}
```

You can re-build the httpd.aaa container to apply the changes using the following command:
```
/usr/local/pf/addons/dev-helpers/build-local-container.sh httpd.aaa
bin/pfcmd configreload hard
systemctl restart packetfence-httpd.aaa
```

**Comment by rvt88** [comment]
Thank you, rebuilding the container did the trick and the user role applies fine now.

**Pull request merged**
