### PR TITLE
Update to go1.22.1

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Update to golang 1.22.1

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Update to golang 1.22.1

### CODE REVIEW

**Comment by JeGoi** [comment]
https://gitlab.com/inverse-inc/packetfence/-/pipelines/1246375070
in progress

**Comment by JeGoi** [comment]
@jrouzierinverse Should we also upgrade that line: https://github.com/inverse-inc/packetfence/blob/feature/golang-1.22.1/go/go.mod#L3 ?
Thanks

**Comment by JeGoi** [comment]
Could we go to "golang 1.22.2"?
@fdurand said that this new version is available.

**Comment by jrouzierinverse** [comment]
Let me check

**Comment by jrouzierinverse** [comment]
I updated go1.22.2

**Comment by JeGoi** [comment]
Does this branch need to be rebased?
Some tests have issues https://gitlab.com/inverse-inc/packetfence/-/pipelines/1247543807

**Comment by JeGoi** [comment]
Ok almost done.
Looks like no need to rebase.

**Pull request merged**
