### PR TITLE
Debian package for PacketFence Connector

### PR DESCRIPTION
**Pull request by nqb**
# Description
Build a Debian package for PacketFence Connector.
 
Build is identical to other packetfence packages.

# Impacts
packetfence-pfconnector installation

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [X] Document the feature

# NEWS file entries
## Enhancements
* Debian package for PacketFence Connector

### CODE REVIEW

**Comment by nqb** [comment]
Things to discuss:
- default configuration file provided through packaging (not the case ATM)
- permissions on `pfconnector-client.env` (there is a secret inside it)

Depending on our choices, I will have to adjust a bit the Upgrade section to mention `.dpkg-dist` files.

On my side, I tested:
- installation
- upgrade
- remove
- reinstall

and it works as expected 👌

**Comment by nqb** [comment]
I did adjustments we discussed.

There is one remaining thing to handle: upgrade of a packetfence-pfconnector-remote installed using v12.0.0 instructions. 

I will write a simple script called during postinstallation to perform some cleanup if we detect an old installation.

**Comment by nqb** [comment]
> I will write a simple script called during postinstallation to perform some cleanup if we detect an old installation.

Done. I will test an upgrade from a current installation to packaged version to see if it behaves as expected.

**Comment by nqb** [comment]
Upgrade from 12.0.0 to 12.1.0 tested, it works as expected. I adjust a bit documentation.

Nothing more to do on my side.

**Comment by nqb** [comment]
Thing to adjust before merge:
- [x] Add fingerbank-collector-remote as a dependency to packetfence-pfconnector-remote

=> We need to know version of `fingerbank-collector-remote`

**Comment by julsemaan** [comment]
> => We need to know version of `fingerbank-collector-remote`

It will be fingerbank-collector-remote >= 1.4.1

**Comment by nqb** [comment]
Dependency added. I'm updating tasks on related PR and I will re-run a build to be sure it doesn't break anything.

**Comment by nqb** [comment]
Packages have been built correctly. I think we are good to merge.

**Review by julsemaan — APPROVED** [review]
On my end it looks good, just not sure about the upgrade doc being there but I think we need to address this by moving the connector doc outside of the Linode section anyway so there is no point on blocking the merge for that

**Comment by fdurand** [comment]
I review the change and didn´t find anythig wrong, i am ok to merge.

**Pull request merged**
