### PR TITLE
Add necessary PF adjustements to use Redis with Fingerbank + updating data automatically

### LINKED ISSUE #1217: auto update Fingerbank database using pfmon

### PR DESCRIPTION
**Pull request by julsemaan**
# Description

Add necessary PF adjustements to use Redis with Fingerbank 
Also adds the auto update of the Fingerbank data via pfmon
# Impacts

Fingerprinting, but it will be disabled by default, so nothing.
Update of the Fingerbank data (SQLite DB, p0f map, redis map)
# Fixes

fixes #1217 
# Code / PR Dependencies

PR 9 from fingerbank/perl-client
# Delete branch after merge

YES
# NEWS file entries
## New Features
- Added fingerprint discovery through Redis

### CODE REVIEW

**Comment by julsemaan** [comment]
Review pew-pew-pew

**Comment by jrouzierinverse** [comment]
Is using the raw memory l1_cache is no longer needed?

**Comment by julsemaan** [comment]
Correct, it is no longer needed since I changed the caching strategy since the objects were taking too much place in each process memory

**Comment by rouzier** [comment]
Is the fingerbank part is ready?

**Comment by julsemaan** [comment]
Everything ready for review.

**Comment by julsemaan** [comment]
Ready to merge ?

**Comment by jrouzierinverse** [comment]
Is the fingerbank bank package ready?

**Comment by julsemaan** [comment]
The fingerbank code is also still pending review...

**Comment by jrouzierinverse** [comment]
The code look good will only merge when the fingerbank package is ready

**Comment by dwlfrth** [comment]
Can you rebase

**Comment by extrafu** [comment]
Get some traction on this PR so we can merge it and be ready for v6.

**Comment by julsemaan** [comment]
wibaized

**Comment by jrouzierinverse** [comment]
Where is the fingerbank package???

**Pull request merged**
