### PR TITLE
feature/form-captive-portal

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Allow captiveportal::Form::Authentication to be customize
## NEWS file entries

Enhancements
++++++++++++
- Allow captiveportal::Form::Authentication to be customize
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
The packaging to avoid overriding customizations still needs to be done.

**Comment by fdurand** [comment]
seems to be ok since you are just moving files.

**Comment by extrafu** [comment]
Can this be tested?

**Comment by fdurand** [comment]
Need a rebase

**Comment by jrouzierinverse** [comment]
done

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by fdurand** [comment]
Can you add that in packetfence.spec:
%config(noreplace)      html/captive-portal/lib/captiveportal/Form/Authentication.pm
%config(noreplace)      html/captive-portal/lib/captiveportal/Form/Field/AUP.pm
%config(noreplace)      html/captive-portal/lib/captiveportal/Form/Widget/Field/AUP.pm
and that in packetfence.conffiles:
html/captive-portal/lib/captiveportal/Form/Authentication.pm
html/captive-portal/lib/captiveportal/Form/Field/AUP.pm
html/captive-portal/lib/captiveportal/Form/Widget/Field/AUP.pm

**Comment by jrouzierinverse** [comment]
done

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by fdurand** [comment]
Tested , works, merge

**Pull request merged**
