### PR TITLE
feature/logger-pipe

### LINKED ISSUE #2601: Log::Dispatch is not thread safe
We need to upgrade to the newest version of Log::Dispatch

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
have rlm_perl modules to use /usr/bin/systemd-cat to log to sysloh

Impacts
=======
Radius rlm_perl modules 
Issue
=====
Fixes #2601

Delete branch after merge
=========================
NO

NEWS file entries
=================

Bug Fixes
------------

* rlm_perl modules are now using syslog instead writing directly to the file

### CODE REVIEW

**Comment by fdurand** [comment]
Just tested , looks ok for me , anyone what to test ?

**Comment by extrafu** [comment]
Get rid of the pfsetvlan part.

**Comment by jrouzierinverse** [comment]
Done

**Comment by fdurand** [comment]
It miss the packaging part.

**Comment by jrouzierinverse** [comment]
Ok

**Comment by jrouzierinverse** [comment]
done

**Pull request merged**
