### PR TITLE
feature/profile-advanced-filter

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Profile Advanced Filter

NEWS file entries
=======================
Enhancements
-------------
* Use the condition builder for advanced_filter

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by extrafu** [comment]
@julsemaan Can you quickly review and merge this?

**Comment by jrouzierinverse** [comment]
@satkunas still needs to do his parts.

**Comment by julsemaan** [comment]
I think we can't realistically plan to get this merged today for 10.1 if @satkunas hasn't worked on it yet

**Comment by extrafu** [comment]
IIRC, @satkunas said it would take a couple of minutes to do if the backend is all good.

**Comment by extrafu** [comment]
@jrouzierinverse You have a conflicting file: lib/pf/UnifiedApi/Controller/Config.pm

**Comment by jrouzierinverse** [comment]
Done

**Comment by satkunas** [comment]
@jrouzierinverse  

1. I'm getting the following error with `parse_condition` (`flatten_condition` works as expected): 

Using: `{"condition":"not_contains(action, \"a\") && not_contains(action, \"b\")"}`

```May 29 17:05:35 packetfence packetfence: pfperl-api(10198) WARN: Use of inherited AUTOLOAD for non-method pf::UnifiedApi::Controller::Config::parse_condition_string() is deprecated at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 1329.
 (pf::UnifiedApi::Controller::Config::parse_condition)
May 29 17:05:35 packetfence packetfence: pfperl-api(10198) ERROR: Undefined subroutine &pf::UnifiedApi::Controller::Config::parse_condition_string called at /usr/share/perl5/vendor_perl/Mojolicious.pm line 147.
```


2. In the meta for config/connection_profiles, the `advanced_filter` (profiles) does not match that from `condition` (filter engines). The `allowed` is empty, and the nesting of `properties` has an issue - it's missing the `item` parent.

3. The current profiles, without any def in the conf file show the following. If an item is defined it requires the missing `field`, `value` and `values` keys, same as filter engines.
```
# /usr/local/pf/sbin/pfperl-api get -M GET "/api/v1/config/connection_profile/default-copy"| jq .item.advanced_filter
{
  "op": "and"
}
```

**Comment by satkunas** [comment]
@jrouzierinverse front-end changes are done. It should work once you address the issues above.

**Comment by jrouzierinverse** [comment]
I fixed issues with the backend let me know if you have any additional issues.

**Review by cgx — APPROVED** [review]
JavaScript part looks good.

**Comment by julsemaan** [comment]
Is the backend code retrocompatible with an existing advanced filter as-is or does it require to define the top_op or something like this ?

**Comment by jrouzierinverse** [comment]
There would be a need for a retrofit.

**Comment by julsemaan** [comment]
> There would be a need for a retrofit.

Next question, is the GUI handling that retrofit gracefully ?

**Comment by satkunas** [comment]
@julsemaan the GUI no longer supports the old advanced filter format. The back end will need to recompose it for the GUI.

**Comment by jrouzierinverse** [comment]
The GUI should handle the retrofit just fine.
I am assuming if there is no top op it would be either 'and', 'not_and'.
The GUI should be work just fine.

**Comment by extrafu** [comment]
@jrouzierinverse / @julsemaan / @satkunas Get together and nail the last items in this, we need to merge once for all.

**Comment by julsemaan** [comment]
@satkunas, you will need to rebase this and we should be good for merging

**Comment by satkunas** [comment]
@julsemaan rebased

**Pull request merged**
