### PR TITLE
Feature/net snmp perl

### PR DESCRIPTION
**Pull request by mullagain**
Added pf::snmp module to use SNMP.pm from net-snmp instead of Net::SNMP. SNMP.pm has huge performance gains over Net::SNMP. I have created an initial connectRead to replace the method in Switch.pm and get/get_tables methods to make read requests look the same as Net::SNMP.

This is also a Moose based class.

Future support will include set requests, traps, etc.

For review, discussion and merge.

### CODE REVIEW

**Comment by dwlfrth** [comment]
What's my status ?

**Comment by mullagain** [comment]
What do you mean?

**Comment by dwlfrth** [comment]
Asking if it is still accurate, regarding the comment in pull/210.

**Comment by louismunro** [comment]
I actually like this stuff. 
While we aim to no longer use SNMP for authentication in  PF 6, the performance gains might be worth it. I will keep this around until we have some time to benchmark it.

**Comment by louismunro** [comment]
Sorry. This was a good idea, but we went in a different direction in the end.

**Pull request closed without merging**
