### PR TITLE
Allow multiple access levels in source admin rules

### LINKED ISSUE #5440: Impossible to set multiple access level in administration rule
**Describe the bug**
In the previous admin we used to be able to set multiple access level rules. The new admin needs to support this as well.

**To Reproduce**
1. Go in an LDAP/AD source
2. Create an administration rule
3. Attempt to set the "Access level"
4. Try to put multiple values in that field

**Expected behavior**
In a single "Access level" action, we should be able to set multiple access levels

### PR DESCRIPTION
**Pull request by satkunas**
# Description
Allow multiple choices in `set_access_level` of Authentication Sources Administratin Rule Actions.

# Impacts
n/a 

# Issue
fixes #5440

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

## Bug Fixes
* Impossible to set multiple access level in administration rule (#5440)

### CODE REVIEW

**Comment by satkunas** [comment]
@jrouzierinverse I've made the necessary changes to the front-end.

The array is saving properly in the `.conf`:
```
[LDAP rule Test]
action0=set_access_level=Node Manager,User Manager
  match=all
class=administration
```

However, I need you to adjust the API output, as the current response is a flat string and needs to be changed to an array.

```
# /usr/local/pf/sbin/pfperl-api get -M GET "/api/v1/config/source/LDAP"|jq '.item.administration_rules[0].actions[0]'
{
  "type": "set_access_level",
  "value": "Node Manager,User Manager"
}
```

**Comment by jrouzierinverse** [comment]
Done

**Comment by satkunas** [comment]
@jrouzierinverse no change

```
# /usr/local/pf/sbin/pfperl-api get -M GET "/api/v1/config/source/LDAP"|jq '.item.administration_rules[0].actions[0]'
{
  "type": "set_access_level",
  "value": "Node Manager,User Manager"
}
```

**Comment by jrouzierinverse** [comment]
Can you check if you are on the right branch or if your branch is up to date?
As I am seeing the right output.
Check if you are on the right branch and commit HEAD.
If you are then send me your aiuthetication.conf so I can see what could be the problem.
```
 /usr/local/pf/sbin/pfperl-api get -M GET "/api/v1/config/source/file1"| jq '.item.administration_rules[0].actions[0]'
{
  "type": "set_access_level",
  "value": [
    "User Manager",
    "Violation Manager"
  ]
}
```

**Comment by julsemaan** [comment]
@satkunas, can you check what @jrouzierinverse posted to see if this allows you to fix the issue

**Comment by satkunas** [comment]
@jrouzierinverse @julsemaan my bad, it's good.

**Comment by extrafu** [comment]
@jrouzierinverse Review and merge if all is fine. Don't forget to update the NEWS file.

**Pull request merged**
