### PR TITLE
fix/5659

### LINKED ISSUE #5659: Network Interface Configuration Issue
**Describe the bug**

Happen if you use the HWADDR parameter to map the interface with a specific name.

When you have a network interface configured like that:

```
DEVICE=em1
ONBOOT=yes
HWADDR=00:50:56:20:0F:85
TYPE=Ethernet
BOOTPROTO=none
IPADDR=10.255.204.90
NETMASK=255.255.252.0
DNS1=10.255.232.204
DNS2=10.255.232.216
```

and when you go in the configurator and set the interface as management (or reg/isol) then the configuration become like that:

```
DEVICE=em1
ONBOOT=yes
TYPE=Ethernet
BOOTPROTO=none
IPADDR=10.255.204.90
NETMASK=255.255.252.0
DNS1=10.255.232.204
DNS2=10.255.232.216
```
and you lost the HWADDR configuration parameter.
Then if you rebbot the server than you will lost the network access.

We should at least fetch the existing parameters (like only the one we doesn't changre from the admin gui) and merge them with the new ones.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Do not override user defined values in the interface file for centos.

NEWS file entries
=======================
Bug Fixes
-------------
* Don't override user defined values in the interface file for centos.

Issue
=====
fixes #5659

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
This seems like it doesn't enforce NM_CONTROLLED=no like we currently do (this ensures that although the NetworkManager is running, it doesn't interfere with our interfaces)

**Comment by julsemaan** [comment]
I think we should adopt a strategy of tracking which configuration items we don't want to touch

Otherwise we may leave incompatible configuration in place

**Comment by jrouzierinverse** [comment]
It finds all the variables that were not in the new config from the old config and appends them to the new config.
So the case of 'NM_CONTROLLED=no' since it is in the new config.

**Comment by julsemaan** [comment]
> It finds all the variables that were not in the new config from the old config and appends them to the new config.
> So the case of 'NM_CONTROLLED=no' since it is in the new config.

doesn't seem to work

I modified my interface to use:
```
DEVICE=eth0
HWADDR=
ONBOOT=yes
BOOTPROTO=static
NM_CONTROLLED=yes
IPADDR=172.20.20.109
NETMASK=255.255.0.0
TEST=hello


IPV6INIT=yes
IPV6ADDR=fd9b:46e6:e651:0000:020c:29ff:feda:b089/64
```

And then in the admin, I saved it and it stayed with NM_CONTROLLED=yes

**Comment by jrouzierinverse** [comment]
Did you restart your pfperl-api? It works on my side.

**Comment by julsemaan** [comment]
I just retried ensuring that pfperl-api was restarted.

Using the configuration I put above, the setting `NM_CONTROLLED=yes` stays in place although it should have been replaced by `NM_CONTROLLED=no`

**Comment by julsemaan** [comment]
Also, when I removed my IPv6 address in the admin, it left the 2 IPV6 directives in the file

**Comment by jrouzierinverse** [comment]
I did see the issue with the IPV6 directives in the file.
However, I am not seeing the NM_CONTROLLED=yes issue.
Can you paste the before and after of the network config here, please?

**Comment by jrouzierinverse** [comment]
Also, I just pushed the fix for the IPV6 directives

**Comment by julsemaan** [comment]
> I did see the issue with the IPV6 directives in the file.
> However, I am not seeing the NM_CONTROLLED=yes issue.
> Can you paste the before and after of the network config here, please?

Config wasn't changing due to a permission issue for a file in var/ for the NM_CONTROLLED test I was doing

I tested again against your latest commit and all looks good on my end now

**Pull request merged**
