### PR TITLE
fix(EXOS): disable SNMP query on CLI login

### PR DESCRIPTION
**Pull request by nqb**
# Description
Disable SNMP query on CLI login

# Impacts
EXOS switch module

# Issue

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Disable SNMP query on CLI login for EXOS switches

### CODE REVIEW

**Comment by nqb** [comment]
This fix prevent a SNMP query on switch when PF receives a RADIUS request for a CLI access.

It looks like it cause following error only when dealing with CLI RADIUS request:
```
Mar 16 10:19:50 packetfence2 packetfence_httpd.aaa[497425]: httpd.aaa(497425) ERROR: [mac:[undef]] radius switch access failed with error: Recursive data structure detected at this point in the structure: 'switch._sessionRead._pdu._security'. Cannot flatten recursive structures. at /usr/local/pf/lib_perl/lib/perl5/Hash/Flatten.pm line 205.
(pf::api::radius_switch_access)
```

**Comment by julsemaan** [comment]
@nqb, the code looks good

Please confirm this has been tested either in lab or with a customer and we're good to merge this and put it in maintenance

**Comment by nqb** [comment]
@julsemaan, I will provide an adjustment because it has been tested and cause an issue.

Once I got a positive feedback from customer that new code is working, I will add a comment here.

**Comment by nqb** [comment]
@julsemaan, you can review and merge.

**Pull request merged**
