### PR TITLE
Add clone method to connection profiles

### LINKED ISSUE #2809: Admin: Allow to clone a connection profile
Like other configuration resources, we should be able to clone connection profiles.

### PR DESCRIPTION
**Pull request by satkunas**
# Description
Adds clone functionality to Admin > Connection Profiles

# Impacts
Connection Profiles Flow

# Issue
Fixes #2809

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Added Cloning in Connection Profiles

### CODE REVIEW

**Comment by julsemaan** [comment]
Does cloning a connection profile using this code also makes sure that the templates in html/captive-portal/profile-templates/$NAME_OF_SRC_PROFILE are used for the new profile ?

**Comment by satkunas** [comment]
@julsemaan captive-portal templates are included with the clone in https://github.com/inverse-inc/packetfence/pull/2814/commits/a5c62ef267f0972f24d2759b73f5fef53c630a9f

**Comment by julsemaan** [comment]
@satkunas 
image

I'll take another quick look and merge that

**Comment by extrafu** [comment]
^--- looks like a 60 years old emaciated @lzammit

**Pull request merged**
