### PR TITLE
Fix for multiple XSS vulnerabilities

### LINKED ISSUE #720: Admin panel: multiple XSS vulnerabilities. 1 unauthenticated.
There are several XSS vulnerabilities on the admin panel. Most notably:
1. An unregistered or registered client sets their hostname as HTML script tags containing a Javascript alert with text "XSS Found"
2. The host shows up under "Nodes" once served by DHCP. The script tags are correctly escaped in the list.
3. Once clicking on the MAC address of this host, a JavaScript alert message appears with text "XSS Found".

Similar XSS happens on other pages, such as violations, where a violation can be named the same as above and will cause a JS popup once the "delete" button is pressed. This is probably rampant throughout other admin menus also.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Fixed #720

This was done by having the Template Toolkit by default filter all output using the html filter (via Template::AutoFilter)
All safe output is replaced with the none filter
## Impacts

The template rendering in the admin gui
## NEWS file entries

New Features
++++++++++++

Enhancements
++++++++++++

Bug Fixes
+++++++++
- Fix multiple xss vulnerabilities in the admin gui
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Review me please

**Comment by jrouzierinverse** [comment]
In order to test you would need to install Template::AutoFilter and upgrade your Template::View::TT

**Comment by extrafu** [comment]
Packaging _must_ be included as part of this work. So make sure you also provide Debian, Ubuntu and RHEL packages for Template::AutoFilter and the update of Template::View::TT.

**Comment by jrouzierinverse** [comment]
I am working with Fabrice to create the packages

**Comment by julsemaan** [comment]
Reported issue is ok now. Tried in violations, switch, users and no other vulnerability found

**Comment by julsemaan** [comment]
As for the code it's fine

**Comment by jrouzierinverse** [comment]
I will work with Fabrice on Tuesday to settle the new dependencies

**Comment by louismunro** [comment]
Can you rebase please?

**Comment by jrouzierinverse** [comment]
Ok

**Comment by jrouzierinverse** [comment]
Done

**Pull request merged**
