### PR TITLE
IBM provisioner removal

### PR DESCRIPTION
**Pull request by nqb**
# Description
Remove IBM provisioner.

# Impacts
Provisioners
Web admin

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
I rebuilt all Docker images and I didn't see any complaints.

**Review by satkunas — COMMENTED** [review]
UI changes look good

**Comment by jrouzierinverse** [comment]
There is no script that removes the IBM provisioners from the conf/provisioning.conf and conf/profiles.conf

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
There is no script that removes the IBM provisioners from the conf/provisioning.conf and conf/profiles.conf

**Comment by nqb** [comment]
Upgrade script has been already merged.

**Pull request merged**
