### PR TITLE
Feature/pfcron container

### PR DESCRIPTION
**Pull request by JeGoi**
# Description
Add pfcron in a container

# Impacts
pfcron will be in a container

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by julsemaan** [comment]
Just to make sure, you did validate the tasks were able to run correctly?
(Including the ones that get done via a call to pfperl-api)

**Comment by JeGoi** [comment]
Tests done against api and DB. It looks fine.
Thanks @jrouzierinverse and @julsemaan

**Comment by jrouzierinverse** [comment]
Is the fingerbank files shared among the containers?

**Comment by julsemaan** [comment]
> Is the fingerbank files shared among the containers?

Not unless its explicitly exposed (its not in this case)

Looks like the Fingerbank DB update in pfcron goes through the httpd.webservices so that is the one that would require the mount point `-v /usr/local/fingerbank/db:/usr/local/fingerbank/db` from a quick code read. @jrouzierinverse, I'll let you confirm my analysis

**Comment by jrouzierinverse** [comment]
You are correct httpd.webservices need access to the fingerbank db

**Comment by JeGoi** [comment]
It looks that is a default:
https://github.com/inverse-inc/packetfence/blob/devel/containers/systemd-service#L15

**Comment by julsemaan** [comment]
@JeGoi, please rebase and it should be ready to merge

**Comment by JeGoi** [comment]
@julsemaan Rebase on devel is done.

**Pull request merged**
