### PR TITLE
Fix/2112 monit checks

### LINKED ISSUE #2112: monitoring: Monit checks not working anymore with systemd
Previously based on pid files, monit process checks does not appear to be working anymore with systemd integration

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description
Adjusted Monit checks to use "MATCHING" rather than PID

# Impacts
Monit monitoring

# Issue
fixes #2112 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* monitoring: Monit checks not working anymore with systemd (#2112)

### CODE REVIEW

**Comment by dwlfrth** [comment]
Please review. Need test with new PacketFence version

**Comment by julsemaan** [comment]
It looks good but I haven't tested it though.

Shall we merge and test or test and merge ?

**Comment by dwlfrth** [comment]
I'd say test and merge.
No impact on build or whatnot... no impact on code unless you activate Monit

**Comment by dwlfrth** [comment]
I mean merge and test from build ;)

**Pull request merged**
