### PR TITLE
Replace prototype.js by jQuery

### PR DESCRIPTION
**Pull request by cgx**
Phasing out prototype.js and replacing it by jQuery as it's substantially more popular. 

Will ease the integration of external JavaScript plugins that rely on jQuery.

Not required for release 4.5 (must consult @dwlfrth).

### CODE REVIEW

**Comment by dwlfrth** [comment]
Tested before pull request and was working.
Unless big modifications between test and pull-request, ready to merge.

**Comment by dwlfrth** [comment]
Tested and working on default workflow (login in and being redirected...)

**Comment by louismunro** [comment]
Please rebase.

**Comment by dwlfrth** [comment]
Why is the milestone modified ?
I have it working at couple deployment and working pretty fine.

**Comment by dwlfrth** [comment]
Also, what's the "reviewed - need rework" ?

**Comment by julsemaan** [comment]
Most probably because of the needed rebase but I agree with @dwlfrth that this should go in 5.4

**Comment by cgx** [comment]
I'll create a new pull request.

**Pull request closed without merging**
