### PR TITLE
Change paths used in documentation (images and includes)

### PR DESCRIPTION
**Pull request by nqb**
# Description
Change paths used in documentation (images and includes)

# Impacts
- Embedded documentation with web admin
- Documentation published on PacketFence.org
- Source documentation on Github

# Delete branch after merge
YES

### CODE REVIEW

**Comment by extrafu** [comment]
I defer to @cgx to review and merge that one.

**Comment by nqb** [comment]
@cgx : could you review my changes ?

Please note following informations : 
* I modify `Makefile` to send images in another location for `pfappserver` : my commit message was unclear
* With current configuration, Github engine doesn't display correctly images on asciidoc files because it don't know `imagesdir` parameter (use by `asciidoctor` when we make PDF and HTML docs).

**Comment by nqb** [comment]
Test with packetfence-8.0.9-0.201806260000.el7.noarch, embedded doc with `pfappserver` works.

**Comment by cgx** [comment]
You'll need to adapt the [debian packaging](https://github.com/inverse-inc/packetfence/blob/devel/debian/rules#L161-L168).

**Comment by cgx** [comment]
Ready to merge?

**Comment by nqb** [comment]
I'm testing builds to merge asap.

**Comment by nqb** [comment]
@cgx : we can merge ! We also need to update our release procedure.

**Pull request merged**
