### PR TITLE
feature/golang-1.16

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Upgrade to golang 1.16

NEWS file entries
=======================
Enhancements
-------------
* Upgrade to golang 1.16.3

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by nqb** [comment]
I run a pipeline here: https://gitlab.com/inverse-inc/packetfence/-/pipelines/296655737
* Docker image to run builds has Golang 1.16.3

EDIT: new pipeline [here ](https://gitlab.com/inverse-inc/packetfence/-/pipelines/296663560) to build packages with new image. it will run all tests.

**Comment by nqb** [comment]
All tests (Perl, Golang and integration tests) passed correctly on CentOS 7.

**Comment by nqb** [comment]
Same tests in progress for the new version: https://gitlab.com/inverse-inc/packetfence/-/pipelines/302760386

Would be nice to merge it if everything is ok before I started to work on build environment for Debian 11 and RHEL8.

**Comment by nqb** [comment]
Every tests passed 👌

**Comment by jrouzierinverse** [comment]
I would prefer to merge this now and not the last minute.
So we can test if the new version of Golang causes as early as possible.
Or we could even just move to 1.15.12
https://golang.org/doc/devel/release.html#go1.15.minor

**Comment by nqb** [comment]
I suggest we keep 1.16.4 as we will release a major version too (v11).

**Pull request merged**
