### PR TITLE
Instructions to override CSS definitions on captive portal

### LINKED ISSUE #7278: PF12 - Not able to edit styles.css or logo for Captive Portal
**Describe the bug**
I'm not able to upload styles.css and logo on the captive portal to set my visual identity.

**To Reproduce**
1. Go to connection profile configuration
2. Change the logo path on the profile
3. Upload the logo.png and styles.css to path /usr/local/pf/html/common/

**Expected behavior**
I should be able to see the logo and the portal with the colors of my company visual identity
Can be created a path on server for html/common folder and mount it on docker image for the portal ( httpd.portal )?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge, Firefox
 - Version: Edge-106.0.1370.37, Firefox-105.0.3

### PR DESCRIPTION
**Pull request by nqb**
# Description
Instructions to override CSS definitions on captive portal

# Issue
fixes #7278

# Delete branch after merge
YES

### CODE REVIEW

**Comment by PureOxygen-Dev** [comment]
Hi @nqb and @julsemaan,

Needed to update this information

The <style> tag is there but totally ignored.

How it is rendered in the browser

image

How the Style Tag should make it look

image

Here is the evidence that the style tag is there

image

**Comment by nqb** [comment]
@RHDHV-simon-sutcliffe, did you disable CSP headers on captive portal and restart service as mentioned ?

**Comment by PureOxygen-Dev** [comment]
> @RHDHV-simon-sutcliffe, did you disable CSP headers on captive portal and restart service as mentioned?

That was it, sorry I forgot that as I got dragged into various meetings.  Problem solved.  Nice workaround.

**Comment by PureOxygen-Dev** [comment]
Good Morning @nqb I noticed one small error in your text, you state

"Then you need to restart `httpd.portal` service."

But Packetfence gets you to restart the api-frontend

image

**Comment by nqb** [comment]
@RHDHV-simon-sutcliffe,

I agree that we don't have httpd.portal button on this menu but we will not solve this issue on this PR.

@julsemaan, if you are happy with that PR, could you merge it ? I will backport to maintenance/12.0 and rebuild doc on website.

**Comment by PureOxygen-Dev** [comment]
@nqb I think I might have been unclear sorry.  When I tested this there appeared to be no need to restart the httpd.portal to affect the toggle switch affect.   I only mention it as you call it out explicitly within the text as something that is needed but my feeling was it is not.

Hope this clarifies it.

**Comment by nqb** [comment]
I will backport to maintenance/12.0 and rebuild doc on website.

**Pull request merged**
