### PR TITLE
Renamed metascan to Metadefender

### LINKED ISSUE #1445: metascan is now know as Metadefender
Make sure metascan is now referenced as Metadefender
- in code
- in doc
- in configuration
- trigger type needs modification

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description

OPSWAT metascan is now known as Metadefender. Adjusting integration
# Impacts
- Metadefender integration
- violation triggering (both with or without using "metadefender" (previously "metascan") trigger type)
- configuration
# Issue

fixes #1445 
# Delete branch after merge

YES
# UPGRADE file entries

pf.conf configuration parameters
- 'metascan' configuration section is now 'metadefender', which means that;
- 'metascan.api_key' is now 'metadefender.api_key'
- 'metascan.query_url_hash' is now 'metadefender.query_url_hash'
  also, 
- the value of 'metadefender.query_url_hash' changed from "https://hashlookup.metascan-online.com/v2/hash/" to "https://hashlookup.metadefender.com/v2/hash/"

violations.conf
- 'metascan' trigger type changed to 'metadefender'

### CODE REVIEW

**Comment by louismunro** [comment]
Please rebase.

**Comment by louismunro** [comment]
Reeebaaase meeeee...
I think we're good otherwise.
I see no reason not to merge apart from that.

**Comment by dwlfrth** [comment]
Ribayzed

**Comment by louismunro** [comment]
Mergèd.

**Pull request merged**
