### PR TITLE
Track in local git repo the configuration directory

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Autocommit in the local git repo when a change is made in the /usr/local/pf/conf directory.

# Impacts
No

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Track configuration change in local git repo

### CODE REVIEW

**Comment by nqb** [comment]
We should use directly [etckeeper](https://etckeeper.branchable.com/) in place of having your own service and code.

**Comment by fdurand** [comment]
If you want to use etckeeper then you need to manage a configuration file, a service ...
This is directly managed by systemd and there is no package dependency.

**Comment by jrouzierinverse** [comment]
Need to add a .gitignore to avoid saving things like vim temp files.

**Comment by fdurand** [comment]
Bump

**Pull request merged**
