### PR TITLE
Fix the task counters not in sync when a task expires

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Task counters are not in sync when a task expires
## Impacts

pfqueue
## NEWS file entries

Bug Fixes
+++++++++
- Fix task counters out of sync when a task expires
## Delete branch after merge

NO

### CODE REVIEW

**Comment by julsemaan** [comment]
The miss count should be shown in the admin so all the infos is there when we troubleshoot

**Comment by jrouzierinverse** [comment]
Already does

**Comment by julsemaan** [comment]
I don't see it.

Is it showing where there isn't any miss ?

Would be useful to have it since its an odd behavior to not have the column

**Comment by jrouzierinverse** [comment]
It will only display it when there are missed counters

**Comment by louismunro** [comment]
That is not very intuitive to the user.
Could we make that show 0 if there aren't any?

**Comment by julsemaan** [comment]
Is it hard to add it because a user would expect the column to be there with a count of 0

**Comment by jrouzierinverse** [comment]
Since this is "dynamic" information prepopulating would be difficult/pain.
I will change the display to split the display of the task counters and miss counters.

**Comment by jrouzierinverse** [comment]
This has been done.

**Comment by julsemaan** [comment]
When there are no miss count counters to show it should say it (following the same principles as the portal profiles) instead of showing an empty table.

**Comment by jrouzierinverse** [comment]
Done

**Pull request merged**
