### PR TITLE
feature/auto-generate-openapi-dal-crud

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========

Auto generate OpenAPI spec from the pfunified_api routes

### CODE REVIEW

**Comment by extrafu** [comment]
What's the status on this PR?

**Comment by julsemaan** [comment]
@jrouzierinverse 

Are we aiming for 8.0 for this ?

It has no tags nor milestone right now, we need to know what to do with this

**Comment by jrouzierinverse** [comment]
I will get this out for the release.

**Comment by jrouzierinverse** [comment]
Please review

**Pull request merged**
