### PR TITLE
Add email html template FR/EN

### PR DESCRIPTION
**Pull request by whitx**
# Description

Redefine email template, to use HTML emails instead of plaintext.
# Impacts

This should not have impact on the PacketFence,  try to open the html email with different client/webmail/device would be the best testing.
# Delete branch after merge

YES
# NEWS file entries
## New Features
- Email are now in HTML format
## Enhancements
- Redefine email to be HTML instead of plaintext, email are now responsive and better looking.
- Added French version of the templates

Used #509 as a ref for the templates.

### CODE REVIEW

**Comment by extrafu** [comment]
I guess you should use a tab-stop of 2 spaces, 8 is pure insanity!

**Comment by louismunro** [comment]
That's cause he's french. 
8 is metric for 2.

**Comment by whitx** [comment]
biling
preregadmin
preregsponsor

Email preview.

**Comment by dwlfrth** [comment]
I think we should avoid any "personal' formula in these kind of email. 
No "we", "nous" i mean...
ie: We have created you an account to access our network  -> An account has been created so you can access the network
ie: Nous vous avons créé un compte... -> Un compte a été créé pour vous permettre....

**Comment by louismunro** [comment]
Mistakes were made…
(It’s called the impersonal voice. Great way to absolve anyone from anything).  

## 

LM

**Comment by jrouzierinverse** [comment]
Mistakes were made but not by me

**Pull request merged**
