### PR TITLE
feature/network-description

### LINKED ISSUE #5826: Networks: allow to specify a description
**Is your feature request related to a problem? Please describe.**
When you have to deal with a lot of networks, it would be nice to add a description on each network to identify them.

**Describe the solution you'd like**
Having a description field on each network.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
New description field for network

Impacts
=======
network configuration

NEWS file entries
=======================
Enhancements
-------------
* Description Field for networks

Issue
=====
Fixes #5826

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Review by nqb — CHANGES_REQUESTED** [review]
Now we are able to add description on L2 networks and also on Routed networks using Description field.

### Description field on interfaces

Description field is also available on network interfaces:

Capture d’écran de 2021-01-13 09-49-34

I'm not sure it's intended because backend doesn't handle this. I mean we don't have a description fields for interfaces. 

And we got frontend errors when editing an interface:
Capture d’écran de 2021-01-13 09-53-24


### Unexpected behavior

If I do following actions:
- create an interface with a type "inline L2" (without description)
- edit L2 network to add a description

I see two API messages:
- config/interface/172.17.6.0: Interface 172.17.6.0 doesn't exist
- config/l2_network/172.17.6.0: Settings updated

with 172.17.6.0 my new network.

Same behavior if I edit interface.

**Comment by nqb** [comment]
@jrouzierinverse and @satkunas,

I just tested code and my previous comment is still valid.

**Comment by nqb** [comment]
Still issues reported in my first comment.

**Comment by extrafu** [comment]
@nqb retest

**Comment by nqb** [comment]
@extrafu, code is not ready according to @jrouzierinverse.

**Comment by extrafu** [comment]
@nqb So it should be specified here.

**Comment by nqb** [comment]
@jrouzierinverse, can I test it ?

**Comment by jrouzierinverse** [comment]
I am waiting on some feedback from @satkunas

**Comment by jrouzierinverse** [comment]
Everything seems to be working.

**Review by nqb — CHANGES_REQUESTED** [review]
### [FIXED] Place of description field for L3 networks

When editing a L3 network, Description field is located between network and netmask fields which I find contre-intuitive. I suggest following order

1. network
2. netmask
3. description

Capture d’écran de 2021-03-26 08-40-51


### Adding a description to an already created network

I created an isolation interface during configurator with IP 172.17.3.2. When I edited L2 network  (172.17.3.0) from GUI to add a description, I got following error from API:

```
config/interface/172.17.3.0: Interface 172.17.3.0 doesn't exist
config/l2_network/172.17.3.0: Settings updated
```
=> Description is updated, saved in `networks.conf` but we got an error.

**Comment by nqb** [comment]
Error reported by API is logged like this:

```
Mar 26 07:49:50 pfdeb9dev packetfence: pfperl-api(15938) WARN: Problem trying to run command: LANG=C sudo ip -4 -o link show 172.17.3.0 called from (eval). Child exited with non-zero value 1 (pf::util::pf_run) │
```

If I run command by hand:
```console
# sudo ip -4 -o link show 172.17.3.0
Device "172.17.3.0" does not exist.
```

According to `man ip link`, this command seems to be used to display informations **on device** not on networks.

**Comment by nqb** [comment]
Error mentioned above is a bug not related to this PR. I will merge this one and open a dedicated bug.

**Pull request merged**
