### PR TITLE
Feature/multitenant api reports

### PR DESCRIPTION
**Pull request by satkunas**
# Description
Add existing reports to multitenant API
Add test units for implemented API endpoints

# Impacts
Heavy queries, reports may consume large resources with production dB's.

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Added reporting to API

### CODE REVIEW

**Comment by extrafu** [comment]
@jrouzierinverse and @julsemaan Please review and give feedback to @satkunas so he can move on with new API work.

**Comment by julsemaan** [comment]
Looks good to me as far as I know, @jrouzierinverse can probably just confirm the routes declaration in UnifiedAPI.pm to make sure the framework was used correctly and then its good to merge

**Comment by jrouzierinverse** [comment]
To avoid installing additional routes add ``` resource_v2a   => {}``` to each reporting entry.
For example instead of
```perl
{ controller => 'reports', collection_v2a => { get => 'os' },  id_key => 'report_id', path => '/reports/os' },
```
It should read as
```perl
{ controller => 'reports', collection_v2a => { get => 'os' }, resource_v2a   => {},  id_key => 'report_id', path => '/reports/os' },
```
Also please update the OpenAPI documentation at docs/api/spec/paths/

You can find the format of OpenAPI here.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

If you have questions on how to update you can ask @julsemaan

**Review by jrouzierinverse — DISMISSED** [review]
Please update requested items if you any questions please let me know.

**Comment by satkunas** [comment]
@jrouzierinverse requested change made in https://github.com/inverse-inc/packetfence/pull/2885/commits/58e7db6897fe65a188a37a429e15638df9f2764f

**Comment by jrouzierinverse** [comment]
Missing documentation.

**Pull request merged**
