### PR TITLE
Add exportable backup for PF

### PR DESCRIPTION
**Pull request by JeGoi**
# Description
This will create exportable backup for packetfence.
It combines the current backup and export script in one

# Impacts
It will create exportable backup for packetfence.
```
[root@el8_standalone pf]# ls -la /root/backup/
total 1086028
drwxr-xr-x. 2 root root      4096 Sep 26 13:04 .
dr-xr-x---. 7 root root      4096 Sep 26 13:03 ..
-rw-r--r--  1 root root 184624564 Sep 26 12:58 packetfence-exportable-backup-2024-09-26_12h57.tgz
-rw-r--r--  1 root root 184631925 Sep 26 13:04 packetfence-exportable-backup-2024-09-26_13h03.tgz
```

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Creating exportable backup

### CODE REVIEW

**Comment by JeGoi** [comment]
No ready test is failing.

**Comment by JeGoi** [comment]
@lzammit is is ready for review. It passes the unit tests.
Doc is included

**Comment by E-Thang** [comment]
What does this change mean for importing a standalone host from 14.0 to 14.1? I was wanting to import a standalone 14.0 export to a standalone 14.1 host, but the file name change made that not possible. It might work if I edit the exported file and rename the packetfence-files* to packetfence-conf*

**Comment by JeGoi** [comment]
Thanks and Good point, let's fix it now.

**Comment by JeGoi** [comment]
Quick and dirty Fix:  https://github.com/inverse-inc/packetfence/commit/f15703fc4ffd4ac3b803e6d5c1b6f4ad64c6696b
@E-ThanG thanks again.

**Pull request merged**
