### PR TITLE
Feature/export csv

### PR DESCRIPTION
**Pull request by julsemaan**
# Description

Adds CSV export to node and user searches
# Impacts

Nodes and users search
# NEW Package(s) required

perl-Catalyst-View-CSV
# Delete branch after merge

YES
# NEWS file entries
## Enhancements
- Added option to export nodes and users within the web administration interface

### CODE REVIEW

**Comment by julsemaan** [comment]
Ready for review

**Comment by jrouzierinverse** [comment]
Have you tested this with WRIX exporting?

**Comment by julsemaan** [comment]
I just didn't do it for WRIX

**Comment by jrouzierinverse** [comment]
pfappserver::View::CSV was added for because of wrix (yes it is just for one customer).
Just make sure it did not break it.

**Comment by julsemaan** [comment]
Double checked and WRIX export still works

**Comment by julsemaan** [comment]
Re-review or ready to merge ?

**Comment by jrouzierinverse** [comment]
Has perl-Catalyst-View-CSV been packaged?

**Comment by julsemaan** [comment]
It hasn't, I'll see with @febreeze for the debian package and I'll do the rpm

**Comment by julsemaan** [comment]
Package for CentOS 6 + 7 in devel.

Package for debian in /root/Catalyst-View-CSV on pfbuilder

**Comment by jrouzierinverse** [comment]
Update packetfence.spec and debian/control to include Catalyst::View::CSV as a dependency

**Comment by julsemaan** [comment]
Done, re-review

**Pull request merged**
