### PR TITLE
Build vagrant images for integration tests

### PR DESCRIPTION
**Pull request by nqb**
# Description
Build ready-to-use Vagrant images for integration tests and send them to Vagrant cloud

# Impacts
Integration tests
Pipeline

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature

# NEWS file entries
## Enhancements
* Vagrant images for integration tests

### CODE REVIEW

**Comment by nqb** [comment]
This PR is ready to be reviewed.

I still have an issue with CentOS boxes after build which I'm not able to understand. For now, I suggest we keep `centos/7` boxes (I need to re-add `upgrade_os.yml` in addons/vagrant directory) and I will request help to CentOS community.

**Comment by nqb** [comment]
I missed to disable SELinux before packaging box. Perhaps this is the root cause of my issue. Next pipeline triggered to check if it works.

**Review by JeGoi — APPROVED** [review]
That is fine for me.

**Review by JeGoi — APPROVED** [review]
Better Now!
let's merge it

**Pull request merged**
