### PR TITLE
feature/match-by-rule-action

### LINKED ISSUE #1858: authentication sources: Do not "match" a rule if "requested" action if not configured in it
Authentication sources works on a first hit match. Same for the rules in the source.
We should not match a rule in an authentication if we look for a specific action and that this specific action is not part of the rule.

ie.
- I have 3 rules in my authentication source
- 2 of them are "administration" class, the other one "authentication" class
  - First rule condition is pretty large (almost all employees) and give access to admin interface GUI
  - Second rule condition is also pretty large (but not the same) and allow sponsor
  - Third is not important
- A user is matching first and second rule conditions. When trying to check for sponsor, we match the first and since the "mark_as_sponsor" is not an available action, we bail out.

Need to add the ability of specifying the action we are looking for when trying to match and do not match a rule not containing that action.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
-----------

Do not "match" a rule if "requested" action if not configured in it

Impacts
-----------
Rules matching

NEWS file entries
-------

Enhancements
++++++++++++
* Do not "match" a rule if "requested" action if not configured in it

Fixes #1858

Delete branch after merge
-------------------------
NO

### CODE REVIEW

**Comment by dwlfrth** [comment]
Do we really need those .txt files ?

**Comment by jrouzierinverse** [comment]
nope fixed

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by dwlfrth** [comment]
Is it ready to be reviewed ?

**Comment by jrouzierinverse** [comment]
Yup

**Comment by dwlfrth** [comment]
Please add appropriate labels and milestone

**Comment by jrouzierinverse** [comment]
done

**Comment by dwlfrth** [comment]
Please rebase

**Comment by jrouzierinverse** [comment]
Done

**Comment by extrafu** [comment]
Bump

**Comment by fdurand** [comment]
look good to me, agree to merge

**Comment by dwlfrth** [comment]
I will give it a try tomorrow with my use case and will merge once done.

**Comment by dwlfrth** [comment]
Works as expected

**Pull request merged**
