### PR TITLE
Add copyright without year to avoid useless rpmnew or dpkg-dist files

### LINKED ISSUE #4986: Copyright in conf files caused useless rpmnew or dpkg-dist files during upgrades
Some conf files (see below) contains a copyright which is updated each year. When you make an upgrade, package manager detect those files as new and create useless rpmnew or dpkg-dist files.

Conf files with an Inverse copyright:
```
conf/dhcp_fingerprints.conf
conf/floating_network_device.conf.example
conf/I18N/api/fr.po
conf/I18N/api/en.po
conf/locale/nl/LC_MESSAGES/packetfence.po
conf/locale/de/LC_MESSAGES/packetfence.po
conf/locale/en/LC_MESSAGES/packetfence.po
conf/locale/pl_PL/LC_MESSAGES/packetfence.po
conf/locale/es/LC_MESSAGES/packetfence.po
conf/locale/he_IL/LC_MESSAGES/packetfence.po
conf/locale/fr/LC_MESSAGES/packetfence.po
conf/locale/pt_BR/LC_MESSAGES/packetfence.po
conf/locale/it/LC_MESSAGES/packetfence.po
conf/pfqueue.conf.defaults
conf/pfqueue.conf.example
conf/profiles.conf.defaults
conf/profiles.conf.example
conf/switches.conf.defaults
conf/switches.conf.example
```

**Expected behavior**
From my point of view, we should drop copyright from these files because most of files under `conf` directory doesn't contain any copyright information.

* `conf/locale` subdirectories are marked as "conffiles" in packaging,
* `conf/I18N` files are **not** marked as "conffiles" in packaging

### PR DESCRIPTION
**Pull request by nqb**
# Description
Add copyright without year to avoid useless rpmnew or dpkg-dist files each yearly upgrade

# Impacts
Package upgrade.

# Issue
fixes #4986 

# Delete branch after merge
YES

# NEWS files entries
## Enhancements
* All configuration files have a copyright without year to avoid useless rpmnew or dpkg-dist files each yearly upgrade

### CODE REVIEW

**Comment by julsemaan** [comment]
@extrafu should be stating the copyright removal of these files

**Comment by extrafu** [comment]
Indeed, why does it create an issue?

**Comment by nqb** [comment]
Hello @extrafu,

See #4986. 

If we decide to keep this copyright in conf files, in that case, we should fix all conf files that didn't have a copyright in it (as mentioned in issue)

**Comment by extrafu** [comment]
@nqb Let's do this then - it's a better approach.

**Comment by nqb** [comment]
@extrafu,

> @nqb Let's do this then - it's a better approach.

That's will not solve issue and make yearly upgrade a pain.

Is copyright really necessary in conf files ? I understand the idea for lib files but not for conf files.

**Comment by extrafu** [comment]
It won't make a yearly upgrade a pain if you remove the dates in the (C).

**Comment by nqb** [comment]
> It won't make a yearly upgrade a pain if you remove the dates in the (C).

@extrafu I agree. 

I made changes you requested. But I'm not sure that's a good idea.

By adding a Copyright to all conf files under `conf`, we will generate a lot of rpmnew and dpkg-dist files at next upgrade which is what I would like to avoid when I opened this PR.

**Comment by nqb** [comment]
@extrafu, @julsemaan, what's your opinion on my last comment ?

**Comment by extrafu** [comment]
I honestly don't care about those files. For new installations, it won't be a problem. For upgrades, we'll do them most of the time and can cleanup after.

**Comment by nqb** [comment]
@julsemaan: ready to review.

**Comment by nqb** [comment]
@julsemaan: after merge, we will need to push new .po files to Transifex.

**Comment by julsemaan** [comment]
Merged, you can have fun with the .po now

**Pull request merged**
