### PR TITLE
Feature/add brands icons

### LINKED ISSUE #2228: Adding brand icons
Would be nice to have matching brand icons for specific sources: for instance oauth2/billing icons

### PR DESCRIPTION
**Pull request by whitx**
# Description
Adding brands icons next to sources name and in creation of a source. Available only if the icons is existing in http://fontawesome.io/icons/

# Impacts
Authentication sources list, and source edit.

# Issue
fixes #2228 

# Delete branch after merge
YES 

# NEWS file entries
## Enhancements
* Adding brands icons to authentication source (i.e Twitter, PayPal etc ..) in the administration interface

### CODE REVIEW

**Comment by whitx** [comment]
auth source
twitsource

**Comment by jrouzierinverse** [comment]
The icons should be on the left of the name

**Comment by jrouzierinverse** [comment]
We should also consider having some type of icons for the other sources

**Comment by cgx** [comment]
@jrouzierinverse I would not recommend trying to add an icon for each authentication source. Let's keep the icons for branded OAuth sources only.

**Review by cgx — APPROVED** [review]
👍

**Pull request merged**
