### PR TITLE
feature/resend-sms

### LINKED ISSUE #6318: Re-send SMS feature for SMS registration
Currently you would need to re-do the SMS form to get the SMS PIN again.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Allow the user to resend an SMS pin.

Impacts
=======
The capitive portal.

NEWS file entries
=======================
Enhancements
-------------
* Allow users to resend the SMS pin

Issue
=====
Fixes #6318

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [x] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by extrafu** [comment]
@julsemaan NTH for v11. If you think it's safe and good, let's merge it. Otherwise bump it to v11.1.

**Comment by julsemaan** [comment]
We just need an acceptance test defined in test link for this and we're good

**Comment by extrafu** [comment]
@lzammit Create the test in TestLink please.

**Comment by lzammit** [comment]
Testlink: 👍

**Comment by extrafu** [comment]
@julsemaan Ready to merge then?

**Pull request merged**
