### PR TITLE
Improved LLDP support

### PR DESCRIPTION
**Pull request by obilodeau**
Now exposed as a capability although there's no default implementation yet. We'll need to flesh out what most vendors do first.

Implemented Cisco support kept Nortel as is because I was scared of breaking it.

Pending review and field testing.

NEWS

```
New Hardware
 * Support for LLDP-based VoIP discovery on Cisco Catalyst series

Enhancements
 * LLDP IP Telephone Discovery improvements

```

### CODE REVIEW

**Comment by obilodeau** [comment]
Ideally, the core should log at the INFO level when we have a list of phones MACs looked up. Otherwise it's hard to troubleshoot if CDP / LLDP works.

**Comment by fgaudreault** [comment]
It looks good.  I will add the missing logger.

**Comment by fgaudreault** [comment]
Ready to be merged.

**Comment by aioyou** [comment]
Investigating CI failures on commit [`55a2128f845a1d7c112885a4317391ad744c3859`](https://github.com/inverse-inc/packetfence/commit/55a2128f845a1d7c112885a4317391ad744c3859)...

All 0 checks passed

**Pull request merged**
