### PR TITLE
CI: upgrade Ansible, Vagrant and Packer

### PR DESCRIPTION
**Pull request by nqb**
# Description
Upgrade Ansible to 2.10 
Upgrade Vagrant to 2.2.10 and vagrant-libvirt to 0.2.1
Upgrade Packer to 1.6.5

on GitLab runners, apply changes necessary.

# Impacts
build_img stage + test stage + build_zen stage
Integration with Vagrant
Local tests on Ansible collections

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [x] Document the feature: some changes in Developers guide

### CODE REVIEW

**Comment by nqb** [comment]
I will need to upgrade software on runners before this PR is merged to avoid errors.

**Comment by nqb** [comment]
Even if Vagrant 2.2.13 has been released last week, I will keep 2.2.10 as current version for now.

**Review by JeGoi — APPROVED** [review]
Ok sounds good to me.

**Comment by nqb** [comment]
Upgrade done on runners. I ran a [pipeline](https://gitlab.com/inverse-inc/packetfence/-/pipelines/214017583) to verify everything work as expected.

**Pull request merged**
