### PR TITLE
(web admin) Allow user to extend session

### LINKED ISSUE #4571: Redirect to login screen on token expiration
**Is your feature request related to a problem? Please describe.**
Right now when the token expires, you are allowed to browse the admin and you get redirected to the login when the next API call is done

**Describe the solution you'd like**
It would be good to redirect the user to the login screen when the token expires in the frontend (available in token_info)

**Additional context**
Zammit said it would be nice

### PR DESCRIPTION
**Pull request by cgx**
# Description
Show a modal when the session is about to expire (this delay is currently set to 60 seconds).

# Issue
fixes #4571

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* (web admin) Notify the user when the token is about to expire

### CODE REVIEW

**Comment by extrafu** [comment]
@cgx Who should be the assignee/reviewer?

**Comment by cgx** [comment]
> @cgx Who should be the assignee/reviewer?

@satkunas

**Comment by extrafu** [comment]
@satkunas Please review and merge if all is fine before tomorrow.

**Comment by satkunas** [comment]
Unable to test.

Backend still appears to be sending token expiration far into the future, not respecting the api_activity_timeout in pf.conf.

[@2019-08-27 15:54:33]:
```json
{
expires_at: "2019-08-27T18:04:33.689685217-04:00"
}
```

**Comment by cgx** [comment]
@satkunas Are you sure you're running the latest version of `pfhttpd`?

**Pull request merged**
