### PR TITLE
Adjusted documentation to have systemd manage MariaDB in RHEL/CentOS7…

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description
Adjusted the Clustering guide to instruct configuration of pcs resource using systemd to manage MariaDB rather than manually starting it

# Impacts
None

# Delete branch after merge
YES

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me...
Only documentation changes but I used the PR way to "discuss" possible side effects of using systemd in pcs rather than manually starting it.

**Comment by julsemaan** [comment]
This seems like a no-brainer to me

We already use systemd to manage mariadb in active/active so there was no point in managing it manually using pcs

Unless somebody puts a veto on that, I'll merge it today

**Comment by dwlfrth** [comment]
Applied at a client site last night, still alive.

**Comment by fdurand** [comment]
Looks good to me too. Merge !

**Pull request merged**
