### PR TITLE
feature/remove-configfile-table

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
-----------
Remove the configfile table

Impacts
-----------
pfcmd

NEWS file entries
-------

New Features
++++++++++++

Enhancements
++++++++++++

Bug Fixes
+++++++++

Delete branch after merge
-------------------------
NO

### CODE REVIEW

**Comment by julsemaan** [comment]
image

**Comment by jrouzierinverse** [comment]
Apparently it was used as a way to sync configuration across multiple servers.

**Comment by fdurand** [comment]
Did a search in the code to see if there some call to pf::configfile other than the stuff you removed.
So looks to be good to merge.

**Comment by julsemaan** [comment]
I'd also say its safe to remove it

**Comment by fdurand** [comment]
So we merge ?

**Comment by julsemaan** [comment]
I guess so

**Pull request merged**
