### PR TITLE
Fix unit tests in pipeline

### PR DESCRIPTION
**Pull request by nqb**
# Description
Fix unit tests to make them working in pipeline

# Impacts
RPM and Debian packaging (symlinks)

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
@jrouzierinverse, 

The only test that still failed is related to `packetfence-iptables` service: https://gitlab.com/inverse-inc/packetfence/-/jobs/416064119#L545.

Do you have any idea how to fix it ?

**Comment by jrouzierinverse** [comment]
I will dig into that issue later next week.

**Comment by nqb** [comment]
Ok @jrouzierinverse. You can push directly to this branch and run a pipeline on it to see if it works.

**Comment by nqb** [comment]
@jrouzierinverse, did you find the time to work on it ?

**Comment by nqb** [comment]
@jrouzierinverse, I saw you comment `iptables` unit test in bf6f1c0651732611a9de2c3798834b730772d7fd.

Could you merge this PR if all is fine for you in order to have nightly builds with unit tests working ?

**Comment by nqb** [comment]
Unit tests all fixaid !

**Pull request merged**
