### PR TITLE
Packaging: install favicon in dist directory, remove public directory

### LINKED ISSUE #5325: configurator: missing favicon on Debian
**Describe the bug**
Favicon is not found when reaching `https://IP_MGMT:1443/admin/alt#`

**To Reproduce**
1. Install a fresh Debian 9
2. Try to reach configurator

**Expected behavior**
Favicon should be visible. Added recently by @cgx in https://github.com/inverse-inc/packetfence/commit/76195fe8fc65d19dd5cf3db8c83a0d82ad65474c

**Additional context**
When I reach `/admin/alt`, I got:
```html
<link rel=icon href=/admin/alt/favicon.ico>
```
but `/usr/local/pf/html/pfappserver/root/static.alt/dist` doesn't contains `favicon.ico`.

### PR DESCRIPTION
**Pull request by nqb**
# Description
Install favicon in dist directory, remove public directory

# Impacts
Web admin

# Issue
fixes #5325 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
I wonder if `src` directory should be part of packaging too

**Comment by nqb** [comment]
This fix will only work for CentOS because Makefile target is not used by Debian packaging.

**Comment by julsemaan** [comment]
@nqb will adjust the PR today or tomorrow

**Comment by nqb** [comment]
Closing this for now. I will provide a direct commit for the fix.

**Pull request closed without merging**
