### PR TITLE
Feature/dell n1500

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Support for Dell n1500 v 6.6.0.10

# Impacts
Dell n1500 switch module

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Support for Dell n1500 starting from 6.6.0.10

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Is there anything special someone needs to do after applying this?

**Comment by jrouzierinverse** [comment]
Please provide upgrade instructions

**Comment by extrafu** [comment]
@jrouzierinverse Review and merge if all is fine. Don't forget to update the NEWS file.

**Comment by jrouzierinverse** [comment]
Is there anything special someone needs to do after applying this?

**Comment by fdurand** [comment]
No, nothing, i believe that you don't have a Dell switch at home to test it.

**Comment by julsemaan** [comment]
> No, nothing, i believe that you don't have a Dell switch at home to test it.

Weird assumption, I thought everybody had Dell switches at home except me. I don't feel alone anymore now

**Comment by jrouzierinverse** [comment]
No dell switches

**Comment by Venice-89** [comment]
If you need some testers, we have many Dell switches.

N3000 Series and N1000 Series are available for testing ;)
Let me know if I can help.

**Pull request merged**
