### PR TITLE
Update docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc

### PR DESCRIPTION
**Pull request by xinity**
added DGS-3100 and Aruba Instant OS configuration.

### CODE REVIEW

**Comment by xinity** [comment]
this pull request is far better!
hoping this helps :)

**Comment by xinity** [comment]
any chance this would be added to the next release ?

**Comment by dwlfrth** [comment]
Sure thing. I will merge it soon.
Thanks and sorry for the delays

**Comment by xinity** [comment]
no problem, it's just that i will have many pull request to come
i don't want to spam :)

**Comment by dwlfrth** [comment]
Will be merged into PacketFence v4 since it cannot be automatically merge from the web :)

**Comment by xinity** [comment]
nifty !

Can't wait to get my hands on PacketFence v4

**Comment by extrafu** [comment]
Ok for v4.0.2?

**Comment by dwlfrth** [comment]
Guess what... IT'S IN DEVEL ! ;)
https://github.com/inverse-inc/packetfence/commit/500a945048d20f8bb3d4809a219e7f7729072ff5

**Comment by xinity** [comment]
welcome guys! :)

**Pull request closed without merging**
