### PR TITLE
tests: cancel jobs and halt VM differently

### LINKED ISSUE #7475: tests: cancel a scheduled pipeline if one job in test stage has failed
Currently, a scheduled pipeline will run all tests job even if one test job has failed.
It doesn't really make sense because, packages will not be uploaded to repositories.

On top of that, a new pipeline will need to be run to fix tests.

Proposal: cancel all test jobs which have not start yet once we detect a failure.

### LINKED ISSUE #7488: tests: manage two timeouts
**Describe the problem**
If a job (running on a shell executor) reaches pipeline timeout configured in GitLab, job is canceled by GitLab. However, due to a [GitLab bug](https://gitlab.com/gitlab-org/gitlab/-/issues/15603), jobs are not stopped on runners.

A workaround using `timeout` (provided in another [GitLab issue](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3376) has been put in place to stop jobs.

The workaround is working. However, we need to define a specific timeout for `after_script` because at the moment, an `after_script` can also run for 3hours.

### PR DESCRIPTION
**Pull request by nqb**
# Description
- Cancel all **pending** jobs if an error has been detected during a test job. We don't cancel all jobs because if a shell job is running and canceled by API, job will not be stopped (GitLab bug)
- Don't use `after_script` instruction for test jobs because implicit timeout (5 minutes) is not enough to perform all tasks (especially stopping VM)
- Handle error in test jobs differently to shutdown VM using `script` instruction
- Adjust wrong test on `GITLAB_API_TOKEN`

# Issue
fixes #7488 
fixes #7475 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
Test pipeline: https://gitlab.com/inverse-inc/packetfence/-/pipelines/807105019 (only cancel part)

=> it failed.

New test: https://gitlab.com/inverse-inc/packetfence/-/pipelines/807276606

=> failed again. Shell runners need to have `jq` installed, I will install it.

**Comment by nqb** [comment]
Running a latest pipeline to be sure everything is working as expected: https://gitlab.com/inverse-inc/packetfence/-/pipelines/808481612

@JeGoi, if you are happy with review, we will need to backport this until 11.0.0

**Review by JeGoi — APPROVED** [review]
Looks good to me.

**Comment by JeGoi** [comment]
Add something if it is manual or scheduled

**Pull request merged**
