### PR TITLE
Move pf::config to use @EXPORT_OK

### LINKED ISSUE #1315: Move pf::file_paths to use @EXPORT_OK
Since pf::file_paths exports all its variables to a module namespace (which is just a hash internally) it will increase the memory usage of any module that imports it.

So by moving to EXPORT_OK there will be a reduction of memory across all modules in packetfence ~4 megabytes

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description 

Since pf::config exports all its variables to a module namespace (which is just a hash internally) it will increase the memory usage of any module that imports it.

So by moving to EXPORT_OK there will be a reduction of memory across all modules in packetfence ~5 megabytes

All test have passed
## Impacts

Nothing
## NEWS file entries

Enhancements
++++++++++++
- Reduction of memory usage
## Delete branch after merge

NO

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Bump

**Comment by julsemaan** [comment]
This is as boring to review as it was to make it.

Reviewed it quickly without seeing anything abnormal.

Like pf::file_paths export rework I shall raise the question of the merge-ability for v6 while agreeing with the merge

**Comment by jrouzierinverse** [comment]
You are a brave man to even look at this

**Comment by jrouzierinverse** [comment]
@louismunro do you want to do the honors?

**Comment by louismunro** [comment]
I dub thee Sir Mergealot.

**Comment by rouzier** [comment]
I like big merges I cannot lie

**Pull request merged**
