### PR TITLE
Feature/server hostname info

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description

Displays the server hostname in admin info box
# Impacts

None
# Delete branch after merge

YES
## Enhancements
- Displays the server hostname in the admin info box

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me please

**Comment by julsemaan** [comment]
Looks good to me, me merging

**Comment by dwlfrth** [comment]
Where's my nail polish ? :(

**Comment by julsemaan** [comment]
:nail_care: :rocket: :chicken:

**Pull request merged**
