### PR TITLE
Verify if a user has sponsor rights before allowing them to sponsor a user

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Fixes issue where a non sponsor user can validate a sponsored email
## Impacts

Impacts the sponsored user workflow.
May require an additional rule in the admin source to mark the username as a sponsor
## NEWS file entries

Bug Fixes
+++++++++
Fixes allowing a non-sponsored user to verify a sponsored email address
## Delete branch after merge

NO

### CODE REVIEW

**Comment by julsemaan** [comment]
To clarify your questionning in the description. i dont think theres a need to create additionnal rules since we first lookup the object using the mail field and then pass it through the rules so I think it's good as is.

**Comment by rouzier** [comment]
We would need two rules for in order for this to work.
The first to match the user's email address to see if the email address is a sponsor's email address (this is what we do now)
The second rule is to match the user's name that they enter.
Unless there is another way to figure out if the user is sponsor before allow them to let the user in.

**Comment by julsemaan** [comment]
right now we dont create a rule for the email. we lookup the ldap info from the email. Unless im misunderstanding it. Ill probably just test it to be sure

**Comment by fdurand** [comment]
Tested and it works

**Pull request merged**
