### PR TITLE
New plugin architecture for pfdetect for defining new parsers

### LINKED ISSUE #581: Create configurable pfdetect such as parsers snort,Security Onion,suricata

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

New plugin architecture for pfdetect for defining new parsers
## Impacts

Impacts pfdetect
## NEWS file entries

New Features
++++++++++++
- New plugin architecture for pfdetect for defining new parsers
- Added support for Security Onion in pfdetect

Enhancements
++++++++++++

Bug Fixes
+++++++++

Fixes #581
## Delete branch after merge

NO

### CODE REVIEW

**Comment by julsemaan** [comment]
Missing a few details for the PR description, title,...

**Comment by jrouzierinverse** [comment]
Yeah I saw that

**Comment by jrouzierinverse** [comment]
I need to update the pod docs for examples on how to create a new parser

**Comment by jrouzierinverse** [comment]
@julsemaan  Can we close this?

**Comment by julsemaan** [comment]
Zammit just approved it so that's enough

**Comment by jrouzierinverse** [comment]
Where? I do not believe you

**Comment by julsemaan** [comment]
He's a ninja so his comments cannot be seen to the untrained eye from what he just told me. I usually just believe him

**Comment by jrouzierinverse** [comment]
Ninja and a Spartan I am confused

**Comment by julsemaan** [comment]
You shouldn't. They are even making a movie about it 

image

**Comment by louismunro** [comment]
Not good enough.

**Pull request closed without merging**
