### PR TITLE
Generating the same password multiple times

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

When generating a password each apache process has the same random seed
Which would cause every apache process to create the exact same password
## Impacts

Creating users in the httpd.admin
## NEWS file entries

Bug Fixes
+++++++++
Fixed issue where the same password can be generated multiple times
## Delete branch after merge

NO

### CODE REVIEW

**Comment by extrafu** [comment]
Nice fix!

**Comment by jrouzierinverse** [comment]
Please review

**Comment by fdurand** [comment]
Ok to merge

**Comment by extrafu** [comment]
Should go in 4.6's maint

**Pull request merged**
