### PR TITLE
feature/wrix_endpoint

### LINKED ISSUE #3568: Add WRIX endpoints

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
New wrix endpoint

Fixes #3568

### CODE REVIEW

**Comment by satkunas** [comment]
No `DELETE` method exists in the API, but one exists in Perl libs. This should also be exposed.

```
/usr/local/pf/sbin/pfperl-api get -M DELETE -c '{"id": "id_$$"}' /api/v1/wrix_locations | jq
{
  "errors": [],
  "message": "Unknown path /api/v1/wrix_locations"
}
```

**Comment by satkunas** [comment]
Please document the enpoint(s) in the openapi spec.

**Comment by jrouzierinverse** [comment]
We do not allow deletion on the collection for table tables.

**Comment by extrafu** [comment]
Bump - what's the status on this one?

**Comment by extrafu** [comment]
Bump.

**Pull request merged**
