### PR TITLE
Update and rename Unifi.pm to UniFi.pm

### PR DESCRIPTION
**Pull request by rcmcdonald91**
# Description
(REQUIRED)
Changed all instances of 'Unifi' to be the proper style 'UniFi'

# Impacts
(REQUIRED)
Cosmetic changes to the GUI

# Delete branch after merge
(REQUIRED)
YES

### CODE REVIEW

**Comment by julsemaan** [comment]
Doing this will require an upgrade script to be written so that switches with the type Unifi are changed to UniFi

**Comment by rcmcdonald91** [comment]
I assume the only file that would need to be upgraded is switches.conf?

**Comment by julsemaan** [comment]
Yes that is correct

**Comment by rcmcdonald91** [comment]
`sed -i -e 's/type=Ubiquiti::Unifi/type=Ubiquiti::UniFi/g' /usr/local/pf/conf/switches.conf`

Not sure where this would need to go. But this will replace all instances with the correct type.

Edit: Seems we need a script to put in the /usr/local/pf/addons/upgrade folder?

**Comment by extrafu** [comment]
A script addons/upgrade/to-9.0-unifi-rename.sh should be provided to handle the rename. Pushing to v9.1 until that is provided.

**Pull request closed without merging**
