### PR TITLE
Merge pull request #1 from inverse-inc/devel

### PR DESCRIPTION
**Pull request by bsu3338**
Hope This Works...

### CODE REVIEW

**Comment by bsu3338** [comment]
Hope this workds again

**Comment by bsu3338** [comment]
Hope this works

**Comment by bsu3338** [comment]
Sorry Still learning github

**Comment by louismunro** [comment]
You can't merge your code into our repository (unless I misunderstand what you are trying to do).
That is why it's called a pull "request".

The idea is that you make a request, we review it, and when the time comes we merge it or ask for changes.

Keep trying, you'll get the hang of it eventually :smile:

**Pull request closed without merging**
