### PR TITLE
Added owner fields in radius filter

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Add owner in the radius filter.

# Impacts
Radius filters

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Added the owner info in the radius filters

### CODE REVIEW

**Comment by fdurand** [comment]
BUMP

**Review by nqb — COMMENTED** [review]
When there is no `pid` defined for a node (MAC authentication), would it not generate errors in log ?

I didn't test.

**Comment by julsemaan** [comment]
> When there is no `pid` defined for a node (MAC authentication), would it not generate errors in log ?
> 
> I didn't test.

There should always be a PID AFAIK since default is in the person table

**Review by nqb — APPROVED** [review]
Work as expected. No error messages for MAC Auth.

I was able to test RADIUS filters for authorize and accounting. Accounting requires `filter_in_packetfence_accounting=enabled` in `pf.conf`

**Pull request merged**
