### PR TITLE
fix/6045

### LINKED ISSUE #6045: Locationlog entry is not updated when Called-Station-Id changed
**Describe the bug**
If a node has a locationlog opened on a network device and network device sends a new RADIUS request with an updated Called-Station-Id attribute, locationlog is not updated.

For Unifi AP, we need to send a disconnect request to AP using BSSID as NAS-Identifier. If node roams between two BSSIDs on same AP, locationlog is not updated and PF can send disconnect request with wrong NAS-Identifier to AP. Consequently, we received a Disconnect-NAK with Session-Context-Not-Found.

**To Reproduce**
1. Create a MAC Auth RADIUS request using: 
```console
# cat /opt/mac_auth
User-Name = "77:77:77:77:77:77"
User-Password = "77:77:77:77:77:77"
NAS-IP-Address = 172.17.17.201
NAS-Port = 1
NAS-Port-Type = Ethernet
Service-Type = Call-Check
Called-Station-Id = "00:1a:1e:01:68:f8"
Calling-Station-Id = "77:77:77:77:77:77"
Called-Station-SSID = "Yeah"

# cat /opt/mac_auth | radclient -x 172.17.17.10:1812 auth `cat /usr/local/pf/conf/local_secret`
```
2. Create a second MAC Auth RADIUS request by updating `Called-Station-Id` attribute
3. Check locationlog: it has not been updated with new `Called-Station-Id` value.

**Expected behavior**
`switch_mac` should be updated in `locationlog` table.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Update the location log when the switch mac changes.

NEWS file entries
=======================
Bug Fixes
-------------
* Update the location log when the switch mac changes (#6045)

Issue
=====
Fixes #6045

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Bump!

**Comment by jrouzierinverse** [comment]
Bump!

**Comment by fdurand** [comment]
@nqb  will test it, if it's ok then we merge.

**Comment by nqb** [comment]
I tested this PR on a development setup. 

PF archives current locationlog when it receives a new RADIUS request with an updated Called-Station-Id

**Pull request merged**
