### PR TITLE
Fix/fdb issues bypass

### LINKED ISSUE #2448: Our critical processes aren't protected against a Fingerbank issue
Our portal flow and RADIUS flow aren't protected against a potential issue with the Fingerbank DB and requests will fail due to it even though they don't actually require device profiling info to grant/deny access to the network

We need to protect the following flows from this issue:
- RADIUS 802.1x
- RADIUS MAB
- Portal registration
- iplog update

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Protect RADIUS and portal authentication against a potential issue with the Fingerbank DB

# Impacts
RADIUS + portal flows that use device profiling

# Issue
fixes #2448 

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Ensure RADIUS and portal authentication won't be affected if the Fingerbank database has issues

### CODE REVIEW

**Review by dwlfrth — COMMENTED** [review]
LGTM,
One question: we no longer want to "process_user_agent" at all ?

**Comment by julsemaan** [comment]
@dwlfrth I don't think so, don't really see where this is used anymore but then, I didn't look that much but I'm 95% sure its not related to device profiling anymore

**Comment by dwlfrth** [comment]
Aight.
Squash merge then I will backport

**Comment by dwlfrth** [comment]
Cherry-picked in

- `maintenance/7.1`
- `maintenance/7.0`
- `maintenance/6.5`
- `maintenance/6.4`
- `maintenance/6.3`

**Pull request merged**
