### PR TITLE
Feature/revamped captive portal

### PR DESCRIPTION
**Pull request by cgx**
# Description
Minor revamp of the captive portal so the default CSS is more neutral.

# Impacts
Changes the colours but not the layout.

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Revamped default colours of the captive portal to a more neutral/grayish theme.

# Preview

pf-cp-bg-frame

# New available classes

pf-cp
pf-cp-bg-frame-dark
pf-cp-border
pf-cp-bg frame border
pf-cp-bg

### CODE REVIEW

**Comment by extrafu** [comment]
@julsemaan Can you test this and if all looks good (ie., CSS builds correctly), we can include this in v6.5

**Comment by julsemaan** [comment]
Not sure I really like it that much. The footer font color is almost invisible and the green aup background looks a bit weird

image

**Review by julsemaan — COMMENTED** [review]
Issue with footer color and not sure about the green in the AUP background..

**Comment by cgx** [comment]
@julsemaan You don't seem to have the `frame` class on your main container.

**Comment by cgx** [comment]
You don't have the new default logo neither.

**Comment by julsemaan** [comment]
the logo is a setting I put so its normal its not the same.

Now for the frame class, I'll take any guidance you can give on how it can be missing. I'm running the templates provided in the PR

**Comment by cgx** [comment]
Try with the new css build.

**Comment by julsemaan** [comment]
Already looks better.

Now, for the green AUP, IMO that looks a bit weird for the color, I (still opinionated) preferred it with a neutral background

Don't know what the other guys think about it but it doesn't look like it fits for me

**Comment by julsemaan** [comment]
Discussion with @dwlfrth and @lzammit : 

AUP background could use the same color as the background of the 'I accept the terms'

Green header + text could be the same color as the background (blueish)

**Comment by cgx** [comment]
I think we must have an accent color for titles. How about this red?

screen shot 2017-01-30 at 12 02 32 pm

**Comment by julsemaan** [comment]
I'm not really a reference for that.

But, I still prefer the green over the pink

**Comment by dwlfrth** [comment]
I agree with the accent color but I think this red and the green stands out a bit too much.
Can we try with the PacketFence blue-ish ?

**Comment by cgx** [comment]
Same color as the action buttons?

screen shot 2017-01-30 at 12 41 22 pm

**Comment by dwlfrth** [comment]
Something like ... (warning... GIMP alert)

portal_blue
portal_grey

**Comment by dwlfrth** [comment]
That last one looks good !

**Comment by julsemaan** [comment]
same color as button looks good

**Comment by julsemaan** [comment]
Found a visual glitch

When the 'restart' button appears, it actually brings the logo and the whole layout down

No reset:
image

With reset:
image

**Comment by julsemaan** [comment]
Also, footer doesn't look good on mobile:
image

**Comment by cgx** [comment]
I suggest to move the reset button near the navigation "dots", but in not in this release.

Footer has been fixed.

**Pull request merged**
