### PR TITLE
feature/remove_currently_at

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Remove the need for the currently_at file

Impacts
=======
The configurator 

NEWS file entries
=======================
Enhancements
-------------
* Showing the configurator is now configurable.

UPGRADE file entries
=======================
The file /usr/local/pf/conf/currently-at is no longer needed it can be removed.
```rm -rf /usr/local/pf/conf/currently-at```

### CODE REVIEW

**Comment by nqb** [comment]
We will need to upgrade documentation (Upgrade guide and others) to remove `currently-at` references.

**Comment by jrouzierinverse** [comment]
done

**Comment by extrafu** [comment]
@nqb Just merge it if all is fine.

**Review by nqb — CHANGES_REQUESTED** [review]
New GUI need to display option to enable/disable configurator, not the case right now in Advanced section.

@cgx, can you take a look at this ?

**Comment by nqb** [comment]
@jrouzierinverse: could you add upgrade instructions and/or write a script that delete old currently-at file for users doing upgrades ?

I updated our post-upgrade template added at end of upgrade guide to remove reference to currently-at file in Database schema section.

**Comment by cgx** [comment]
@nqb I've added the toggle button to enable/disable the Configurator.

**Comment by nqb** [comment]
Thanks @cgx, I will wait upgrade instructions or script migration from @jrouzierinverse now.

**Comment by jrouzierinverse** [comment]
Done

**Comment by nqb** [comment]
@jrouzierinverse,

I add another part to your upgrade notes in Upgrade guide. Let me know if it's fine for you.

**Pull request merged**
