### PR TITLE
add file to track fingerbank collector env variables

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Added ability to control the Fingerbank collector environment variables through the PacketFence config

# Impacts
Fingerbank collector

# NEW Package(s) required
fingerbank-collector-1.1.1

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Added ability to control the Fingerbank collector environment variables through the PacketFence config

### CODE REVIEW

**Comment by julsemaan** [comment]
@jrouzierinverse 

Please check this and merge if its fine

Its pretty simple and we can get the collector 1.1.1 in after this gets merged.

If 1.1.1 is not in, it doesn't break either, it will just be an empty non-used file

**Review by jrouzierinverse — CHANGES_REQUESTED** [review]
I found the following three issues
* Make conf/fingerbank-collector.env.defaults an example file
* Provide commented out examples of the allowed variables.
* Update packaging to mark conf/fingerbank-collector.env.defaults as a config file

**Comment by julsemaan** [comment]
There is no point into making this an example file, its made only to push variables for the collector through the maintenance by us, not for usage by users

**Comment by jrouzierinverse** [comment]
Ok no problem just update the packaging so it will not fail.

**Comment by jrouzierinverse** [comment]
Would there ever be a scenario where a user could update the env file.
Then I would suggest the following pattern.

conf/fingerbank-collector.env.example 
conf/fingerbank-collector.env.defaults would have the following content.
```bash
PF_DIR=/usr/local/pf/
ENV="$PF_DIR/conf/fingerbank-collector.env"
if [ -e  "$ENV"  ];then
 . $ENV
fi
```

This pattern allows us to have custom variables for the collector while still allowing us to push variables for collector through the maintenance.

**Comment by julsemaan** [comment]
There isn't really such scenario, if the user should configure stuff in the collector, then this should go through the collector section of fingerbank.conf which already sets up environment variables.

This is really just for maintenance purposes

**Comment by jrouzierinverse** [comment]
Ok then the only thing to do is to update the packaging part then we are good.

**Comment by julsemaan** [comment]
packaging fixed, ready for another review

**Pull request merged**
