### PR TITLE
Feature/opswat api

### PR DESCRIPTION
**Pull request by julsemaan**
NOT READY

### CODE REVIEW

**Comment by louismunro** [comment]
Please update description.

**Comment by louismunro** [comment]
What should we do with this one? 
Rebase if needed.

**Comment by julsemaan** [comment]
that is still a work in progress.

added appropriate tags and removed milestone

**Comment by louismunro** [comment]
Please rebase.

**Comment by extrafu** [comment]
Closing, suspended indefinitely.

**Pull request closed without merging**
