### PR TITLE
Feature/dashboard

### PR DESCRIPTION
**Pull request by lzammit**
New PacketFence dashboard using Netdata info.

### CODE REVIEW

**Comment by extrafu** [comment]
@cgx I suggest this gets reviewed and merged quickly so next week when we start testing, the dashboard "works" (in a sense that it starts pulling stats from netdata). pfstats will get merged also today so we'll have new metrics to utilize early next week.

**Comment by cgx** [comment]
@extrafu I'll push a few fixes/improvements prior to merging.

**Comment by extrafu** [comment]
Great 👍

**Comment by extrafu** [comment]
@julsemaan Please merge.

**Pull request merged**
