### PR TITLE
Feature/api networks

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Add API endpoints for L2 and routed networks
Also add configstores to manage them individually

# Impacts
Unified API

# Delete branch after merge
YES

### CODE REVIEW

**Comment by julsemaan** [comment]
This is missing the spec update since the script to auto-generate the necessary files is not working on this (nor devel) #4105 

We could still merge this without the spec and generate it after the merge once #4105 is fixed

**Comment by satkunas** [comment]
Missing `gateway`, `domain-name`, `nat_enabled`, `fake_mac_enabled`, `named`, and `netmask`.

```json
{
  "items": [
    {
      "dhcp_default_lease_time": "86400",
      "dhcp_end": "10.10.255.246",
      "dhcp_max_lease_time": "86400",
      "dhcp_start": "10.10.0.10",
      "dns": "8.8.8.8",
      "id": "10.10.0.0",
      "ip_assigned": null,
      "ip_reserved": null,
      "not_deletable": false,
      "portal_fqdn": null,
      "type": "inlinel2"
    }
  ],
  "nextCursor": 1,
  "prevCursor": 0,
  "status": 200
}
```

**conf/networks.conf**
```
[10.10.0.0]
dns=8.8.8.8
dhcp_start=10.10.0.10
gateway=10.10.0.2
domain-name=inlinel2.satkunas.com
nat_enabled=enabled
named=enabled
dhcp_max_lease_time=86400
fake_mac_enabled=disabled
dhcpd=enabled
dhcp_end=10.10.255.246
type=inlinel2
netmask=255.255.0.0
dhcp_default_lease_time=86400
```

Furthermore, missing the `[interface *]` sections from conf/pf.conf, or will this be address in an other PR?

**Comment by julsemaan** [comment]
@satkunas 

Can you check this again so we can get this ASAP and it doesn't rot here

**Comment by extrafu** [comment]
@satkunas Please confirm and merge so the GUI work around this can get going.

**Pull request merged**
