### PR TITLE
feature/ha_int_for_reals

### PR DESCRIPTION
**Pull request by jrouzierinverse**
## Description

Store the interface object instead of the interface name for @pf::config::ha_ints
## Impacts

iptables generation and pf admin interface editing
## Delete branch after merge

NO

### CODE REVIEW

**Comment by tlaurion** [comment]
Can't use string ("eth0") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/iptables.pm line 245.

**Comment by jrouzierinverse** [comment]
Do a configreload

**Comment by tlaurion** [comment]
Reason why it was not working was because of a typo in high_availability (high_availability). a config reload makes it work between code changes.

**Comment by tlaurion** [comment]
@fdurand? I'll do a pull request that depends upon this to be merged in devel.

**Pull request merged**
