### PR TITLE
removed useragent/user_agent trigger from security events

### LINKED ISSUE #4120: Security events: have useragent and user_agent in the code
In the security events, we have user_agent in the pfappserver controller and in the conf while the trigger is useragent.

We need to adjust this to be only useragent as it is in the factory

Should be adjusted in at least:
 * html/pfappserver/lib/pfappserver/PacketFence/Controller/SecurityEvent.pm
 * conf/security_events.conf.example
 * conf/security_events.conf.defaults

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Removed the useragent/user_agent trigger in security events

# Impacts
Security events

# Issue
fixes #4120

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Deprecated the useragent and user_agent triggers

# UPGRADE file entries

The useragent and user_agent security event triggers have been deprecated. Performing HTTP User-Agent based detection is extremelly inefficient given the very dynamic nature of HTTP User-Agents. You should instead be using the device trigger which leverages the device profiling performed by Fingerbank. In order to remove any existing useragent trigger, execute the following script:

```
/usr/local/pf/addons/upgrade/to-9.1-security-events-remove-useragent.pl
```

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
rebase

**Comment by extrafu** [comment]
@jrouzierinverse Review and merge ASAP.

**Comment by jrouzierinverse** [comment]
Looks good just needs to be rebased

**Comment by julsemaan** [comment]
rebased

**Comment by jrouzierinverse** [comment]
Missed one place.

html/pfappserver/root/security_event/view.tt

Also, there should be an upgrade script to remove it from the security event triggers.

**Comment by julsemaan** [comment]
Due to the complexity of the triggers (multiple or/and), IMO we're better off with instructions on removing them so that we don't invest a lot of time creating a script that will do nothing in 99% of the deployments. Worst case if its left there it will do nothing

**Comment by jrouzierinverse** [comment]
Currently, we support two formats of triggers.

The simple trigger 'name::val' and the multi-trigger '(name1::val1 & name1::val2)'.

These are not very difficult to parse and remove from the config.

You can even reuse the inflate and deflate methods in pfappserver::Form::Field::Trigger to do this.

```perl
my $trigger_hash = pfappserver::Form::Field::Trigger->inflate($old_trigger);
delete $trigger_hash->{useragent};
my $new_trigger = pfappserver::Form::Field::Trigger->deflate($trigger_hash);
```

Also, if the trigger is left it will not be safely ignored.

```
Aug 26 10:40:23 dev-c7 packetfence: ERROR pfcmd.pl(78124): Invalid trigger useragent:1223. Error was : 'useragent:1223' is invalid at /usr/local/pf/lib/pf/factory/condition/security_event.pm line 113.
 (pfconfig::namespaces::FilterEngine::SecurityEvent::build)
```

**Comment by jrouzierinverse** [comment]
Remember to fix the template html/pfappserver/root/security_event/view.tt

**Comment by julsemaan** [comment]
both items have been handled

**Comment by julsemaan** [comment]
actually still have to adjust the warning since its wrongly placed

**Comment by julsemaan** [comment]
all done, ready for re-review

**Pull request merged**
