### PR TITLE
fix/5495

### LINKED ISSUE #5495: API: Reevaluate access require NODES_CREATE administrative role
**Describe the bug**
If you don't have NODES_CREATE administrative role but NODES_READ and NODES_UPDATE, you can't reevaluate access of a node.

**To Reproduce**
1. Create following admin access:
```ini
[tech]
actions=AUDITING_READ,RADIUS_LOG_READ,NODES_READ,NODES_UPDATE,SECURITY_EVENTS_READ,DHCP_OPTION_82_READ,USERS_READ
allowed_roles=
allowed_node_roles=
description=Technicien niveau 1
allowed_access_levels=
allowed_actions=
```
2. Create a user with this admin access
3. Try to reevaluate access of a node

=> message: "Unauthorized access, lacking the NODES_CREATE administrative role"

**Expected behavior**
NODES_UPDATE administrative role should be enough

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Use PUT for node reevaluate_access to fix issue with admin_role actions mapping.

Impacts
=======
Mapping of reevaluate_access of admin roles action

NEWS file entries
=======================

Enhancements
-------------
* Use PUT for node reevaluate_access to fix issue with admin_role actions mapping.

Issue
=====
fixes #5495

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by nqb** [comment]
I wonder if restart switchport should not be handle the same way.

**Comment by jrouzierinverse** [comment]
Which other actions should we move to PUT

**Comment by nqb** [comment]
`fingerbank_refresh` and `apply_security_event` are POST actions like `restart_switchport`.

From my point of view, if you give `NODES_UPDATE` privilege to a user, he should be able to perform all these actions. All these actions are related to nodes but I don't know implications about doing such changes.

@julsemaan, what's your opinion ?

**Comment by satkunas** [comment]
Will we need to move `bulk_reevaluate_access` from POST to PUT as well?

**Comment by julsemaan** [comment]
> Will we need to move `bulk_reevaluate_access` from POST to PUT as well?

Anything that modifies a node and doesn't actually create it needs to be a PUT so that the ACL map properly

**Comment by satkunas** [comment]
@julsemaan here's a list of additional endpoint that may need to be modified:

* [ ] - applySecurityEventNode: data => {
    return apiCall.post(['node', data.mac, 'apply_security_event'], data).then(response => {

* [ ] - clearSecurityEventNode: data => {
  return apiCall.post(['node', data.mac, 'close_security_event'], data).then(response => {

* [ ] - refreshFingerbankNode: mac => {
  return apiCall.postQuiet(['node', mac, 'fingerbank_refresh']).then(response => {

* [ ] - restartSwitchportNode: mac => {
  return apiCall.postQuiet(['node', mac, 'restart_switchport']).then(response => {

* [ ] - bulkRegisterNodes: body => {
  return apiCall.post(['nodes', 'bulk_register'], body).then(response => {

* [ ] - bulkDeregisterNodes: body => {
  return apiCall.post(['nodes', 'bulk_deregister'], body).then(response => {

* [ ] - bulkApplySecurityEvent: body => {
  return apiCall.post(['nodes', 'bulk_apply_security_event'], body).then(response => {

* [ ] - bulkCloseSecurityEvents: body => {
  return apiCall.post(['nodes', 'bulk_close_security_events'], body).then(response => {

* [ ] - bulkApplyRole: body => {
  return apiCall.post(['nodes', 'bulk_apply_role'], body).then(response => {

* [ ] - bulkApplyBypassRole: body => {
  return apiCall.post(['nodes', 'bulk_apply_bypass_role'], body).then(response => {

* [ ] - bulkReevaluateAccess: body => {
  return apiCall.post(['nodes', 'bulk_reevaluate_access'], body).then(response => {

* [ ] - bulkRefreshFingerbank: body => {
  return apiCall.post(['nodes', 'bulk_fingerbank_refresh'], body).then(response => {

* [ ] - bulkRestartSwitchport: body => {
  return apiCall.post(['nodes', 'bulk_restart_switchport'], body).then(response => {

* [ ] - bulkApplyBypassVlan: body => {
  return apiCall.post(['nodes', 'bulk_apply_bypass_vlan'], body).then(response => {

* [ ] - bulkImport: body => {
  return apiCall.post(['nodes', 'bulk_import'], body).then(response => {

**Comment by jrouzierinverse** [comment]
Please review

**Pull request merged**
